[build]
    publish = "dist"
    base = "content/hibernate"


[build.environment]
    REPO_NAME = "mongodb-hibernate"
    SECRETS_SCAN_ENABLED = "false"
    MUT_COMMANDS_ENABLED = "false"

[context.production.environment]
    ENV = "dotcomprd"

[context.preprd.environment]
    ENV = "dotcomstg"

[context.deploy-preview.environment]
    ENV = "prd"

[context.branch-deploy.environment]
    ENV = "prd"

[context.preview-server.environment]
    ENV = "prd"

[context.dev.environment]
    ENV = "stg"


### OFFLINE REDIRECTS
### ALIAS REDIRECTS
### WILDCARD REDIRECTS
### PAGE-SPECIFIC REDIRECTS (divided into subsections by version, if applicable)
### CATCH ALLS
 ##redirects any pages not at any of the active versions to current (makes eol's technically unecessary)


### CATCH ALLS (add slug to paths without slug)
 
[[redirects]]
from = "/docs/languages/java/mongodb-hibernate/current/*"
to = "/docs/languages/java/mongodb-hibernate/current/:splat"
status = 200
 
[[redirects]]
from = "/docs/languages/java/mongodb-hibernate/upcoming/*"
to = "/docs/languages/java/mongodb-hibernate/upcoming/*"
status = 200
 
[[redirects]]
from = "/docs/languages/java/mongodb-hibernate/*"
to = "/docs/languages/java/mongodb-hibernate/current/:splat"

[[redirects]]
from = "/docs/languages/java/mongodb-hibernate/:version/model-data/"
to = "/docs/languages/java/mongodb-hibernate/:version/model-data/entities/"

[[redirects]]
from = "/docs/languages/java/mongodb-hibernate/:version/interact-data/"
to = "/docs/languages/java/mongodb-hibernate/:version/interact-data/crud/"