name = "sql-interface"
title = "SQL Interface"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
              ]

toc_landing_pages = [
    "/content", 
    "/tutorials",
]

[constants]
abic = "Atlas BI Connector"
adf = "Atlas Data Federation"
asql = "MongoSQL"
atlas-ui = "Atlas UI"
aws = ":abbr:`AWS (Amazon Web Services)`"
AWS = ":abbr:`AWS (Amazon Web Services)`"
avs = "MongoDB Vector Search"
azure = "Microsoft Azure"
cluster = "cluster"
Cluster = "Cluster"
clusters = "clusters"
Clusters = "Clusters"
df = "Data Federation"
fdi = "federated database instance"
Fdi = "Federated database instance"
FDI = "Federated Database Instance"
MongoDB-Enterprise = "`MongoDB Enterprise <https://www.mongodb.com/try/download/enterprise>`__"
mongosh = ":binary:`~bin.mongosh`"
mql = ":abbr:`MQL (MongoDB Query Language)`"
oidc = ":abbr:`OIDC (OpenID Connect)`"
schema-builder = "MongoDB SQL Schema Builder"
interface = "SQL Interface"
sql-interface = "SQL Interface"
sql-odbc-version = "1.4.3"
a-service = "an Atlas"
A-service = "An Atlas"
service = "Atlas"
Service = "Atlas"

[substitutions]
a-service = "an Atlas"
aws = ":abbr:`AWS (Amazon Web Services)`"
azure = ":abbr:`Azure (Microsoft Azure)`"
bic-full = ":bic:`MongoDB Connector for BI </>`"
bic-short-no-link = "BI Connector"
bi = ":abbr:`BI (Business Intelligence)`"
bson = ":abbr:`BSON (Binary Javascript Object Notation)`"
dns = ":abbr:`DNS (Domain Name System)`"
fts = "MongoDB Search"
gcp = "Google Cloud"
jdbc = ":abbr:`JDBC (Java Database Connectivity)`"
k8s = "Kubernetes"
odbc = ":abbr:`ODBC (Open Database Connectivity)`"
oidc = ":abbr:`OIDC (OpenID Connect)`"
s3 = ":abbr:`S3 (Simple Storage Service)`"
service = "Atlas"
ui-org-menu = ":icon-mms:`office` :guilabel:`Organizations` menu"
uri = ":abbr:`URI (Uniform Resource Identifier)`"

[[composables]]
id = "os"
title = "Operating System"
default = "macos"
dependencies = [{deployment-type = "self"}]
options = [
   {id = "macos", title = "macOS"},
   {id = "windows", title = "Windows"},
   {id = "linux", title = "Linux"},
]

[[composables]]
id = "sql-driver"
title = "Driver"
default = "power-bi"
options = [
   {id = "power-bi", title = "Power BI"},
   {id = "tableau", title = "Tableau"},
   {id = "dbeaver", title = "DBeaver"},
   {id = "odbc", title = "ODBC Driver"},
   {id = "jdbc", title = "JDBC Driver"},
]