name = "node"
title = "Node.js Driver"
eol = true

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

toc_landing_pages = [
    "/get-started",
    "/connect",
    "/security",
    "/security/authentication",
    "/data-formats",
    "/connect/connection-options",
    "/aggregation",
    "/crud",
    "/crud/update",
    "/crud/transactions",
    "/monitoring-and-logging",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
version = "6.10"
api = "https://mongodb.github.io/node-mongodb-native/{+version+}"
driver-long = "MongoDB Node.js driver"
driver-short = "Node.js driver"
mdb-server = "MongoDB Server"
min-node-version = "v16"
stable-api = "Stable API"
vector-search = "MongoDB Vector Search"
search = "MongoDB Search"
language = "JavaScript"
environment = "Node.js"
docs-url = "https://www.mongodb.com/docs/drivers/node/current/"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <{+docs-url+}>`__ to learn how to `upgrade your version of the {+driver-short+} <{+docs-url+}/reference/upgrade>`__.\
    """