apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: log-rotate
  namespace: mongodb
spec:
  podSpec:
    podTemplate:
      spec:
        containers:
        - name: mongodb-enterprise-database
          env:
          - name: READINESS_PROBE_LOGGER_MAX_SIZE
            value: "50"
  version: 8.0.0
  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials
  type: Standalone
  persistent: false
  # https://docs.opsmanager.mongodb.com/current/reference/mongodb-agent-settings/
  agent:
    startupOptions:
      maxLogFiles: 10
      maxLogFileSize: 2
    readinessProbe:
      environmentVariables:
        READINESS_PROBE_LOGGER_MAX_SIZE: 10
        READINESS_PROBE_LOGGER_BACKUPS: 1
        READINESS_PROBE_LOGGER_MAX_AGE: 3
        READINESS_PROBE_LOGGER_COMPRESS: true
        MDB_WITH_AGENT_FILE_LOGGING: false
        LOG_FILE_PATH: /var/log/mongodb-mms-automation/readiness.log
    backupAgent:
      logRotate:
        sizeThresholdMB: 10
        timeThresholdHrs: 10
    monitoringAgent:
      logRotate:
        sizeThresholdMB: 10
        timeThresholdHrs: 10
    # For Ops Manager 6, you can only configure mongod logs with this setting starting with version 6.0.2.
    # For Ops Manager 7, you can only configure mongod logs with this setting starting with version 7.0.4.
    # For previous Ops Manager versions, you must configure mongod logs using the Ops Manager UI.
    mongod:
      logRotate:
        sizeThresholdMB: 10
        timeThresholdHrs: 10
        numUncompressed: 10
        numTotal: 10
        percentOfDiskspace: 10
      auditLogRotate:
        sizeThresholdMB: 10
        timeThresholdHrs: 10
        numUncompressed: 10
        numTotal: 10
        percentOfDiskspace: 10