name = "kotlin-sync"
title = "Kotlin Sync Driver"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

toc_landing_pages = [
    "/connect",
    "/indexes",
    "/data-formats",
    "/builders",
    "/aggregation",
    "/connect/connection-options",
    "/logging-and-monitoring",
    "/databases-and-collections",
    "/security/authentication"
]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-long = "MongoDB Kotlin Sync Driver"
driver-short = "Kotlin Sync driver"
language = "Kotlin"
version-number = "5.5"
full-version = "{+version-number+}.2"
version = "v{+version-number+}"
mdb-server = "MongoDB Server"
stable-api = "Stable API"
api-root = "https://mongodb.github.io/mongo-java-driver/{+version-number+}/apidocs"
driver-api = "{+api-root+}/driver-kotlin-sync/mongodb-driver-kotlin-sync/com.mongodb.kotlin.client"
core-api = "{+api-root+}/driver-core/com/mongodb"
kotlin-docs = "https://kotlinlang.org"
serialization-version = "1.6.0"
kotlinx-dt-version = "0.6.1"
mongocrypt-version = "{+full-version+}"
logbackVersion = "1.2.11"
log4j2Version = "2.17.1"
search = "MongoDB Search"
vector-search = "MongoDB Vector Search"
