[build]
publish = "dist"
base = "content/csharp"

[build.environment]
REPO_NAME = "docs-csharp"
SECRETS_SCAN_ENABLED = "false"
MUT_COMMANDS_ENABLED = "false"

[context.production.environment]
ENV = "dotcomprd"

[context.preprd.environment]
ENV = "dotcomstg"

[context.deploy-preview.environment]
ENV = "prd"

[context.branch-deploy.environment]
ENV = "prd"

[context.preview-server.environment]
ENV = "prd"

[context.dev.environment]
ENV = "stg"


### OFFLINE REDIRECTS
### ALIAS REDIRECTS
### PAGE-SPECIFIC REDIRECTS
### WILDCARD REDIRECTS
### CATCH ALLS
## redirects any pages not at any of the active versions to current (makes eols technically unnecessary)

### OFFLINE REDIRECTS


### ALIAS REDIRECTS
[[redirects]]
from = "/docs/drivers/csharp/v3.x/*"
to = "/docs/drivers/csharp/current/:splat"
status = 302

[[redirects]]
from = "/docs/drivers/csharp/upcoming/*"
to = "/docs/drivers/csharp/current/:splat"

### VERSION CONSOLIDATION
[[redirects]]
from = "/docs/drivers/csharp/v3.6/*"
to = "/docs/drivers/csharp/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v3.5/*"
to = "/docs/drivers/csharp/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v3.4/*"
to = "/docs/drivers/csharp/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v3.3/*"
to = "/docs/drivers/csharp/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v3.2/*"
to = "/docs/drivers/csharp/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v3.1/*"
to = "/docs/drivers/csharp/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v3.0/*"
to = "/docs/drivers/csharp/v3.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.30/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.29/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.28/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.27/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.26/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.25/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.24/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.23/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.22/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.21/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.20/*"
to = "/docs/drivers/csharp/v2.x/:splat"

[[redirects]]
from = "/docs/drivers/csharp/v2.19/*"
to = "/docs/drivers/csharp/v2.x/:splat"

### PAGE-SPECIFIC REDIRECTS
## v3.x
[[redirects]]
from = "/docs/drivers/csharp/v3.x/fundamentals/enterprise-authentication/"
to = "/docs/drivers/csharp/v3.x/security/authentication/"

[[redirects]]
from = "/docs/drivers/csharp/v3.x/upgrade/"
to = "/docs/drivers/csharp/v3.x/reference/upgrade/"

[[redirects]]
from = "/docs/drivers/csharp/v3.x/upgrade/v2/"
to = "/docs/drivers/csharp/v3.x/reference/upgrade/v2/"

[[redirects]]
from = "/docs/drivers/csharp/v3.x/upgrade/v3/"
to = "/docs/drivers/csharp/v3.x/reference/upgrade/v3/"

## v2.x
[[redirects]]
from = "/docs/drivers/csharp/v2.x/upgrade/v2/"
to = "/docs/drivers/csharp/v2.x/upgrade/"

[[redirects]]
from = "/docs/drivers/csharp/v2.x/upgrade/v3/"
to = "/docs/drivers/csharp/v2.x/upgrade/"

## CURRENT
[[redirects]]
from = "/docs/drivers/csharp/current/fundamentals/enterprise-authentication/"
to = "/docs/drivers/csharp/current/security/authentication/"

[[redirects]]
from = "/docs/drivers/csharp/current/upgrade/"
to = "/docs/drivers/csharp/current/reference/upgrade/"

[[redirects]]
from = "/docs/drivers/csharp/current/upgrade/v2/"
to = "/docs/drivers/csharp/current/reference/upgrade/v2/"

[[redirects]]
from = "/docs/drivers/csharp/current/upgrade/v3/"
to = "/docs/drivers/csharp/current/reference/upgrade/v3/"

### WILDCARD REDIRECTS
[[redirects]]
from = "/docs/drivers/csharp/:version/compatibility/"
to = "/docs/drivers/compatibility/"

[[redirects]]
from = "/docs/drivers/csharp/:version/reference/compatibility/"
to = "/docs/drivers/compatibility/"

[[redirects]]
from = "/docs/drivers/csharp/:version/connection-troubleshooting/"
to = "/docs/drivers/csharp/:version/connect/connection-troubleshooting/"

[[redirects]]
from = "/docs/drivers/csharp/:version/crud/query/specify-documents-to-return/"
to = "/docs/drivers/csharp/:version/crud/query/specify-documents/"

[[redirects]]
from = "/docs/drivers/csharp/:version/crud/query/specify-query/"
to = "/docs/drivers/csharp/:version/crud/query/query-filter/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/"
to = "/docs/drivers/csharp/:version/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/aggregation/"
to = "/docs/drivers/csharp/:version/aggregation/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/atlas-search/"
to = "/docs/drivers/csharp/:version/atlas-search/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/authentication/"
to = "/docs/drivers/csharp/:version/security/authentication/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/authentication/aws-iam/"
to = "/docs/drivers/csharp/:version/security/authentication/aws-iam/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/authentication/kerberos/"
to = "/docs/drivers/csharp/:version/security/authentication/kerberos/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/authentication/ldap/"
to = "/docs/drivers/csharp/:version/security/authentication/ldap/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/authentication/oidc/"
to = "/docs/drivers/csharp/:version/security/authentication/oidc/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/authentication/scram/"
to = "/docs/drivers/csharp/:version/security/authentication/scram/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/authentication/x509/"
to = "/docs/drivers/csharp/:version/security/authentication/x509/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/bson/"
to = "/docs/drivers/csharp/:version/document-formats/bson/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/builders/"
to = "/docs/drivers/csharp/:version/crud/update-one/fields/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/class-mapping/"
to = "/docs/drivers/csharp/:version/serialization/class-mapping/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/connection/"
to = "/docs/drivers/csharp/:version/connect/mongoclient/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/connection/connect/"
to = "/docs/drivers/csharp/:version/connect/mongoclient/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/connection/connection-options/"
to = "/docs/drivers/csharp/:version/connect/connection-options/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/connection/connection-pools/"
to = "/docs/drivers/csharp/:version/connect/connection-options/connection-pools/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/connection/network-compression/"
to = "/docs/drivers/csharp/:version/connect/connection-options/network-compression/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/connection/server-selection/"
to = "/docs/drivers/csharp/:version/connect/connection-options/server-selection/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/connection/tls/"
to = "/docs/drivers/csharp/:version/security/tls-ssl/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/"
to = "/docs/drivers/csharp/:version/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/read-operations/"
to = "/docs/drivers/csharp/:version/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/read-operations/change-streams/"
to = "/docs/drivers/csharp/:version/logging-and-monitoring/change-streams/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/read-operations/distinct/"
to = "/docs/drivers/csharp/:version/crud/query/distinct/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/read-operations/project/"
to = "/docs/drivers/csharp/:version/crud/query/project/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/read-operations/retrieve/"
to = "/docs/drivers/csharp/:version/crud/query/find/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/read-operations/specify-documents-to-return/"
to = "/docs/drivers/csharp/:version/crud/query/specify-documents-to-return/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/"
to = "/docs/drivers/csharp/:version/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/bulk-write/"
to = "/docs/drivers/csharp/:version/crud/bulk-write/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/change/"
to = "/docs/drivers/csharp/:version/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/delete/"
to = "/docs/drivers/csharp/:version/crud/delete/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/insert/"
to = "/docs/drivers/csharp/:version/crud/insert/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/modify/"
to = "/docs/drivers/csharp/:version/crud/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/replace/"
to = "/docs/drivers/csharp/:version/crud/replace/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/update-many/"
to = "/docs/drivers/csharp/:version/crud/update-many/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/update-many/arrays/"
to = "/docs/drivers/csharp/:version/crud/update-many/arrays/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/update-many/fields/"
to = "/docs/drivers/csharp/:version/crud/update-many/fields/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/update-one/"
to = "/docs/drivers/csharp/:version/crud/update-one/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/update-one/arrays/"
to = "/docs/drivers/csharp/:version/crud/update-one/arrays/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/write-operations/update-one/fields/"
to = "/docs/drivers/csharp/:version/crud/update-one/fields/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/data-formats/bson/"
to = "/docs/drivers/csharp/:version/document-formats/bson/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/data-formats/guid-serialization/"
to = "/docs/drivers/csharp/:version/serialization/guids/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/data-formats/poco/"
to = "/docs/drivers/csharp/:version/serialization/poco/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/data-formats/polymorphism/"
to = "/docs/drivers/csharp/:version/serialization/polymorphic-objects/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/database-collection/"
to = "/docs/drivers/csharp/:version/databases-collections/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/databases-collections/run-command/"
to = "/docs/drivers/csharp/:version/run-command/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/encrypt-fields/"
to = "/docs/drivers/csharp/:version/security/in-use-encryption/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/geo/"
to = "/docs/drivers/csharp/:version/crud/geo/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/gridfs/"
to = "/docs/drivers/csharp/:version/crud/gridfs/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/indexes/"
to = "/docs/drivers/csharp/:version/indexes/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/linq/"
to = "/docs/drivers/csharp/:version/aggregation/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/logging/"
to = "/docs/drivers/csharp/:version/logging-and-monitoring/logging/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/monitoring/"
to = "/docs/drivers/csharp/:version/logging-and-monitoring/monitoring/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/odata/"
to = "/docs/drivers/csharp/:version/integrations/odata/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/read-write-configuration/"
to = "/docs/drivers/csharp/:version/crud/configure/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/serialization/"
to = "/docs/drivers/csharp/:version/serialization/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/serialization/class-mapping/"
to = "/docs/drivers/csharp/:version/serialization/class-mapping/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/serialization/poco/"
to = "/docs/drivers/csharp/:version/serialization/poco/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/serialization/polymorphic-objects/"
to = "/docs/drivers/csharp/:version/serialization/polymorphic-objects/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/specify-query/"
to = "/docs/drivers/csharp/:version/crud/query/specify-query/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/stable-api/"
to = "/docs/drivers/csharp/:version/connect/connection-options/stable-api/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/time-series/"
to = "/docs/drivers/csharp/:version/time-series/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/transactions/"
to = "/docs/drivers/csharp/:version/crud/transactions/"

[[redirects]]
from = "/docs/drivers/csharp/:version/get-started/create-connection-string/"
to = "/docs/drivers/csharp/:version/get-started/"

[[redirects]]
from = "/docs/drivers/csharp/:version/get-started/deploy-cluster/"
to = "/docs/drivers/csharp/:version/get-started/"

[[redirects]]
from = "/docs/drivers/csharp/:version/get-started/download-driver/"
to = "/docs/drivers/csharp/:version/get-started/"

[[redirects]]
from = "/docs/drivers/csharp/:version/get-started/run-sample-query/"
to = "/docs/drivers/csharp/:version/get-started/"

[[redirects]]
from = "/docs/drivers/csharp/:version/previous-versions/"
to = "/docs/drivers/csharp/:version/reference/previous-versions/"

[[redirects]]
from = "/docs/drivers/csharp/:version/quick-reference/"
to = "/docs/drivers/csharp/:version/reference/quick-reference/"

[[redirects]]
from = "/docs/drivers/csharp/:version/usage-examples/"
to = "/docs/drivers/csharp/:version/"

[[redirects]]
from = "/docs/drivers/csharp/:version/whats-new/"
to = "/docs/drivers/csharp/:version/reference/release-notes/"

[[redirects]]
from = "/docs/drivers/csharp/:version/connect/"
to = "/docs/drivers/csharp/:version/connect/mongoclient/"

[[redirects]]
from = "/docs/drivers/csharp/:version/crud/"
to = "/docs/drivers/csharp/:version/crud/insert/"

[[redirects]]
from = "/docs/drivers/csharp/:version/crud/query/"
to = "/docs/drivers/csharp/:version/crud/query/query-filter/"

[[redirects]]
from = "/docs/drivers/csharp/:version/document-formats/"
to = "/docs/drivers/csharp/:version/document-formats/bson/"

[[redirects]]
from = "/docs/drivers/csharp/:version/logging-and-monitoring/"
to = "/docs/drivers/csharp/:version/logging-and-monitoring/logging/"

[[redirects]]
from = "/docs/drivers/csharp/:version/reference/"
to = "/docs/drivers/csharp/:version/reference/quick-reference/"

[[redirects]]
from = "/docs/drivers/csharp/:version/security/"
to = "/docs/drivers/csharp/:version/authentication/"

[[redirects]]
from = "/docs/drivers/csharp/:version/fundamentals/crud/restful-api-tutorial/"
to = "/docs/drivers/csharp/:version/crud/restful-api-tutorial/"

#Online versions: dict_keys(['upcoming', 'current', 'v3.5', 'v3.4', 'v3.3', 'v3.2', 'v3.1', 'v3.0', 'v2.30', 'v2.29', 'v2.28'])
### CATCH ALLS (Redirects any /docs/drivers/csharp/ page that would've 404ed to the version's landing page)


### CATCH ALLS (add slug to paths without slug)
[[redirects]]
from = "/docs/drivers/csharp/current/*"
to = "/docs/drivers/csharp/current/:splat"
status = 200

[[redirects]]
from = "/docs/drivers/csharp/*"
to = "/docs/drivers/csharp/current/:splat"
