git:
  remote:
    upstream: 'mongodb/docs'
    tools: 'mongodb/docs-tools'
project:
  name: 'primer'
  tag: 'primer'
  url: 'http://docs.mongodb.org/primer'
  title: 'MongoDB Primer'
  branched: false
  editions:
    - name: shell
      branched: false
    - name: python
      branched: false
    - name: python
      branched: false
version:
  release: '2.6.1'
  branch: '2.6'
system:
  files:
    - 'integration.yaml'
    - 'push.yaml'
    - 'sphinx_local.yaml'
    - 'intersphinx.yaml'
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
  - branch: primer-dataset
    path: build/dataset
    repository: https://github.com/mongodb/docs-assets.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'
...