---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-prereq-java-AggregatePrimer.java
truncate:
   start-after: 21
   end-before: 27
---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-java-group-documents-by-a-field-and-calculate-count.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 35
   end-before: 38
---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-java-group-documents-by-a-field-and-calculate-count-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 39
   end-before: 41
---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-java-group-documents-by-a-field-and-calculate-count-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 41
   end-before: 48
---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-java-group-documents-by-a-field-and-calculate-count-results.txt
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 51
   end-before: 58
---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-java-filter-and-group-documents.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 68
   end-before: 72
---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-java-filter-and-group-documents-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 73
   end-before: 75
---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-java-filter-and-group-documents-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 75
   end-before: 82
---
source: build/java-examples/driver/src/examples/primer/AggregatePrimer.java
target: includes/example-java-filter-and-group-documents-results.txt
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 85
   end-before: 91
---
source: build/java-examples/driver/src/examples/primer/InsertPrimer.java
target: includes/example-prereq-java-InsertPrimer.java
truncate:
   start-after: 21
   end-before: 30
---
source: build/java-examples/driver/src/examples/primer/InsertPrimer.java
target: includes/example-java-insert-a-document.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 38
   end-before: 60
---
source: build/java-examples/driver/src/examples/primer/InsertPrimer.java
target: includes/example-java-insert-a-document-post.txt
transform: 
  regex: "^        // @post: "
  replace: ""
truncate:
   start-after: 61
   end-before: 63
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-prereq-java-QueryPrimer.java
truncate:
   start-after: 21
   end-before: 29
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-all.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 37
   end-before: 39
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-all-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 40
   end-before: 42
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-all-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 42
   end-before: 49
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-and.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 58
   end-before: 61
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-and-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 62
   end-before: 64
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-and-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 64
   end-before: 71
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-and-pre2.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 72
   end-before: 74
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-and-pre2.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 74
   end-before: 76
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-or.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 85
   end-before: 89
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-or-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 90
   end-before: 92
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-or-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 92
   end-before: 99
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-or-pre2.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 100
   end-before: 102
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-logical-or-pre2.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 102
   end-before: 104
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-top-level-field.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 112
   end-before: 115
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-top-level-field-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 116
   end-before: 118
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-top-level-field-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 118
   end-before: 125
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-top-level-field-pre2.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 126
   end-before: 128
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-top-level-field-pre2.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 128
   end-before: 130
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-embedded-document.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 137
   end-before: 140
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-embedded-document-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 141
   end-before: 143
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-embedded-document-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 143
   end-before: 150
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-embedded-document-pre2.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 151
   end-before: 153
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-embedded-document-pre2.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 153
   end-before: 155
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-field-in-array.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 162
   end-before: 165
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-field-in-array-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 166
   end-before: 168
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-field-in-array-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 168
   end-before: 175
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-field-in-array-pre2.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 176
   end-before: 178
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-query-field-in-array-pre2.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 178
   end-before: 180
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-greater-than.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 187
   end-before: 190
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-greater-than-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 191
   end-before: 193
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-greater-than-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 193
   end-before: 200
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-greater-than-pre2.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 201
   end-before: 203
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-greater-than-pre2.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 203
   end-before: 205
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-less-than.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 212
   end-before: 215
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-less-than-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 216
   end-before: 218
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-less-than-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 218
   end-before: 225
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-less-than-pre2.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 226
   end-before: 228
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-less-than-pre2.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 228
   end-before: 230
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-sort.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 238
   end-before: 241
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-sort-pre1.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 242
   end-before: 244
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-sort-pre1.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 244
   end-before: 251
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-sort-pre2.txt
transform: 
  regex: "^        // @pre: "
  replace: ""
truncate:
   start-after: 252
   end-before: 254
---
source: build/java-examples/driver/src/examples/primer/QueryPrimer.java
target: includes/example-java-sort-pre2.java
transform: 
  - regex: "^        "
    replace: ""
truncate:
   start-after: 254
   end-before: 256
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-prereq-java-UpdatePrimer.java
truncate:
   start-after: 20
   end-before: 24
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-java-update-top-level-fields.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 37
   end-before: 41
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-java-update-top-level-fields-post.txt
transform: 
  - regex: "^        "
    replace: ""
  - regex: "^    "
    replace: ""
truncate:
   start-after: 44
   end-before: 47
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-java-update-embedded-field.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 55
   end-before: 59
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-java-update-embedded-field-post.txt
transform: 
  - regex: "^        "
    replace: ""
  - regex: "^    "
    replace: ""
truncate:
   start-after: 61
   end-before: 64
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-java-update-multiple-documents.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 75
   end-before: 79
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-java-update-multiple-documents-post.txt
transform: 
  - regex: "^        "
    replace: ""
  - regex: "^    "
    replace: ""
truncate:
   start-after: 82
   end-before: 85
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-java-replace-document.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 95
   end-before: 104
---
source: build/java-examples/driver/src/examples/primer/UpdatePrimer.java
target: includes/example-java-replace-document-post.txt
transform: 
  - regex: "^       "
    replace: ""
  - regex: "^    "
    replace: ""
truncate:
   start-after: 106
   end-before: 109
---
source: build/java-examples/driver/src/examples/primer/IndexesPrimer.java
target: includes/example-prereq-java-IndexesPrimer.java
truncate:
   start-after: 22
   end-before: 24
---
source: build/java-examples/driver/src/examples/primer/IndexesPrimer.java
target: includes/example-java-single-field-index.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 32
   end-before: 34
---
source: build/java-examples/driver/src/examples/primer/IndexesPrimer.java
target: includes/example-java-single-field-index-post.txt
transform: 
  regex: "^        // @post: "
  replace: ""
truncate:
   start-after: 35
   end-before: 37
---
source: build/java-examples/driver/src/examples/primer/IndexesPrimer.java
target: includes/example-java-create-compound-index.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 43
   end-before: 45
---
source: build/java-examples/driver/src/examples/primer/IndexesPrimer.java
target: includes/example-java-create-compound-index-post.txt
transform: 
  regex: "^        // @post: "
  replace: ""
truncate:
   start-after: 46
   end-before: 48
---
source: build/java-examples/driver/src/examples/primer/RemovePrimer.java
target: includes/example-prereq-java-RemovePrimer.java
truncate:
   start-after: 21
   end-before: 23
---
source: build/java-examples/driver/src/examples/primer/RemovePrimer.java
target: includes/example-java-remove-matching-documents.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 30
   end-before: 32
---
source: build/java-examples/driver/src/examples/primer/RemovePrimer.java
target: includes/example-java-remove-matching-documents-post.txt
transform: 
  - regex: "^        "
    replace: ""
  - regex: "^    "
    replace: ""
truncate:
   start-after: 35
   end-before: 38
---
source: build/java-examples/driver/src/examples/primer/RemovePrimer.java
target: includes/example-java-remove-all-documents.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 46
   end-before: 48
---
source: build/java-examples/driver/src/examples/primer/RemovePrimer.java
target: includes/example-java-remove-all-documents-post.txt
transform: 
  - regex: "^        "
    replace: ""
  - regex: "^    "
    replace: ""
truncate:
   start-after: 51
   end-before: 54
---
source: build/java-examples/driver/src/examples/primer/RemovePrimer.java
target: includes/example-java-drop-collection.java
transform: 
  regex: "^        "
  replace: ""
truncate:
   start-after: 62
   end-before: 64
...