source: /installation.txt
truncate:
  end-before: "Installation Guides"
transform:
  - regex: ':doc:`/release-notes`'
    replace: ':manual:`Release Notes </release-notes>`'
append: |
  .. include:: /includes/toc/dfn-list-spec-installation.rst

  .. include:: /includes/toc/install-on-linux-landing.rst

  .. include:: /includes/toc/installation-osx.rst

  .. include:: /includes/toc/installation-windows.rst

  .. include:: /includes/toc/installation-enterprise-landing.rst
---
source: /includes/toc-spec-installation.yaml
transform:
  - regex: 'file: /administration/install-on-linux'
    replace: 'file: /tutorial/install-on-linux'
  - regex: 'file: /administration/install-enterprise'
    replace: 'file: /tutorial/install-enterprise'
---
source: /includes/toc-installation-enterprise-landing.yaml
transform:
  regex: 'file: /administration/install-enterprise'
  replace: 'file: /tutorial/install-enterprise'
---
source: /includes/toc-install-on-linux-landing.yaml
transform:
  regex: 'file: /administration/install-on-linux'
  replace: 'file: /tutorial/install-on-linux'
---
source: /administration/install-on-linux.txt
target: /tutorial/install-on-linux.rst
transform:
  - regex: "For systems without supported packages.*"
    replace: ""
  - regex: "Installation tutorial."
    replace: ""
---
source: /tutorial/install-mongodb-on-red-hat-centos-or-fedora-linux.txt
transform:
  regex: ":doc:`default ports </reference/default-mongodb-port>`."
  replace: ":manual:`default ports </reference/default-mongodb-port>`."
---
source: /administration/install-enterprise.txt
target: /tutorial/install-enterprise.rst
---
source: /tutorial/install-mongodb-enterprise-on-windows.txt
transform:
  regex: "include:: /tutorial/install-mongodb-on-windows.txt"
  replace: "include:: /tutorial/install-mongodb-on-windows.rst"
---
source: /tutorial/install-mongodb-on-windows.txt
transform:
  - regex: ":doc:`/core/security`"
    replace: ":manual:`Security Concepts </core/security>`"
  - regex: ":doc:`/reference/method"
    replace: ":manual:`MongoDB Shell Methods </reference/methods>`"
  - regex: ":doc:`(.*) <(/reference/configuration-options)>`"
    replace: ":manual:`\\1 <\\2>`"
---
source:   /includes/steps-configure-windows-service-for-mongodb.yaml
transform:
  regex: ":doc:`(.*) <(/reference/configuration-options)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: /includes/steps-create-manually-windows-service-for-mongodb.yaml
transform:
  regex: ":doc:`(.*) <(/reference/configuration-options)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: /includes/steps-run-mongodb-on-windows.yaml
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: /includes/list-mongodb-org-packages.rst
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: /includes/list-mongodb-enterprise-packages.rst
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: /core/data-modeling-introduction.txt
target: /includes/excerpt-data-modeling-introduction.rst
truncate:
  start-after: .. start-primer-excerpt
  end-before: ".. end-primer-excerpt"
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
...