sources:
  - /images/crud-annotated-document-print.png
  - /images/crud-annotated-document.png
  - /images/crud-annotated-document.rst
  - /images/data-model-normalized.rst
  - /images/data-model-normalized.png
  - /images/data-model-normalized-print.png
  - /images/data-model-denormalized.rst
  - /images/data-model-denormalized.png
  - /images/data-model-denormalized-print.png
  - /includes/list-mongodb-enterprise-packages.rst
  - /includes/install-copy-release-linux-i686.rst
  - /includes/install-copy-release-linux-i686.rst
  - /includes/install-copy-release-linux-x86_64.rst
  - /includes/install-copy-release-osx-x86_64.rst
  - /includes/install-curl-release-ent-amzn64.rst
  - /includes/install-curl-release-ent-rhel62.rst
  - /includes/install-curl-release-ent-suse11.rst
  - /includes/install-curl-release-ent-ubuntu1204.rst
  - /includes/install-curl-release-linux-i686.rst
  - /includes/install-curl-release-linux-i686.rst
  - /includes/install-curl-release-linux-x86_64.rst
  - /includes/install-curl-release-osx-x86_64.rst
  - /includes/install-untar-release-linux-i686.rst
  - /includes/install-untar-release-linux-i686.rst
  - /includes/install-untar-release-linux-x86_64.rst
  - /includes/install-untar-release-osx-x86_64.rst
  - /includes/steps-install-mongodb-enterprise-on-windows.yaml
  - /includes/steps-install-mongodb-enterprise-on-suse.yaml
  - /includes/steps-install-mongodb-enterprise-on-amazon.yaml
  - /includes/steps-install-mongodb-enterprise-on-ubuntu.yaml
  - /includes/steps-install-mongodb-enterprise-on-red-hat-or-centos.yaml
  - /includes/steps-install-mongodb-enterprise-on-linux.yaml
  - /includes/steps-install-mongodb-on-linux.yaml
  - /includes/steps-install-mongodb-on-debian.yaml
  - /includes/steps-install-mongodb-on-linux-32.yaml
  - /includes/steps-install-mongodb-on-linux-64.yaml
  - /includes/steps-install-mongodb-on-osx-manually.yaml
  - /includes/steps-install-mongodb-on-osx-with-homebrew.yaml
  - /includes/steps-install-mongodb-on-red-hat-centos-or-fedora-linux.yaml
  - /includes/steps-install-mongodb-on-ubuntu.yaml
  - /includes/steps-install-mongodb-on-windows.yaml
  - /includes/steps-run-mongodb-on-a-linux-distribution.yaml
  - /includes/steps-run-mongodb-on-debian.yaml
  - /includes/steps-run-mongodb-on-linux.yaml
  - /includes/steps-run-mongodb-on-windows.yaml
  - /includes/toc-installation-enterprise.yaml
  - /includes/toc-installation-linux.yaml
  - /includes/toc-installation-osx.yaml
  - /includes/toc-installation-windows.yaml
  - /includes/toc-spec-installation-linux-other.yaml
  - /includes/toc-spec-installation-linux-packages.yaml
  - /tutorial/install-mongodb-on-debian.txt
  - /tutorial/install-mongodb-on-linux.txt
  - /tutorial/install-mongodb-on-os-x.txt
  - /tutorial/install-mongodb-on-ubuntu.txt
  - /tutorial/install-mongodb-enterprise-on-red-hat-or-centos.txt
  - /tutorial/install-mongodb-enterprise-on-ubuntu.txt
  - /tutorial/install-mongodb-enterprise-on-suse.txt
  - /tutorial/install-mongodb-enterprise-on-amazon.txt
  - /tutorial/install-mongodb-enterprise-on-windows.txt
  - /includes/steps-getting-started-insert-prereq.yaml
  - /includes/steps-getting-started-insert.yaml
  - /includes/steps-getting-started-insert-an-array.yaml
  - /includes/steps-getting-started-insert-bulk.yaml
  - /includes/steps-getting-started-query-prereq.yaml
  - /includes/steps-getting-started-query-all.yaml
  - /includes/steps-getting-started-query-equality.yaml
  - /includes/steps-getting-started-query-operators.yaml
  - /includes/steps-getting-started-query-projection.yaml
  - /includes/driver-table.rst
  - /includes/note-id-values-generated.rst
---
source: /core/introduction.txt
target: /introduction.rst
---
source: /administration/install-enterprise.txt
target: /tutorial/install-enterprise.rst
...
