override: false
sources:
  - includes/table/linux-kernel-version-production.rst
  - includes/fact-installation-bind-ip-default-in-config.rst
  - includes/note-minimum-glibc.rst
  - includes/release-base.yaml
  - includes/release-pinning.yaml
  - includes/release-specifications.yaml
  - includes/steps-install-mongodb-on-linux.yaml
  - includes/steps-install-mongodb-on-debian.yaml
  - includes/steps-install-mongodb-on-linux-32.yaml
  - includes/steps-install-mongodb-on-linux-64.yaml
  - includes/steps-install-mongodb-on-osx-manually.yaml
  - includes/steps-install-mongodb-on-osx-with-homebrew.yaml
  - includes/steps-install-mongodb-on-red-hat.yaml
  - includes/steps-install-mongodb-on-ubuntu.yaml
  - includes/steps-install-mongodb-on-amazon.yaml
  - includes/steps-install-mongodb-on-suse.yaml
  - includes/steps-install-mongodb-on-windows.yaml
  - includes/steps-run-mongodb-on-a-linux-distribution.yaml
  - includes/steps-run-mongodb-on-debian.yaml
  - includes/steps-run-mongodb-on-linux.yaml
  - includes/steps-run-mongodb-on-windows.yaml
  - includes/toc-installation-linux.yaml
  - includes/toc-installation-osx.yaml
  - includes/toc-installation-windows.yaml
  - includes/toc-spec-installation-linux-other.yaml
  - includes/toc-spec-installation-linux-packages.yaml
  - tutorial/install-mongodb-on-debian.txt
  - tutorial/install-mongodb-on-linux.txt
  - tutorial/install-mongodb-on-os-x.txt
  - tutorial/install-mongodb-on-ubuntu.txt
  - tutorial/install-mongodb-on-amazon.txt
  - tutorial/install-mongodb-on-suse.txt
  - includes/driver-table.rst
---
source: administration/install-enterprise.txt
target: tutorial/install-enterprise.rst
...
