project: 'mongodb-primer'
master_doc: 'index'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'primer'
  project: 'primer'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'MongoDB-primer'
  repo: 'docs'
  jira: 'DOCS'
sidebars:
  '**':
    - 'pagenav.html'
    - 'formats.html'
...