name: pymongo
url: https://api.mongodb.com/python/current/
path: pymongo.inv
---
name: motor
url: https://motor.readthedocs.io/en/stable/
path: motor.inv
---
name: phplib
url: https://www.mongodb.com/docs/php-library/master/
path: phplib.inv
---
name: clouddocs
url: https://www.mongodb.com/docs/atlas/
path: cloud-docs.inv
---
name: compassdocs
url: https://www.mongodb.com/docs/compass/current/
path: compass-docs.inv
...
