[[integrations]]
name = "snooty-cache-plugin"

# Production context: all deploys from the Production branch
# set in your siteâ€™s Branches settings in the UI will inherit
# these settings.
[build]
base = "source"
publish = "../snooty/public"
command = "cd ../ && . ./build.sh"
