name = "mongosync"
title = "MongoDB Mongosync"

intersphinx = [ "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/php-library/upcoming/objects.inv",
                "https://www.mongodb.com/docs/compass/current/objects.inv",
                "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
                "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/drivers/objects.inv",
                "https://www.mongodb.com/docs/database-tools/objects.inv",
                "https://www.mongodb.com/docs/mongocli/current/objects.inv",
              ]

toc_landing_pages = ["/quickstart",
                     "/reference",
                     "/topologies",
                     "/using-mongosync",
                     "/multiple-mongosyncs",
                     "/release-notes",
                     "/faq",
                     "/reference/collection-level-filtering",
                     "/reference/verification",
                     "/reference/mongosync",
                     "/reference/cutover-process"
                    ]

[constants]
version = "1.19"
version-previous = "1.18"
latest-version="1.19.0"
version-dev = "1.19"
c2c-product-name = "Mongosync"
c2c-full-product-name = "MongoDB Mongosync"
mdb-download-center = "`MongoDB Download Center <https://www.mongodb.com/try/download/mongosync>`__"
c2c-full-beta-program = "Mongosync Beta Program"
c2c-beta-program-short = "``mongosync`` beta"

[substitutions]
c2c-product-name = "Mongosync"
version = "{+version+}"
version-dev = "{+version-dev+}"

[[banners]]
# Warning for non-genuine deployment usage with tool binaries.
targets = [
        "index.txt",
        "about-mongosync.txt",
        "mongosync.txt"
        ]
variant = "warning"
value = """\
        MongoDB ``mongosync`` binaries are not supported or tested for use with non-genuine MongoDB deployments. While the tools may work on these deployments, compatibility is not guaranteed.
        """
