name = "hibernate"
title = "MongoDB Extension for Hibernate"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/drivers/java/sync/current/objects.inv",
                "https://www.mongodb.com/docs/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
extension-long = "MongoDB Extension for Hibernate"
extension-short = "Hibernate ORM extension"
mdb-server = "MongoDB Server"
orm = "Hibernate ORM"
language = "Java"
driver-short = "Java driver"
hibernate-version = "6.6"
extension-version = "1.0.0-alpha0"
user-guide = "https://docs.jboss.org/hibernate/orm/{+hibernate-version+}/userguide/html_single/Hibernate_User_Guide.html"
query-guide = "https://docs.jboss.org/hibernate/orm/{+hibernate-version+}/querylanguage/html_single/Hibernate_Query_Language.html"

[[banners]]
targets = ["index.txt"]
variant = "warning"
value = """
   {+extension-long+} is in Public Preview and intended for evaluation purposes only.
   Public Preview is not recommended for production deployments, because breaking changes
   might be introduced. To learn more about preview feature considerations, see `Preview Features <https://www.mongodb.com/docs/preview-features/>`__.
    """
