eol = true
name = "ruby-driver"
title = "Ruby Driver"
toc_landing_pages = [
    "/connect/connection-options",
    "/crud/query",
    "/indexes",
    "/security/authentication"
]

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-short = "Ruby driver"
driver-long = "MongoDB Ruby Driver"
language = "Ruby"
mdb-server = "MongoDB Server"
mongo-community = "MongoDB Community Edition"
mongo-enterprise = "MongoDB Enterprise Edition"
# always set this to the docs branch (i.e. master, v1.7, v1.8, etc.)
docs-branch = "master"
# always set this to the driver branch (i.e. 1.7 1.8, etc.)
version-number = "2.21"
patch-version-number = "{+version-number+}.3"
version = "v{+version-number+}"
stable-api = "Stable API"
api-root = "https://www.mongodb.com/docs/ruby-driver/current/api/"
bson-version = "5.1.0"
vector-search = "MongoDB Vector Search"
search = "MongoDB Search"
docs-url = "https://www.mongodb.com/docs/ruby-driver/current/"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <{+docs-url+}>`__ to learn how to `upgrade your version of the {+driver-long+} <{+docs-url+}reference/upgrade>`__.\
    """
