name = "spark-connector"
title = "Spark Connector"

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]

toc_landing_pages = [
    "configuration",
    "/batch-mode",
    "/streaming-mode",
    "/streaming-mode/streaming-read",
    "/streaming-mode/streaming-write",
    "/batch-mode/batch-write",
    "/batch-mode/batch-read",
]

[constants]
connector-short = "Spark Connector"
connector-long = "MongoDB {+connector-short+}"
current-version = "10.4.1"
artifact-id-2-13 = "mongo-spark-connector_2.13"
artifact-id-2-12 = "mongo-spark-connector_2.12"
spark-core-version = "3.3.1"
spark-sql-version = "3.3.1"

[substitutions]
copy = "unicode:: U+000A9"
ent-build = "MongoDB Enterprise"
