[build]
    publish = "dist"
    base = "content/landing"

[build.environment]
    REPO_NAME = "docs-landing"
    SECRETS_SCAN_ENABLED = "false"
    MUT_COMMANDS_ENABLED = "false"

[context.production.environment]
    ENV = "dotcomprd"

[context.preprd.environment]
    ENV = "dotcomstg"

[context.deploy-preview.environment]
    ENV = "prd"

[context.branch-deploy.environment]
    ENV = "prd"

[context.preview-server.environment]
    ENV = "prd"

[context.dev.environment]
    ENV = "stg"


[[redirects]] 
from = "/docs/cloud/"
to = "/docs/"
force = true 

[[redirects]] 
from = "/docs/develop-applications/"
to = "/docs/drivers/"
force = true

[[redirects]] 
from = "/docs/launch-manage/"
to = "/docs/"
force = true

[[redirects]] 
from = "/docs/tools/"
to = "/docs/atlas/"

[[redirects]] 
from = "/docs/view-analyze/"
to = "/docs/atlas/"
force = true

[[redirects]] 
from = "/docs/ai-chatbot-data-usage/"
to = "/docs/generative-ai-faq/"
