name = "landing"
title = "MongoDB Documentation"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

[constants]
atlas-cli = "Atlas CLI"
atlas = "MongoDB Atlas"
fts = "MongoDB Search"
avs = "Vector Search"
mdb-shell = "MongoDB Shell"
package-name-org = "docs-landing"
version = 4.0
pgp-version = "{+version+}"
service = "Atlas"
# Drivers & Driver Versions
node-driver = "Node.js driver"
java-driver = "Java driver"
java-driver-version = "5.5.1"
java-rs-driver = "Java Reactive Streams driver"
java-rs-driver-version = "5.5.1"
python-driver = "Python driver"
csharp-driver = ".NET/C# driver"
cpp-driver = "C++ driver"
cpp-driver-version = "4.1.1"
go-driver = "Go driver"
kotlin-sync-driver = "Kotlin Sync driver"
kotlin-coroutine-driver = "Kotlin Coroutine driver"
kotlin-version = "5.5.1"
ruby-driver = "Ruby driver"
rust-driver = "Rust driver"
rust-driver-version = "3.2.4"
php-driver = "PHP driver"

[deprecated_versions]
bi-connector = ["v2.13", "v2.12", "v2.11", "v2.10", "v2.9", "v2.8", "v2.7", "v2.6", "v2.5", "v2.4", "v2.3", "v2.2", "v2.1", "v2.0", "v1.1"]
docs-k8s-operator = ["v1.23", "v1.22", "v1.21", "v1.20", "v1.19", "v1.18", "v1.17", "v1.16", "v1.15", "v1.14", "v1.13", "v1.12", "v1.11", "v1.10", "v1.9", "v1.8", "v1.7", "v1.6", "v1.5", "v1.4", "v1.3", "v1.2", "v1.1", "v1.0", "v0.12", "v0.11", "v0.10", "v0.9", "v0.8"]
docs = ["v5.3", "v5.2", "v5.1", "v4.2", "v4.0", "v3.6", "v3.4", "v3.2", "v3.0", "v2.6", "v2.4", "v2.2"]
mms = ["v5.0", "v4.4", "v4.2", "v4.0", "v3.6", "v3.4", "v2.0", "v1.8", "v1.6", "v1.5", "v1.4", "v1.3", "v1.2", "v1.1"]
mongocli = ["v0.5.0", "v0.2.0", "v0.1.0", "v0.0.4", "v0.0.3", "v1.0.0", "v1.1.0", "v1.2.0", "v1.3.0", "v1.4.0", "v1.5", "v1.6", "v1.7", "v1.8", "v1.9", "v1.10", "v1.11", "v1.12", "v1.13", "v1.14", "v1.15", "v1.16", "v1.17", "v1.18", "v1.19", "v1.20", "v1.21", "v1.22", "v1.23", "v1.24", "v1.25", "v1.26", "v1.27", "v1.28", "v1.29", "v1.30"]
atlas-cli = ["v1.4", "v1.3", "v1.2", "v1.1", "v1.0"]
ruby-driver = ["v2.18", "v2.17", "v2.16", "v2.15", "v2.14", "v2.13", "v2.12", "v2.11", "v2.10", "v2.9", "v2.8", "v2.7", "v2.6", "v2.5", "v2.4", "v2.3", "v2.2", "v2.0", "v1.x"]
mongoid = ["8.0", "7.5", "7.4", "7.3", "7.2", "7.1", "7.0", "6.4", "6.3", "6.2", "6.1", "5.4"]
spark-connector = ["v3.0", "v2.4", "v2.3", "v2.2", "v2.1", "v2.0", "v1.1"]
atlas-open-service-broker = ["master"]
node = ["v5.5", "v5.4", "v5.3", "v5.2", "v5.1", "v5.0", "v4.17", "v4.16", "v4.15", "v4.14", "v4.13", "v4.12", "v4.11", "v4.10", "v4.9", "v4.8", "v4.7", "v4.6", "v4.5", "v4.4", "v4.3", "v4.2", "v4.1", "v4.0", "v3.7", "v3.6"]
visual-studio-extension = ["v1.1", "v1.0"]
kafka-connector = ["v1.9", "v1.8", "v1.7", "v1.6", "v1.5", "v1.4", "v1.3", "v1.2", "v1.1", "v1.0"]
golang = ["v1.10", "v1.9", "v1.8", "v1.7"]
java = ["v4.6", "v4.5", "v4.4", "v4.3"]
php-library = ["v1.15", "v1.13", "v1.12", "v1.11", "v1.10", "v1.9", "v1.8", "v1.7", "v1.6", "v1.5", "v1.4", "v1.3", "v1.2", "v1.1"]

[[composables]]
id = "language"
title = "Language"
default = "nodejs"
dependencies = []
options = [
  {id = "c", title = "C"},
  {id = "csharp", title = "C#"},
  {id = "cpp", title = "C++"},
  {id = "go", title = "Go"},
  {id = "java-async", title = "Java (Async)"},
  {id = "java-sync", title = "Java (Sync)"},
  {id = "kotlin", title = "Kotlin"},
  {id = "kotlin-coroutine", title = "Kotlin (Coroutine)"},
  {id = "nodejs", title = "Node.js"},
  {id = "php", title = "PHP"},
  {id = "python", title = "Python"},
  {id = "ruby", title = "Ruby"},
  {id = "rust", title = "Rust"},
]
