title: "Complete the prerequisites."
stepnum: 0
level: 4
ref: config-prereqs
replacement:
  service: ""
  api-access-url: ""
content: |
  Before you configure the {+mcli+}:

  1. Add your |ipaddr| or |cidr| block to the |api| access list for
     {{service}}.
  
  #. Generate a |svc-api-key| if you don't already have one.
  
  .. include:: /includes/admonitions/note-api-key-roles.rst

  To learn more about generating a |svc-api-key| for
  {{service}}, see {{api-access-url}}.
---
title: "Authenticate to {{service}}."
stepnum: 0
level: 4
ref: auth-login
replacement:
  service: ""
  serviceOption: ""
content: |
  a. Run the :ref:`mongocli-auth-login` command:

     .. code-block:: sh
     
        mongocli auth login {{serviceOption}}
  
     The command opens a browser window and returns a one-time
     activation code. This code expires after 10 minutes.

  #. If you aren't signed in already, sign into your {{service}} account
     in the browser.

  #. Paste your activation code into the browser and click
     :guilabel:`Confirm Authorization`.
---
title: "Create a profile."
stepnum: 0
level: 4
ref: auth-create-profile
content: |
  In your terminal, press :kbd:`Enter` to create a :ref:`profile
  <mcli-profiles>` called ``default`` in the :ref:`mcli-config-file`.
---
title: "Create a profile."
stepnum: 0
level: 4
ref: create-profile
replacement:
  serviceOption: ""
content: |

  .. tabs::

     .. tab:: Default Profile
        :tabid: default-profile

        This command creates a :ref:`profile <mcli-profiles>` called
        ``default`` in the :ref:`mcli-config-file`.

        Run the :ref:`mongocli-config` command:

        .. code-block:: sh
              
          mongocli config {{serviceOption}}
        
     .. tab:: Named Profile
        :tabid: named-profile

        This command creates a :ref:`profile <mcli-profiles>` with a
        custom name in the :ref:`mcli-config-file`. To use this profile
        in a command, you must specify the profile with the
        ``--profile`` flag.

        Run the :ref:`mongocli-config` command:

        .. code-block:: sh
              
          mongocli config {{serviceOption}} --profile <profile-name>

---
title: "Create a profile for the {{service}} project."
stepnum: 0
level: 4
ref: quick-create-profile
replacement:
  service: ""
  serviceOption: ""
content: |
  Run the following :ref:`command <mongocli-config>` to create a
  :ref:`profile <mcli-profiles>` called ``default``.

  .. code-block:: sh 

     mongocli config {{serviceOption}}

---
title: "Enter the :opsmgr:`URL you use to access Ops Manager </reference/config/ui-settings/#URL-to-Access-Ops-Manager>`."
stepnum: 0
level: 4
ref: enter-base-url
content: |

  .. code-block:: sh
     :copyable: false

     ? URL to Access Ops Manager: http://mms.example.com:8080

---
title: "Enter your {{apiKeys}}."
stepnum: 0
level: 4
optional: true
ref: enter-api-key
replacement:
  apiKeys: ""
  service: ""
content: |

  When prompted, enter the ``Public API Key`` and ``Private API Key``
  for your {{service}} deployment.

  .. code-block:: sh
     :copyable: false
               
     ? Public API Key: [? for help] abcdef
     ? Private API Key: [? for help]
     ************************************

---
title: "Choose your default organization."
stepnum: 0
level: 4
ref: auth-enter-orgid-atlas-cm
content: | 

  a. Select your organization.

     - Press the :kbd:`Down Arrow` and :kbd:`Up Arrow`  
       keys to highlight the desired organization, or
     - Type the organization name to filter the available 
       organizations.
    
     .. code-block:: sh
        :copyable: false

        ? Choose a default organization:  [Use arrows to move, type to filter]
        > Org1 (5e39bf1212121e685774c81c)

  #. Press :kbd:`Enter`.

---
title: "Choose your default organization."
stepnum: 0
level: 4
ref: enter-orgid-atlas-cm
content: | 

  If you entered |api| keys, 
  the command displays the name and ID of the 
  organization that your |api| key can access.

  a. Select your organization.

     - Press the :kbd:`Down Arrow` and :kbd:`Up Arrow`  
       keys to highlight the desired organization, or
     - Type the organization name to filter the available 
       organizations.
    
     .. code-block:: sh
        :copyable: false

        ? Choose a default organization:  [Use arrows to move, type to filter]
        > Org1 (5e39bf1212121e685774c81c)

  #. Press :kbd:`Enter`.

  If you didn't enter |api| keys, the command prompts you to enter your
  ``Default Organization ID``.

---
title: "Choose your default organization."
stepnum: 0
level: 4
ref: enter-orgid-om
content: | 

  If you entered |api| keys, 
  the command displays the name and ID of the 
  organizations that your |api| key can access.

  a. Select your organization.

     - Press the :kbd:`Down Arrow` and :kbd:`Up Arrow`  
       keys to highlight the desired organization, or
     - Type the organization name to filter the available 
       organizations.
    
     .. code-block:: sh
        :copyable: false

        ? Choose a default organization:  [Use arrows to move, type to filter]
        > Org1 (5e39bf1212121e685774c81c)

  #. Press :kbd:`Enter`.

  If you didn't enter |api| keys, the command prompts you to enter your
  ``Default Organization ID``.
---
title: "Choose your default project."
stepnum: 0
level: 4
ref: auth-enter-projectid
content: |

  a. Select your project:
      
     - Press the :kbd:`Down Arrow` and :kbd:`Up Arrow`  
       keys to highlight the desired project, or
     - Type the project name to filter the available 
       projects.

     .. code-block:: sh
        :copyable: false

        ? Choose a default project:  [Use arrows to move, type to filter]
          Project1 (5e5ebffd0c04a97009061234)
          Project2 (5cfacee6014b761b07f15678)
        > Project3 (5e39bf4979358e6857741212)
          Project4 (5c815cc7014b768fb67e3434)

  #. Press :kbd:`Enter`.

---
title: "Choose your default project."
stepnum: 0
level: 4
ref: enter-projectid
content: |

  If you entered |api| keys, the command displays the name and ID of
  projects that your |api| key can access.

  a. Select your project:
      
     - Press the :kbd:`Down Arrow` and :kbd:`Up Arrow`  
       keys to highlight the desired project, or
     - Type the project name to filter the available 
       projects.

     .. code-block:: sh
        :copyable: false

        ? Default Project ID:  [Use arrows to move, type to filter]
          Project1 (5e5ebffd0c04a97009061234)
          Project2 (5cfacee6014b761b07f15678)
        > Project3 (5e39bf4979358e6857741212)
          Project4 (5c815cc7014b768fb67e3434)

  #. Press :kbd:`Enter`.

  If you didn't enter |api| keys, the command prompts you to enter your
  ``Default Project ID``.

---
title: "Choose your default output format."
stepnum: 0
level: 4
ref: enter-fileformat
content: |

   a. Press the :kbd:`Down Arrow` and :kbd:`Up Arrow`  
      keys to highlight the desired default output format:

      .. code-block:: sh
        :copyable: false

        ? Default Output Format:  [Use arrows to move, type to filter]
        > plaintext
          json

      .. list-table::
         :header-rows: 1
         :widths: 30 70

         * - Option
           - Description
   
         * - ``plaintext``
           - Human-readable output that includes all fields that 
             {+mcli+} returns.

         * - ``json``
           - JSON output that includes all fields that {+mcli+} returns.
           
   #. Press :kbd:`Enter`.

---
title: "Specify the path to the MongoDB Shell, {+mongosh+}, on your system."
stepnum: 0
level: 4
ref: enter-mongo-shell-path
content: | 

  {+mcli+} uses the specified {+mongosh+} path so that you can 
  access your deployments. The default value is 
  ``/usr/local/bin/mongosh``. Press :kbd:`Enter` to accept the default 
  or: 

  a. Specify the path to {+mongosh+} on your system.

     .. code-block:: sh 
        :copyable: false 

        ? Default MongoDB Shell Path: [? for help] (/usr/local/bin/mongosh)
        
  #. Press :kbd:`Enter`.
---
title: "Add API Keys to your profile."
optional: true
stepnum: 0
level: 4
ref: add-api-keys
replacement:
  service: ""
  api-access-url: ""
content: |

  After successful authentication, you remain logged into the {+mcli+}
  for 12 hours. For an account that needs programmatic access for longer
  than 12 hours, configure API Keys for the profile with the
  :ref:`mongocli-config-set` command:

  .. code-block:: sh

     mongocli config set public_api_key abcdef
     mongocli config set private_api_key a123bc45-ab1c-234d-5678-f91234a5bc6d
     
  .. include:: /includes/admonitions/note-api-key-roles.rst
  
  To learn more about generating an API Key for {{service}}, see
  {{api-access-url}}. 

---
title: "Verify your profile."
stepnum: 0
level: 4
ref: verify-profile
replacement:
  opsMgrUrl: ""
  serviceName: ""
content: |

  View the :ref:`configuration file <mcli-config-file>` or run the 
  :ref:`mongocli-config-describe` command to verify your profile.

  .. tabs::
     :hidden:
    
     .. tab:: Default Profile
        :tabid: default-profile

        .. example::

           The following command returns the settings 
           in the {+default-profile+}:

           .. code-block:: sh
              :copyable: false

              mongocli config describe default
          
           The preceding command returns the following settings. For 
           security purposes, the command redacts |api| keys in the 
           output.

           .. code-block:: sh
              :copyable: false
              
              SETTING           VALUE
              mongosh_path      /usr/local/bin/mongosh
              {{opsMgrUrl}}
              org_id            5f1f39ffc902201990f12345
              private_api_key   redacted
              project_id        7ehf04abc10defb66c7d1234c
              public_api_key    redacted
              service           {{serviceName}}

     .. tab:: Named Profile
        :tabid: named-profile
        
        .. example::

           The following command returns the settings 
           in the profile named ``myMongoDB``:

           .. code-block:: sh
              :copyable: false

              mongocli config describe myMongoDB
          
           The command returns following settings. For security
           purposes, the command redacts |api| keys in the output.

           .. code-block:: sh
              :copyable: false
              
              SETTING           VALUE
              {{opsMgrUrl}}
              org_id            5f1f39ffc902201990f12345
              private_api_key   redacted
              project_id        7ehf04abc10defb66c7d1234c
              public_api_key    redacted
              service           {{serviceName}}

---
title: "Customize the {+mcli+} output using a Go template."
optional: true
stepnum: 0
level: 4
ref: go-template
content: | 
  To learn more about customizing the {+mcli+} output fields and format 
  using a ``Go`` template, see :ref:`go-template-output`.
...
