title: "Create OneLogin database access groups."
level: 4
ref: onelogin-db-groups
content: |

  |service| |ldap| authorization uses |ldap| groups to determine if users
  are authorized to perform database actions.

  Create separate OneLogin groups for each level of access that you want 
  to grant to users. For example, 
  you create one group for read access to one database, another for read 
  and write access, and so on.

  a. Navigate to your OneLogin groups page.
  #. Click :guilabel:`New Group`.
  #. Enter a group name, for example ``db-read``.
  #. Click :guilabel:`Save`.
---
title: "Add OneLogin Users to database access groups."
ref: add-onelogin-users-to-db-groups
level: 4
content: |

  Assign users to groups based on the level of access
  each user requires.

  a. Navigate to your OneLogin Users page.
  #. Click the user you want to add to a group.
  #. Click the :guilabel:`Authentication` tab.
  #. Select the group you want to add the user to.
  #. Click :guilabel:`Save User`.
...
