title: Log into MongoDB Atlas
stepnum: 1
ref: manage-data-stores-ui-step1

---
title: Select :guilabel:`{+df+}` option from the :guilabel:`Services` on the left
stepnum: 2
ref: manage-data-stores-ui-step2

---
title: Click the :guilabel:`Configuration` button besides the name of your {+fdi+}
stepnum: 3
ref: manage-data-stores-ui-step3

---
title: Select your prefered configuration interface method on the top-right corner
stepnum: 4
ref: manage-data-stores-ui-step4
content: |
  - For a visual interface, click :guilabel:`Visual`.
  - For editing directly in the |json| file, click :guilabel:`JSON Editor`.

---
title: "Make your changes to the {+fdi+} storage configuration."
stepnum: 5
ref: manage-data-stores-ui-step5
content: |

  .. tabs::

     .. tab:: Visual Editor
        :tabid: visual

        Manage Data Sources
        ~~~~~~~~~~~~~~~~~~~

        Add an Additional Data Source
        `````````````````````````````

        Corresponds to ``stores`` |json| configuration setting.

        1. Click :guilabel:`Add Data Store Sources`.
        2. Select the data source provider you want to configure:
           - For |aws| |s3|, continue to step 5 of :ref:`deploy-s3`.
           - For |gcp|, continue to step 7 of :ref:`deploy-gcp`.
           - For |azure|, continue to step 7 of :ref:`deploy-azure`.
           - For |service| Cluster, continue to step 7 of :ref:`deploy-atlas-datastore`.
           - For |http| data store, continue to step 7 of :ref:`deploy-atlas-datastore`.
           - For |service| {+Online-Archive+}, continue to step 7 of :ref:`deploy-oa-datastore`.

        Edit Your Data Source Name
        ``````````````````````````
        Corresponds to ``stores.[n].name`` |json| configuration setting.

        1. Select your data store source from the list on the left.
        2. Click the **Edit Store Name** :icon-fa4:`pencil` icon.
        3. Change the current name in the **Data Store Name** field.
        4. Click **Done**.

        Delete a Data Source
        `````````````````````

        1. Select your Data Store source from the list on the left
        2. Click the **Delete this Store** :icon-fa4:`trash-o` icon
        3. Click the **Delete** button.

        

        **Manage Databases**

        Create a New Database
        `````````````````````
        Corresponds to ``databases`` |json| configuration setting.

        1. Click the **Add Database** button on the right-top corner
        2. Fill in the **Database Name** field
        3. Fill in the **Collection Name** field
        4. Click the **Create** button


        Edit a Database name
        `````````````````````
        Corresponds to ``databases.[n].name`` |json| configuration setting.

        1. Select your Database from the list.
        2. Click the **Edit Database Name** :icon-fa4:`pencil` icon.
        3. Update the **Database Name**.
        4. Click the **Done** button.

        Delete a Database
        ``````````````````

        1. Select your Database from the list.
        2. Click **Delete this Database** :icon-fa4:`trash-o` icon.
        3. Click the **Delete** button.

        **Manage Collections**

        Create a new Collection in a Database
        ``````````````````````````````````````

        Corresponds to ``databases.[n].collections`` |json| configuration setting.

        1. Select the Database from where you want to create a Collection
        2. Click the **Add Collection** :icon-fa4:`plus` icon
        3. Fill in the **Collection Name** field
        4. Click the **Create** button

      
        Edit a Collection name
        ```````````````````````

        Corresponds to ``databases.[n].collections.[n].name`` |json| 
        configuration setting.

        1. Select your Collection from the list
        2. Click the **Edit Collection Name** :icon-fa4:`pencil` icon
        3. Change the current name in the **Collection Name** field for your new name
        4. Click the **Create** button
        

        Delete a Collection
        ````````````````````

        1. Select your Collection from the list
        2. Click the **Delete this Collection** :icon-fa4:`trash-o` icon
        3. Click the **Delete** button.



        **Manage Views**

        Create a new :manual:`View </core/views/>` in a Collection
        ```````````````````````````````````````````````````````````

        Corresponds to ``databases.[n].views`` |json| configuration setting.

        1. Select the Collection from where you want to create a View
        2. Click the **Add View** :icon-fa4:`plus` icon
        3. Fill in the **View Name** field
        4. Fill in the **:manual:`Pipeline </core/aggregation-pipeline/>`** field
        5. Click the **Create** button

        

        Edit a View name or Pipeline
        ``````````````````````````````

        Corresponds to ``databases.[n].views.[n].name`` and 
        ``databases.[n].views.[n].pipeline`` |json| configuration settings 
        respectively.

        1. Select your View from your Collection
        2. Click the **Edit View Name** :icon-fa4:`pencil` icon
        3. Change the current name in the **View Name** field for your new name
        4. Change the current pipeline in the **Pipeline** field for your new pipeline
        5. Click the **Save** button

      
        Delete a View
        `````````````````

        1. Select your View from the list
        2. Click the **Delete this View** :icon-fa4:`trash-o` icon
        3. Click the **Delete** button.

     .. tab:: JSON Editor
        :tabid: json

        Edit the |json| configuration file objects to add, create, or remove
        ``stores``, ``databases``, or ``views``
        
        To learn more about the configuration settings of your specific Data Store
        provider, see their Configuration File page:
        
        - :ref:`adf-configuration-file-aws`
        - :ref:`adf-configuration-file-azure`
        - :ref:`adf-configuration-file-gcp`
        - :ref:`adf-configuration-file-atlas`
        - :ref:`adf-configuration-file-http`
        - :ref:`adf-configuration-file-oa`

     .. tab:: mongosh
        :tabid: mongosh

        To learn how to set and manage storage configuration using
        :mongosh:`MongoDB Shell (mongosh) </>`, see the page
        :ref:`adf-cli`.

---
...
