---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: <myopsmanager>
spec:
  replicas: 1
  version: <opsmanagerversion>
  adminCredentials: <adminusercredentials> # Should match metadata.name
                                           # in the Kubernetes secret
                                           # for the admin user

  externalConnectivity:
    type: LoadBalancer

  applicationDatabase:
    topology: MultiCluster
    clusterSpecList:
    - clusterName: cluster1.example.com
      members: 4
    - clusterName: cluster2.example.com
      members: 3
    - clusterName: cluster3.example.com
      members: 2
    version: "8.0.0-ubi8"

...
