fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  links: []
  targets:
    - 'html'
    - 'dirhtml'
    - 'man'
  doc-root:
    - ''
    - '.htaccess'
  branch-root: null
...
