file: /tutorial/upgrade-on-prem-with-rpm-packages
name: "Upgrade with RPM Package"
description: |
  Upgrade |onprem| on Red Hat, Fedora, CentOS, and Amazon AMI Linux.
---
file: /tutorial/upgrade-on-prem-with-deb-packages
name: "Upgrade with DEB Package"
description: |
  Upgrade |onprem| on Debian and Ubuntu systems.
---
file: /tutorial/upgrade-on-prem-from-archive
name: "Upgrade from Archive on Linux"
description: |
  Upgrade |onprem| on other Linux systems, without using package management.
...
