ref: backup-agent-configuration-ssl
edition: onprem
content: |

  .. bsetting:: sslRequireValidMMSBackupServerCertificate

     Specifies if the Backup Agent should validate SSL certificates
     from |mms|.

     .. warning::

        Setting this option to ``false`` disables certificate
        verification and makes connections between Backup Agent and
        |mms| susceptible to *man-in-the-middle* attacks. Setting this
        option to ``false`` is only recommended for testing purposes.

     .. code-block:: ini

        sslRequireValidMMSServerCertificates=true

  .. bsetting:: sslServerClientCertificate

     *Type*: string

     Specifies the path to the file containing the client's private
     key, certificate, and optional intermediate certificates in
     ``PEM`` format. The Backup Agent uses the client certificate
     when connecting to |onprem| over SSL if |onprem| requires client
     certificates, such as when |onprem| runs with :setting:`Client
     Certificate Mode` set to ``Required for Agents Only`` or
     ``Required for All Requests``.

     .. seealso::
        See :setting:`Client Certificate Mode` in
        :doc:`/reference/configuration` for how to specify this
        setting in the |application|.

     .. code-block:: ini

        sslServerClientCertificate=/path/to/client.pem

  .. bsetting:: sslServerClientCertificatePassword

     *Type*: string

     Specifies the password needed to decrypt the private key in
     the ``sslServerClientCertificate`` file. This setting is
     required when the client certificate ``PEM`` file is
     encrypted.

     .. code-block:: ini

        sslServerClientCertificatePassword=password

---
ref: backup-agent-configuration-ssl
edition: cloud
content: ""
...
