ref: note-manage-agent-auth-with-automation-mongodbcr
inherit:
  ref: _note-manage-agent-auth
  file: extracts-admonition-source.yaml
replacement:
  document: ":doc:`/tutorial/enable-mongodbcr-authentication-for-group`"
---
ref: note-manage-agent-auth-with-automation-ldap
inherit:
  ref: _note-manage-agent-auth
  file: extracts-admonition-source.yaml
replacement:
  document: ":doc:`/tutorial/enable-ldap-authentication-for-group`"
---
ref: note-manage-agent-auth-with-automation-kerberos
inherit:
  ref: _note-manage-agent-auth
  file: extracts-admonition-source.yaml
replacement:
  document: ":doc:`/tutorial/enable-kerberos-authentication-for-group`"
---
ref: note-manage-agent-auth-with-automation-x509
inherit:
  ref: _note-manage-agent-auth
  file: extracts-admonition-source.yaml
replacement:
  document: ":doc:`/tutorial/enable-x509-authentication-for-group`"
---
#################################
# LDAP Agent Configuration Intros
#################################
ref: intro-configure-monitoring-agent-ldap
inherit:
  ref: _configure-agent-ldap-intro
  file: extracts-admonition-source.yaml
replacement:
  agent: "Monitoring Agent"
---
ref: intro-configure-backup-agent-ldap
inherit:
  ref: _configure-agent-ldap-intro
  file: extracts-admonition-source.yaml
replacement:
  agent: "Backup Agent"
...