ref: possibleValues-notification-typeName
edition: cloud
content: |
  - ``EMAIL``
  - ``GROUP`` (Project)
  - ``HIPCHAT``
  - ``ORG``
  - ``PAGER_DUTY``
  - ``SLACK``
  - ``SMS``
  - ``TEAM``
  - ``USER``
  - ``WEBHOOK``
  - ``MICROSOFT_TEAMS``
---
ref: possibleValues-notification-typeName
edition: onprem
content: |
  - ``DATADOG``
  - ``EMAIL``
  - ``GROUP`` (Project)
  - ``HIPCHAT``
  - ``ORG``
  - ``PAGER_DUTY``
  - ``SLACK``
  - ``SMS`` (:ref:`Twilio integration <twilio-sms-alert-settings>` must be configured)
  - ``SNMP``
  - ``USER``
  - ``WEBHOOK``
...
