ref: configure-automation-agent-for-ssl-to-mongodb
content: |
  .. note::

     |mms| can manage |tls-ssl| for you if you are using Automation for
     the deployment. With Automation, |mms| prompts you for the
     certificates to use to connect to the deployment when you enable
     |tls-ssl| and then configures the agents appropriately. To learn
     how to configure |tls-ssl|, see
     :doc:`/tutorial/enable-ssl-for-a-deployment`.
---
ref: configure-automation-agent-for-ssl-to-app
edition: onprem
content: |
  To ensure that the Automation Agents use |tls-ssl| when connecting to
  |onprem|, configure |onprem| to use |tls-ssl| for all connections.
  The :doc:`/tutorial/configure-ssl-connection-to-web-interface`
  tutorial describes how to set up |onprem| to run over |tls-ssl|, also
  known as |https|.

  By default, the Automation Agent validates the |mms| |tls-ssl|
  certificate.

  If you are not using a certificate signed by a trusted third party,
  you must configure the Automation Agent to trust |onprem|.

---
ref: configure-automation-agent-for-ssl-to-app
edition: cloud
content: |
  Automation Agents connect to |mms| using |tls-ssl|.
...
