ref: csrs-conversion-admonition
edition: onprem
content: |
   .. admonition:: Feature Availability

      - For deployments running MongoDB 3.2.4 or Later.
      - Requires |mms| version 2.0.3 or greater.
---
ref: csrs-conversion-admonition
edition: cloud
content: |
   .. admonition:: Feature Availability

      - For deployments running MongoDB 3.2.4 or Later.
      - Requires Automation Agent version greater than 2.6.1.x (i.e. greater than 2.6.1).
---
ref: csrs-conversion-cloud-services-version-prereq
edition: onprem
content: |
   |mms| version 2.0.3 or greater.
      |mms| must be version 2.0.3 or greater.
---
ref: csrs-conversion-cloud-services-version-prereq
edition: cloud
content: |
   Automation Agent version greater than 2.6.1.x.
      The Automation Agent version must be greater than 2.6.1.x (i.e. greater than 2.6.1).
...
