ref: automation-agent-configuration-mmsbaseurl
edition: onprem
content: |

  Set this to the URL of your |application|.

  .. code-block:: ini

     mmsBaseUrl=http://example.com:8080

---
ref: automation-agent-configuration-mmsbaseurl
edition: cloud
content: ""
---
ref: automation-agent-configuration-ssl
edition: onprem
content: |

  .. asetting:: sslMMSServerClientCertificate

     *Type*: string

     Specifies the path to the file containing the client's private
     key, certificate, and optional intermediate certificates in
     ``PEM`` format. The Automation Agent uses the client certificate
     when connecting to |onprem| over SSL if |onprem| requires client
     certificates, such as when |onprem| runs with :setting:`Client
     Certificate Mode` set to ``Required for Agents Only`` or
     ``Required for All Requests``.

     .. seealso::
        See :setting:`Client Certificate Mode` in
        :doc:`/reference/configuration` for how to specify this
        setting in the |application|.

     .. code-block:: ini

        sslMMSServerClientCertificate=/path/to/client.pem

  .. asetting:: sslMMSServerClientCertificatePassword

     *Type*: string

     Specifies the password needed to decrypt the private key in
     the ``sslMMSServerClientCertificate`` file. This setting is
     required when the client certificate ``PEM`` file is
     encrypted.

     .. code-block:: ini

        sslMMSServerClientCertificatePassword=password

---
ref: automation-agent-configuration-ssl
edition: cloud
content: ""
...
