ref: _linux-config-expectations
content: |
  The Linux package init scripts do not expect {{option}} to change from the
  defaults. If you use the Linux packages and change {{option}}, you must
  use your own init scripts and disable the built-in scripts.
---
ref: linux-config-expectations-systemlog-path
replacement:
  option: ":setting:`systemLog.path`"
inherit:
  ref: _linux-config-expectations
  file: extracts-linux-config-expectations.yaml
---
ref: linux-config-expectations-processmanagement-fork
replacement:
  option: ":setting:`processManagement.fork`"
inherit:
  ref: _linux-config-expectations
  file: extracts-linux-config-expectations.yaml
---
ref: linux-config-expectations-storage-dbpath
replacement:
  option: ":setting:`storage.dbPath`"
inherit:
  ref: _linux-config-expectations
  file: extracts-linux-config-expectations.yaml
...
