name: ":doc:`Automation Configuration </reference/api/automation-config>`"
file: /reference/api/automation-config
description: |
  Retrieves and update the project's :doc:`automation configuration
  </reference/cluster-configuration>`, which defines the deployment's MongoDB
  processes and agents. Available only on Automated deployments.
---
name: ":doc:`/reference/api/automation-status`"
file: /reference/api/automation-status
description: |
  View the status of an updated :doc:`automation configuration
  </reference/cluster-configuration>`. Available only on Automated
  deployments.
...
