stepnum: 1
level: 4 
inherit:
  file: steps-source-project-nav.yaml
  ref: project-nav-deployment-topology
---
stepnum: 2
level: 4
source:
  file: steps-source-access-control.yaml
  ref: select-and-edit-process
---
stepnum: 3
level: 4
source:
  file: steps-source-access-control.yaml
  ref: open-advanced-options
---
stepnum: 4
level: 4
title: "Set the ``kerberosKeytab`` option."
content: |
  If ``kerberosKeytab`` is not already set:

  a. Click :guilabel:`Add Option`.

     .. list-table::
        :header-rows: 1
        :widths: 30 70

        * - Option
          - Value
          
        * - ``kerberosKeytab``
          - Provide the absolute path to the keytab file.

  b. Click :guilabel:`Add`.

  c. Click :guilabel:`Save`.

ref: set-kerberosKeytab
...
