title: Specify the mechanism.
stepnum: 1
ref: specify-mechanism
action:
  - pre: |
      On systems that configure ``saslauthd`` with the
      ``/etc/sysconfig/saslauthd`` file, such as Red Hat Enterprise Linux,
      Fedora, CentOS, and Amazon Linux AMI, set the mechanism ``MECH`` to
      ``ldap``:
    language: javascript
    code: |
      MECH=ldap
  - pre: |
      On systems that configure ``saslauthd`` with the
      ``/etc/default/saslauthd`` file, set the ``MECHANISMS`` option to
      ``ldap``:
    language: javascript
    code: |
      MECHANISMS="ldap"
---
title: Adjust caching behavior.
stepnum: 2
ref: caching-behavior
pre: |
  On certain Linux distributions, ``saslauthd`` starts with the caching
  of authentication credentials *enabled*. Until restarted or until the
  cache expires, ``saslauthd`` will not contact the LDAP server to
  re-authenticate users in its authentication cache. This allows
  ``saslauthd`` to successfully authenticate users in its cache, even in
  the LDAP server is down or if the cached users' credentials are revoked.
action:
  pre: |
    To set the expiration time (in seconds) for the authentication cache, see
    the `-t option <http://www.linuxcommand.org/man_pages/saslauthd8.html>`_ of
    ``saslauthd``.
---
title: Configure with LDAP Options.
stepnum: 3
ref: ldap-options
pre: |
  If the ``saslauthd.conf`` file does not exist, create it.
  The ``saslauthd.conf`` file usually resides in the ``/etc``
  folder. If specifying a different file path, see the
  `-O option <http://www.linuxcommand.org/man_pages/saslauthd8.html>`_ of
  ``saslauthd``.
action:
  - heading: Configure for Use with ActiveDirectory
    pre: |
      To use with ActiveDirectory, start ``saslauthd`` with the following
      configuration options set in the ``saslauthd.conf`` file:
    language: none
    code: |
      ldap_servers: <ldap uri>
      ldap_use_sasl: yes
      ldap_mech: DIGEST-MD5
      ldap_auth_method: fastbind
    post: |
      For the ``<ldap uri>``, specify the uri of the ldap server. For
      example, ``ldap_servers: ldaps://ad.example.net``.
  - heading: Configure for Use with OpenLDAP
    pre: |
      To connect to an OpenLDAP server, update the ``saslauthd.conf``
      file with the following configuration options:
    language: none
    code: |
      ldap_servers: <ldap uri>
      ldap_search_base: <search base>
      ldap_filter: <filter>
    post: |
      The ``ldap_servers`` specifies the uri of the LDAP server used
      for authentication. In general, for OpenLDAP installed on the
      local machine, you can specify the value ``ldap://localhost:389``
      or if using LDAP over SSL, you can specify the value
      ``ldaps://localhost:636``.

      The ``ldap_search_base`` specifies distinguished name to which
      the search is relative. The search includes the base or objects
      below.

      The ``ldap_filter`` specifies the search filter.

      The values for these configuration options should correspond to the
      values specific for your test. For example, to filter on email, specify
      ``ldap_filter: (mail=%n)`` instead.
  - heading: Example
    pre: |
       A sample ``saslauthd.conf`` file for OpenLDAP includes the following content:
    language: none
    code: |
       ldap_servers: ldaps://ad.example.net
       ldap_search_base: ou=Users,dc=example,dc=com
       ldap_filter: (uid=%u)
    post: |
      To use this sample OpenLDAP configuration, create users with a ``uid``
      attribute (login name) and place under the ``Users`` organizational
      unit (``ou``) under the domain components (``dc``) ``example`` and
      ``com``.

      For more information on ``saslauthd`` configuration, see
      `<http://www.openldap.org/doc/admin24/guide.html#Configuring saslauthd>`_.
---
title: Test the ``saslauthd`` configuration.
stepnum: 4
ref: test-saslauthd-conf
pre: |
  Use ``testsaslauthd`` utility to test the ``saslauthd``
  configuration. For example:
action:
  language: sh
  code: |
    testsaslauthd -u testuser -p testpassword -f /var/run/saslauthd/mux
...