stepnum: 1
source:
  file: steps-configure-mcli.yaml
  ref: quick-create-profile
replacement:
  mdbService: Ops Manager
  serviceOption: "--service ops-manager"
---
stepnum: 2
source:
  file: steps-configure-mcli.yaml
  ref: enter-base-url
---
stepnum: 3
source:
  file: steps-configure-mcli.yaml
  ref: enter-api-key
replacement:
  apiKeys: ":opsmgr:`API keys </tutorial/configure-public-api-access>`"
  service: "|onprem|"
---
stepnum: 4
source:
  file: steps-configure-mcli.yaml
  ref: enter-orgid
---
stepnum: 5
source:
  file: steps-configure-mcli.yaml
  ref: enter-projectid
...
