title: "Copy your PEM certificate to ``/etc/mongodb-mms/``."
stepnum: 1
ref: copy
action:
  pre: |
    Issue the following sequence of commands:
  language: sh
  code: |
    sudo cp -a mms-ssl-unified.crt /etc/mongodb-mms/
    sudo chown mongodb-mms-agent:mongodb-mms-agent /etc/mongodb-mms/mms-ssl-unified.crt
    sudo chmod 600 /etc/mongodb-mms/mms-ssl-unified.crt
---
title: "Edit the following parameter in ``/etc/mongodb-mms/monitoring-agent.config``."
stepnum: 2
ref: edit
action:
  pre: |
    For example:
  language: sh
  code: |
    sslTrustedMMSServerCertificate=/etc/mongodb-mms/mms-ssl-unified.crt
---
title: "Restart the Monitoring Agent for the configuration update to take effect."
stepnum: 3
ref: restart
action:
  pre: |
    For example:
  language: sh
  code: |
    sudo /etc/init.d/mongodb-mms-monitoring-agent restart
...
