---
stepnum: 1
source:
  ref: account-nav-two-factor-auth
  file: steps-source-account-nav.yaml
---
stepnum: 2
source:
  file: steps-source-2fa.yaml
  ref: security-enable-2fa
---
title: "Configure Voice/SMS Authentication."
stepnum: 4
ref: security-2fa-voice-sms-config
content: |
  
  a. Click :guilabel:`Primary Method`
  
  #. Click :guilabel:`Voice/SMS Number`.
  
  #. In the :guilabel:`Enter your phone number` box, enter your
     preferred mobile phone number.
  
  #. Select your preferred method of receiving codes:
    
     - :guilabel:`Text Message (SMS)` *or*
       
     - :guilabel:`Voice Call (US / Canada Only)`
       
  #. Click :guilabel:`Verify`.

  #. Once you receive the verification code, enter that code into the 
     into the :guilabel:`Verify your code` boxes. Each digit is
     entered in its own box.

  |service| automatically verifies the code and saves your settings.
...
    
