---
title: "Create a profile for the |service| project."
stepnum: 0
level: 4
ref: quick-atlas-profile
content: |
  Run the following command to create the ``default`` profile.

  .. code-block:: sh 

     mongocli config

  To learn more about the ``mongocli config`` command, see 
  :ref:`mcli-config-command` or :ref:`mcli-configure`.

---
title: "Create a profile for the {{mmsService}} project."
stepnum: 0
level: 4
ref: quick-create-profile
content: |
  Run the following command to create the ``default`` profile.

  .. code-block:: sh 

     mongocli config --service {{serviceName}} --profile {{profileName}}

  To learn more about the ``mongocli config`` command, see 
  :ref:`mcli-config-command` or :ref:`mcli-configure`.

---
title: "Set your credentials in your profile."
stepnum: 0
level: 4
ref: config-enter-credentials
content: |
  When the command prompts you for the ``Public API Key`` and
  ``Private API Key``, enter the programmatic |api| keys that you
  generated. 

---
title: "Set the ID of the project in your profile."
stepnum: 0
level: 4
ref: config-enter-projectid
content: |
  When the command prompts you, enter your project ID.

  .. include:: /includes/admonitions/note-get-project-id.rst

...
