stepnum: 1
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: click-deployment-processes-topology
---
title: "Restart the process."
stepnum: 2
level: 4
ref: restart-running-process
content: |
  a. Click the ellipsis icon [ :icon:`ellipsis-h`] next to the sharded
     cluster, replica set, or standalone process that you want to
     restart.
  b. Click :guilabel:`Restart`.
---
title: "Click :guilabel:`Confirm`."
stepnum: 3
level: 4
ref: click-confirm
content: |
  After the next publish, |mms| restarts the sharded cluster, replica
  set, or standalone process. Deployments with multiple members
  should remain available as |mms| performs a :term:`rolling restart`.
...
