stepnum: 1
inherit:
  file: steps-create-manually-windows-service-for-mongodb.yaml
  ref: open-command-prompt
---
stepnum: 2
inherit:
  file: steps-create-manually-windows-service-for-mongodb.yaml
  ref: create-directories
---
stepnum: 3
inherit:
  file: steps-create-manually-windows-service-for-mongodb.yaml
  ref: create-configuration-file
---
title: Install the MongoDB service.
stepnum: 4
ref: mongodb-service
pre: |
     .. important::

        Run all of the following commands in :guilabel:`Command Prompt` with
        "Administrative Privileges".
action:
  - pre: |
      Install the MongoDB service by starting :program:`mongod.exe`
      with the ``--install`` option and the ``-config``
      option to specify the previously created configuration file.
    language: powershell
    code: |
      "C:\Program Files\MongoDB\Server\3.6\bin\mongod.exe" --config "C:\Program Files\MongoDB\Server\3.6\mongod.cfg" --install
post: |
  To use an alternate :setting:`dbpath`, specify the path in the
  configuration file (e.g. ``C:\mongodb\mongod.cfg``) or
  on the command line with the :option:`--dbpath <mongod --dbpath>` option.

  If needed, you can install services for multiple instances of
  :program:`mongod.exe` or :program:`mongos.exe`. Install each service
  with a unique :option:`--serviceName <mongod.exe --serviceName>` and
  :option:`--serviceDisplayName <mongod.exe --serviceDisplayName>`. Use
  multiple instances only when sufficient system resources exist and your
  system design requires it.
---
stepnum: 5
inherit:
  file: steps-create-manually-windows-service-for-mongodb.yaml
  ref: start-mongodb-service
---
stepnum: 6
source:
  file: steps-run-mongodb-on-linux.yaml
  ref: verify
pre: |
  Verify that MongoDB has started successfully by checking the 
  log file at ``c:\data\log\mongod.log`` for the following line:
post: |
  If you modified the :setting:`systemLog.path`
  configuration file option, open the log file at that location to 
  examine the process output.

  You may see non-critical warnings in the process
  output. As long as you see the log line shown above, you can safely
  ignore these warnings during your initial evaluation of MongoDB.
---
title: Connect to MongoDB.
stepnum: 7
ref: connect
pre: |
  To connect to MongoDB through the :program:`mongo.exe <mongo>` shell,
  open another :guilabel:`Command Prompt`.
action:
    copyable: true
    language: powershell
    code: |
      "C:\Program Files\MongoDB\Server\3.6\bin\mongo.exe"
post: |
   If you want to develop applications using .NET, see the documentation
   of :ecosystem:`C# and MongoDB </drivers/csharp>` for more information.
---
title: Stop or remove the MongoDB service as needed.
stepnum: 8
ref: stop
action:
  - pre: |
      To stop the MongoDB service use the following command:
    language: powershell
    code: |
      net stop MongoDB
  - pre: |
      To remove the MongoDB service use the following command:
    language: powershell
    code: |
      "C:\Program Files\MongoDB\Server\3.4\bin\mongod.exe" --remove
...
