ref: go-clusters-view-cluster-pl
level: 4
stepnum: 1
source:
  file: steps-connect-to-cluster-master.yaml
  ref: go-clusters-view

---
ref: select-private-endpoint-pl
level: 4
stepnum: 2
title: "Select the :guilabel:`Private Endpoint` connection type."
---
ref: select-private-endpoint-connect-pl
level: 4
stepnum: 3
title: "Select the private endpoint to which you want to connect."
---
ref: create-mongodb-user-cluster-pl
title: "Create a Database User."
level: 4
content: |

  .. important::

     **Skip this step** if |service| indicates in the
     :guilabel:`Setup connection security` step that you have at least
     one database user configured in your project. To manage existing
     database users, see :ref:`mongodb-users`.

  To access the {+database-deployment+}, you need a MongoDB user with 
  access to the desired database or databases on the 
  {+database-deployment+} in your project. If your
  project has no MongoDB users, |service| prompts you to create a new
  user with the :ref:`Atlas Admin <atlas-user-privileges>` role.

  a. Enter the new user's :guilabel:`Username`.
  b. Enter a :guilabel:`Password` for this new user or click
     :guilabel:`Autogenerate Secure Password`.
      
  c. Click :guilabel:`Create Database User` to save the user.

  Use this user to connect to your {+database-deployment+} in the 
  following step.

  Once you have added a database user, click 
  :guilabel:`Choose Your Connection Method`.

---
ref: connect-details-pl
level: 4
stepnum: 5
source:
  file: steps-connect-to-cluster-master.yaml
  ref: connection-details
post: |

  .. tabs::

     .. tab:: {+aws-pl+}
        :tabid: {+aws-pl+}

        Private endpoint-aware connection strings are available in one of the
        following formats:

        - DNS seedlist connection

          .. code-block:: none
             :copyable: false

             mongodb+srv://cluster0-pl-0-auylw.mongodb.net

        - Standard connection string

          .. code-block:: none
             :copyable: false

             mongodb://pl-0-us-east-1-auylw.mongodb.net:1024,pl-0-us-east-1-auylw.mongodb.net:1025,pl-0-us-east-1-auylw.mongodb.net:1026/?ssl=true&authSource=admin&replicaSet=Cluster0-shard-0-shard-0

     .. tab:: {+az-pl+}
        :tabid: {+az-pl+}

        Private endpoint-aware connection strings are available in one
        of the following formats:

        - DNS seedlist connection

          .. code-block:: none
             :copyable: false

             mongodb+srv://cluster0-pl-0.uzgh6.azure.mongodb.net

        - Standard connection string

          .. code-block:: none
             :copyable: false

             mongodb://pl-0-eastus2.uzgh6.azure.mongodb.net:1024,pl-0-eastus2.uzgh6.azure.mongodb.net:1025,pl-0-eastus2.uzgh6.azure.mongodb.net:1026/?ssl=truereplicaSet=atlas-18bndf-shard-0

     .. tab:: {+gcp-psc+}
        :tabid: {+gcp-psc+}

        Private endpoint-aware connection strings are available in one
        of the following formats:

        - DNS seedlist connection

          .. code-block:: none
             :copyable: false

             mongodb+srv://cluster0-pl-0.uzgh6.gcp.mongodb.net

        - Standard connection string

          .. code-block:: none
             :copyable: false

             mongodb://pl-0-us-east1.uzgh6.gcp.mongodb.net:1024,pl-0-us-east1.uzgh6.gcp.mongodb.net:1025,pl-0-us-east1.uzgh6.gcp.mongodb.net:1026/?ssl=truereplicaSet=atlas-18bndf-shard-0


  MongoDB recommends that your clients use the DNS seedlist connection
  string format.
...
