title: Start each member of the config server replica set.
stepnum: 1
level: 4
ref: sharded-cluster-deploy-config-server
pre: |

   When starting *each* :program:`mongod`, specify the
   :program:`mongod` settings either via a configuration file or the
   command line.

action:
  - pre: |
      **Configuration File**

      If using a configuration file, set:

      .. cssclass:: copyable-code

      .. code-block:: yaml

         sharding:
           clusterRole: configsvr
         replication:
           replSetName: <replica set name>
         net:
           bindIp: localhost,<ip address>

      - :setting:`sharding.clusterRole` to ``configsvr``, 

      - :setting:`replication.replSetName` to the desired name of the
        config server replica set,

      - :setting:`net.bindIp` option to the ip or a comma-delimited
        list of ips that remote clients (including the other members of
        the config server replica set as well as other members of the
        sharded cluster) can use to connect to the instance.

        .. include:: /includes/warning-bind-ip-security-considerations.rst

      - Additional settings as appropriate to your deployment, such as
        :setting:`storage.dbPath` and :setting:`net.port`. For more
        information on the configuration file, see :doc:`configuration
        options</reference/configuration-options>`.

      Start the :program:`mongod` with the ``--config`` option
      set to the configuration file path.
    copyable: true
    language: sh
    code: |
      mongod --config <path-to-config-file>
  - pre: |
      **Command Line**
      
      If using the command line options, start the :program:`mongod`
      with the ``--configsvr``, ``--replSet``, ``--bind_ip``,
      and other options as appropriate to your deployment. For example:

      .. include:: /includes/warning-bind-ip-security-considerations.rst

    copyable: true
    language: sh
    code: |
       mongod --configsvr --replSet <replica set name> --dbpath <path> --bind_ip localhost,<ip address of the mongod host>
    post: |
       For more information on startup parameters, see the
       :program:`mongod` reference page.
---
stepnum: 2
level: 4
title: Connect to one of the config servers.
ref: csrs-connect
pre: |
  Connect a :program:`mongo` shell to one of the config server 
  members. 
action:
  copyable: true
  language: sh
  code: |
    mongo --host <hostname> --port <port>
---
stepnum: 3
title: Initiate the replica set.
level: 4
ref: csrs-initiate
pre: |

  From the :program:`mongo` shell, run the :method:`rs.initiate()` method.

  :method:`rs.initiate()` can take an optional :doc:`replica set
  configuration document </reference/replica-configuration>`. In the
  :doc:`replica set configuration document
  </reference/replica-configuration>`, include:

  - The :rsconf:`_id` set to the replica set name specified in either
    the :setting:`replication.replSetName` or the ``--replSet`` option.

  - The :rsconf:`configsvr` field  set to ``true`` for the config server replica set.

  - The :rsconf:`members` array with a document per each member of the replica set.

action:
  - pre: |

      .. important::

         .. include:: /includes/fact-rs-initiate-once-only.rst

    copyable: true
    language: javascript
    code: |
      rs.initiate(
        {
          _id: "<replSetName>",
          configsvr: true,
          members: [
            { _id : 0, host : "cfg1.example.net:27019" },
            { _id : 1, host : "cfg2.example.net:27019" },
            { _id : 2, host : "cfg3.example.net:27019" }
          ]
        }
      )
post: |
   See :doc:`/reference/replica-configuration` for more information on 
   replica set configuration documents.
...
