title: "Create a profile."
stepnum: 0
level: 4
ref: create-profile
content: |

  .. tabs::

     .. tab:: Default Profile
        :tabid: default-profile

        This command creates a profile called ``default`` in the
        :ref:`mcli-config-file`. The {+mcli+} uses this profile by
        default.

        Run the :ref:`mcli-config-command` command:

        .. code-block:: sh
              
          mongocli config {{serviceOption}}
        
     .. tab:: Named Profile
        :tabid: named-profile

        This command creates a profile with a custom name in the
        :ref:`mcli-config-file`. To use this profile, you must specify
        it with the ``--profile`` flag in every command.

        Run the :ref:`mcli-config-command` command:

        .. code-block:: sh
              
          mongocli config {{serviceOption}} --profile <profile-name>
  
---
title: "Enter your |onprem| Base |url|"
stepnum: 0
level: 4
ref: enter-base-url
content: |
  The |onprem| Base |url| is the :opsmgr:`URL you use to access Ops
  Manager </reference/config/ui-settings/#URL-to-Access-Ops-Manager>`.

  .. code-block:: sh

     ? Ops Manager Base URL: http://mms.example.com:8080

---
title: "Enter your {{apiKeys}} and Project ID."
stepnum: 0
level: 4
ref: enter-api-key
content: |

  When prompted, enter the ``Public API Key``, ``Private API Key``, and
  ``Project ID`` for your {{service}} deployment.

  .. code-block:: sh
     :copyable: false
               
     ? Public API Key: abcdef
     ? Private API Key: [? for help] ************************************
     ? Project ID [optional]: 7ehf04abc10defb66c7d1234c

  If you don't save your project ID in your profile, you must specify
  the ``--projectId`` option every time you run a {+mcli+} command.

---
title: "Verify your profile."
stepnum: 0
level: 4
ref: verify-profile
content: |

  View the :ref:`configuration file <mcli-config-file>` to verify your
  profile.

  .. include:: /includes/admonitions/secure-config-file.rst

  .. tabs::
     :hidden:
    
     .. tab:: Default Profile
        :tabid: default-profile

        .. example::

           In this example, the configuration file is stored in the
           ``/.config`` folder of the home directory. View the file
           using the ``cat`` command:

           .. code-block:: sh
              :copyable: false

              cat ~/.config/mongocli.toml
          
           The command returns the contents of the configuration file,
           which contains the {+default-profile+}. The ``default``
           profile has a |svc-api-key| and project ID for an {{service}}
           deployment.

           .. code-block:: sh
              :copyable: false
              
              [default]
              private_api_key = "abcdef"
              public_api_key = "d5199648-abcd-1234-efgh-3ed4396a3096"
              project_id = "7ehf04abc10defb66c7d1234c"
              service = "{{serviceName}}"

     .. tab:: Named Profile
        :tabid: named-profile
        
        .. example::

           In this example, the configuration file is stored in the
           ``/.config`` folder of your home directory. View the file
           using the ``cat`` command:

           .. code-block:: sh
              :copyable: false

              cat ~/.config/mongocli.toml
          
           The command returns the contents of the configuration file, which contains a profile named ``myMongoDB``. The ``myMongoDB`` profile has a |svc-api-key| and project ID for an {{service}} deployment.

           .. code-block:: sh
              :copyable: false
              
              [myMongoDB]
              private_api_key = "abcdef"
              public_api_key = "d5199648-abcd-1234-efgh-3ed4396a3096"
              project_id = "7ehf04abc10defb66c7d1234c"
              service = "{{serviceName}}"

...
