stepnum: 1
level: 4
source:
  file: steps-source-access-control.yaml
  ref: select-deployment-topology
---
stepnum: 2
level: 4
source:
  file: steps-source-access-control.yaml
  ref: select-and-edit-process
---
stepnum: 3
level: 4
source:
  file: steps-source-access-control.yaml
  ref: open-advanced-options
---
stepnum: 4
level: 4
title: "Set the ``kerberosKeytab`` Startup option to point to the keytab file and click :guilabel:`Apply`."
content: |
  If ``kerberosKeytab`` is not already set, use the :guilabel:`Add Option`
  button to add a new startup option, and select ``kerberosKeytab``
  from the drop-down menu. Input the path to the keytab file
  as the value, and then click :guilabel:`Apply`.
ref: set-kerberosKeytab
...