stepnum: 1
source:
  file: steps-view-replica-set-statistics.yaml
  ref: select-the-deployment-page
---
title: "Select the topology view by clicking the first of the two :guilabel:`Processes` icons."
stepnum: 2
edition:
  - cloud
ref: select-topology-view-cloud-only
# this step is borrowed by other steps
---
title: "On the line listing the cluster, replica set, or process, click the ellipses icon and select :guilabel:`Unmanage`."
stepnum: 3
edition:
  - cloud
ref: unmanage-cloud
---
title: "Click :guilabel:`edit mode`, and then click the arrow to the right of the deployment."
stepnum: 2
edition:
  - onprem
ref: click-arrow
---
title: "In the box displaying the deployment configuration, click the gear icon and select :guilabel:`Unmanage`."
stepnum: 3
edition:
  - onprem
ref: unmanage
---
title: "Click :guilabel:`Review & Deploy`."
stepnum: 4
ref: review-deployment
---
title: "Click :guilabel:`Confirm & Deploy`."
stepnum: 5
ref: confirm-deployment
...
