title: "Click on your user name in the upper-right hand corner and select :guilabel:`Personalization`."
stepnum: 1
level: 4
ref: settings
---
title: "Edit personal settings."
stepnum: 2
level: 4
ref: edit
content: |
  Edit the following, as desired. The available fields depend on the
  your :doc:`role </reference/user-roles>`. 

  .. include:: /includes/list-table-personal-settings.rst
...
