title: "Navigate to your Project Integrations."
stepnum: 1
level: 4
ref: project-settings
inherit:
  ref: project-nav-integrations-page
  file: steps-source-project-nav.yaml
---
title: "Link Datadog to your project using your Datadog |api| key."
stepnum: 2
level: 4
ref: link-datadog
content: |
  a. Click :guilabel:`Configure` for the Datadog integration card.

  #. Enter your Datadog |api| key in the input box.

  #. Select your |api| Region (United States or Europe)

  #. Click :guilabel:`Save`.
...
