title: "Select the :guilabel:`Administration` tab and then select :guilabel:`Group Settings`."
stepnum: 1
ref: group-settings-page
---
title: "Modify group settings as desired."
stepnum: 2
ref: modify-group-settings
content: |
  See :ref:`group-settings-page` options for a full description of
  the group settings.

  If you have :ref:`global-owner-role` access, the interface displays a
  *second* :guilabel:`Group Settings` link under the :guilabel:`Admin
  Only` section. For information on these settings, see
  :ref:`admin-only-group-settings`.
...
