stepnum: 1
source:
  file: steps-configure-mcli.yaml
  ref: create-profile
replacement:
  serviceOption: ""
---
stepnum: 2
source:
  file: steps-configure-mcli.yaml
  ref: enter-api-key
replacement:
  apiKeys: ":atlas:`Programmatic API Key </configure-api-access>`"
  service: "|service|"
---
stepnum: 3
source:
  file: steps-configure-mcli.yaml
  ref: enter-orgid
---
stepnum: 4
source:
  file: steps-configure-mcli.yaml
  ref: enter-projectid
---
stepnum: 5
source:
  file: steps-configure-mcli.yaml
  ref: verify-profile
replacement:
  service: "|service|"
  serviceName: "cloud"
  opsMgrUrl: ""
...
