---
stepnum: 1
title: Select an organization to configure as a paying organization.
ref: select-paying-org
content: |
  If it is not already displayed, select your desired organization 
  from the :guilabel:`Organizations` menu in the navigation bar. If you 
  wish to create a new organization through which to pay, 
  :doc:`Create an Organization </tutorial/manage-organizations>` first.

  .. note::
     You can :ref:`rename an organization <rename-organization>` to reach your 
     desired cross-organization configuration.
---
stepnum: 2
title: Click :guilabel:`Billing`.
ref: click-billing
content: |
  Click :guilabel:`Billing` in the top navigation bar or in the left 
  navigation panel.
---
stepnum: 3
title: Click the :guilabel:`Linked Organizations` tab.
ref: click-linked-org-tab
content: |
  .. note::
     The :guilabel:`Linked Organizations` tab only displays if your 
     selected organization is eligible to be a paying organization for 
     cross-organization billing.
---
stepnum: 4
title: Start linking.
ref: click-start-linking
content: |
  If you are configuring a new paying organization, click 
  :guilabel:`Start Linking`.

  If your organization is already a paying organization, click 
  :guilabel:`Link More Organizations`.
---
stepnum: 5
title: Select organizations to link to your paying organization.
ref: link-orgs-to-paying
content: |
  A dialog displays your selected organization under 
  :guilabel:`Paying organization` on the left and a list of 
  organizations you may link to it under 
  :guilabel:`Select organizations to link` on the right.

  Select each organization you wish to link to your 
  paying organization.

  Click :guilabel:`Review and Finish`.
---
stepnum: 6
title: Review and finalize your links.
ref: confirm-link-orgs
content: |
  Confirm that your organizations are linked as intended and click 
  :guilabel:`Finish`.

...
