---
stepnum: 1
source:
  file: steps-source-project-nav.yaml
  ref: project-nav-alerts-page
---
title: "Choose whether to create a new alert setting or clone an existing one."
stepnum: 2
level: 4
ref: add-alert
content: |
  To create a new alert without cloning an existing setting:

  a. Click :guilabel:`Add`.
  #. Select :guilabel:`New Alert`.

  To clone an existing alert setting:

  a. Click the :guilabel:`Alert Settings` tab.
  #. Locate the alert setting you want to clone.
  #. Click :icon:`ellipsis-h` then :guilabel:`Clone` in that alert
     setting's row.

---
title: "Select the condition that triggers the alert."
stepnum: 3
level: 4
ref: alert-if
content: |
  In the :guilabel:`Alert if` section, select the target component and
  the condition. To learn more about alert conditions, see
  :doc:`/reference/alert-types`.
---
title: "Apply the alert only to specific targets."
stepnum: 4
level: 4
optional: true
ref: for
content: |
  If the options in the :guilabel:`For` section are available, you can
  optionally filter the alert to apply only to a subset of the targets.

  The :guilabel:`matches` field can use regular expressions.
---
title: "Select the alert recipients and delivery methods."
stepnum: 5
level: 4
ref: send-to
content: |
  In the :guilabel:`Send to` section, click :guilabel:`Add` and select
  from the options described in the following table.

  To help eliminate false positives, set the time to elapse before the
  condition triggers the alert.

  .. cond:: onprem

     .. include:: /includes/fact-alert-types.rst

  .. cond:: cloud

     .. include:: /includes/list-table-alert-notification-methods-project-only.rst

---
title: "Click :guilabel:`Save`."
stepnum: 6
level: 4
ref: save
...
