title: "Go to your |mms| :guilabel:`Account Settings`."
edition: onprem
stepnum: 1
content: |

  In |mms|, click your username in the top-right corner
  and select :guilabel:`Account`.
ref: security-2fa-access-account
---
title: "Go to your |mms| :guilabel:`Two-Factor Authentication` settings."
ref: security-access-preferences
edition: cloud
stepnum: 1
content: |

  a. In |mms|, click your username in the top-right corner
     and select :guilabel:`Two-Factor Authentication`.

  b. Click :guilabel:`2FA` in the left navigation pane.

---
title: "Enable Two-Factor Authentication."
ref: security-2fa-click-twofa
stepnum: 2
content: |

  Click :guilabel:`Enable 2FA` or click :icon:`pencil-alt`.

  When prompted for verification:

  - If you are setting up |2fa|, enter your password.
  - If you are editing your |2fa| settings, enter a |2fa| code.
  - Click :guilabel:`Verify`.

---
title: "Configure Voice/SMS Authentication."
ref: security-2fa-voice-sms-config
stepnum: 3
content: |
  
  a. Click :guilabel:`Primary Method`
  
  #. Click :guilabel:`Voice/SMS Number`.
  
  #. In the :guilabel:`Enter your phone number` box, enter your
     preferred mobile phone number.
  
  #. Select your preferred method of receiving codes:
    
     - :guilabel:`Text Message (SMS)` *or*
       
     - :guilabel:`Voice Call (US / Canada Only)`
       
  #. Click :guilabel:`Verify`.

  #. Once you receive the verification code, enter that code into the 
     into the :guilabel:`Verify your code` boxes. Each digit is
     entered in its own box.

  |mms| automatically verifies the code and saves your settings.
...
    
