title: "Login to your |idp|."
stepnum: 1
level: 4
ref: login-to-idp

---
title: "Copy |saml| |idp| values."
stepnum: 2
level: 4
ref: copy-saml-values
content: |

  From your |idp|, click on the |onprem| application:

  a. Find the |mms| metadata values.
  #. Copy the following values to a temporary file:

     - :guilabel:`SAML Login URL`
     - :guilabel:`SAML Logout URL`
     - :guilabel:`X.509 Certificate` (for the |idp|)
     - :guilabel:`IdP Entity ID or Issuer`
     - :guilabel:`Signature Algorithm`
---
title: "Navigate to the :guilabel:`User Authentication` tab of the :guilabel:`Ops Manager Config` page."
stepnum: 3
level: 4
ref: ops-manager-config-page
content: |

  Open the |application| and navigate to: :guilabel:`Admin`
  :icon-fa5:`arrow-right` :guilabel:`General` :icon-fa5:`arrow-right`
  :guilabel:`Ops Manager Config` :icon-fa5:`arrow-right`
  :guilabel:`User Authentication`.

---
title: "Set the :guilabel:`User Authentication` option to :guilabel:`SAML`."
stepnum: 4
level: 4
ref: set-userauth-to-saml
content: |

---
title: "Set the required |saml| |idp| setting values in |mms|."
stepnum: 5
level: 4
ref: set-required-saml-settings
content: |

  Type the values from the |idp| for the following |saml| fields:

  .. list-table::
     :header-rows: 1
     :stub-columns: 1
     :widths: 25 10 40 25

     * - Field
       - Necessity
       - Action
       - Default

     * - Identity Provider URI
       - Required
       - Type the |uri| for your |idp| you use to coordinate your
         Single Sign-On.

         This |uri| is the :guilabel:`IdP Entity ID or Issuer` from the
         |saml| |idp|.
       - None

     * - SSO Endpoint URL
       - Required
       - Type the Single-Sign On |url| for your |idp|.

         This |url| is the :guilabel:`SAML Login URL` from your |idp|.

       - None

     * - SLO Endpoint URL
       - Optional
       - Type the |saml| |idp| |url| to be called if you want the
         |mms| user to log out of their |idp| when the |mms| user logs
         out of |mms|.

         This is the :guilabel:`SAML Logout URL` from your |idp|.

       - None

     * - Identity Provider X509 Certificate
       - Required
       - Paste your |idp|'s X.509 Certificate in this field. The |idp|
         provides the certificate in |pem| format. Make sure you
         include the entire certificate content including and starting
         with `-----BEGIN CERTIFICATE-----` and including and ending
         with `-----END CERTIFICATE-----`. |mms| uses this certificate
         to verify itself with the |idp|.

         This is the :guilabel:`X.509 Certificate` from your
         |idp|.
       - None

     * - Identity Provider Signature Algorithm
       - Required
       - Select the algorithm used to encrypt the signature sent to and
         from the |idp|. The accepted values are:

         - ``rsa-sha1``
         - ``dsa-sha1``
         - ``rsa-sha256``
         - ``rsa-sha384``
         - ``rsa-sha512``

         This is the :guilabel:`Signature Algorithm` from your
         |idp|.
       - None

     * - Require Encrypted Assertions
       - Optional
       - Select whether or not your |idp| encrypts the assertions it
         sends to |mms|.
       - ``false``

     * - Global Role Owner Group
       - Required
       - Type the name of the group in the |saml| Group Member
         Attribute that has full privileges over this deployment,
         including full access to all groups and all administrative
         permissions. This group has the :authrole:`Global Owner` role
         for this |mms| instance.

         You added this group to your |idp| settings as part of your
         prerequisites.
       - None

     * - |saml| Attribute For User First Name
       - Required
       - Type the name of the |saml| Attribute that contains User's
         First Name
       - None

     * - |saml| Attribute For User Last Name
       - Required
       - Type the name of the |saml| Attribute that contains User's
         Last Name
       - None

     * - |saml| Attribute For User Email
       - Required
       - Type the name of the |saml| Attribute that contains User's
         Email Address.
       - None

     * - |saml| Group Member Attribute
       - Required
       - Type the name of the |saml| Attribute that contains the list
         of groups |mms| uses to map roles to Projects and
         Organizations.
       - ``groups``

---
title: "Add any needed optional |saml| |idp| settings to |mms|."
stepnum: 6
level: 4
ref: add-optional-saml-settings
content: |

  Type the values from the |idp| for the following |saml| fields:

  .. list-table::
     :header-rows: 1
     :stub-columns: 1
     :widths: 25 10 55 10

     * - Field
       - Necessity
       - Action
       - Default

     * - Path to SP Certificate PEM Key File
       - Optional
       - Type the absolute file path to the |pem|-formatted certificate
         that the Service Provider uses to sign requests. This
         certificate includes the private and public key.

         If this field is left blank:

         - Ops Manager doesn't sign |saml| authentication requests to
           the |idp|.
         - You can't encrypt |saml| assertions.
       - None

     * - Password For SP Certificate PEM Key File
       - Conditional
       - If you encrypted the private key in your SP |pem| file, type
         its password in this field.
       - None

     * - Global Automation Admin Role
       - Optional
       - Type the name of the group whose members have the
         :authrole:`Global Automation Admin` role.
       - None

     * - Global Backup Admin Role
       - Optional
       - Type the name of the group whose members have the
         :authrole:`Global Backup Admin` role.
       - None

     * - Global Monitoring Admin Role
       - Optional
       - Type the name of the group whose members have the
         :authrole:`Global Monitoring Admin` role.
       - None

     * - Global User Admin Role
       - Optional
       - Type the name of the group whose members have the
         :authrole:`Global User Admin` role.
       - None

     * - Global Read Only Role
       - Optional
       - Type the name of the group whose members have the
         :authrole:`Global Read Only` role.
       - None

  Click :guilabel:`Save`.

---
title: "Export your |onprem| Metadata."
stepnum: 7
level: 4
ref: export-metadata
content: |

  After you save the |saml| configuration, a link to
  :guilabel:`Download the Metadata XML File` appears.

  Click this link to download the |saml| SP metadata XML file.

  This metadata file should look similar to this example:

  .. code-block:: XML
     :linenos:

     <?xml version="1.0"?>
     <md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" validUntil="2019-09-13T20:36:00Z" cacheDuration="PT604800S" entityID="http://ec2-3-88-178-252.compute-1.amazonaws.com:8080" ID="ONELOGIN_f95ad815-e8da-4ab3-a799-3c581484cd6a">
       <md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
         <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://ec2-3-88-178-252.compute-1.amazonaws.com:8080/saml/logout"/>
         <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
         <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://ec2-3-88-178-252.compute-1.amazonaws.com:8080/saml/assert" index="1"/>
       </md:SPSSODescriptor>
     </md:EntityDescriptor>

---
title: "Import the |saml| SP Metadata into your |idp|."
stepnum: 8
level: 4
ref: import-sp-saml-values
content: |

  If your |idp| offers the option, import your metadata into the |idp|.
  |mms| serves as the Service Provider (SP) for your |idp|.

  Provide the following values in the metadata |xml| file to |idp|:

  .. list-table::
     :header-rows: 1
     :stub-columns: 1
     :widths: 40 60

     * - Field
       - Common Value

     * - :guilabel:`SP Entity ID or Issuer`
       - ``{+opsmgr-url+}``
     * - :guilabel:`Audience URI`
       - ``{+opsmgr-url+}``
     * - :guilabel:`Assertion Consumer Service (ACS) URL`
       - ``{+opsmgr-url+}/saml/assert``
     * - :guilabel:`Single Logout URL`
       - ``{+opsmgr-url+}/saml/logout``

  If one or more of these values are missing, use the guidelines listed
  in the previous table to set those values.

  Save these values in your |idp|.

---
title: "Test the |saml| integration between |onprem| and your |idp|."
stepnum: 9
level: 4
ref: test-saml
content: |

  a. In a private browser window, go to your |onprem| instance.

     You are redirected to your |idp|.

  b. Authenicate with your |idp|.

     You are then redirected to your |onprem| instance.

...
