stepnum: 1
level: 4
inherit:
  file: steps-source-project-nav.yaml
  ref: project-nav-deployment-topology
---
title: "Click the name of the deployment that contains the process
  that you want to shut down. |mms| opens the deployment
  :guilabel:`Overview`."
level: 4
stepnum: 2
ref: click-overview
---
title: "Click the :guilabel:`Actions` dropdown for the process that you
  want to shut down."
stepnum: 3
level: 4
ref: pause
---
title: "Click :guilabel:`Suspend`."
stepnum: 4
level: 4
ref: confirm-pause
---
title: "Click :guilabel:`Suspend Automation` to confirm."
stepnum: 5
level: 4
ref: suspend-automation
---
title: "At the top of the deployment :guilabel:`Overview`, click
  :guilabel:`Review & Deploy`"
stepnum: 6
level: 4
ref: review-deploy
---
title: "Click :guilabel:`Confirm and Deploy`."
stepnum: 7
level: 4
ref: confirm-deploy
...
