---
level: 4
ref: manage-data-stores-ui-step1
source: 
  file: steps-adf-deploy-source.yaml
  ref: adf-log-in
---
level: 4
ref: manage-data-stores-ui-step2
source: 
  file: steps-adf-deploy-source.yaml
  ref: adf-left-nav
---
title: "Click :guilabel:`Configuration` for the {+fdi+} and choose the 
       configuration method:"
level: 4
ref: manage-data-stores-step3
content: | 

  - For a guided experience, click :guilabel:`Visual Editor`.
  - To edit the raw |json|, click :guilabel:`JSON Editor`.

---
title: "Make necessary changes to the {+fdi+} storage configuration."
level: 4
ref: manage-data-stores-ui-step4
content: | 

  .. tabs:: 

     .. tab:: Visual Editor 
        :tabid: visual 

        To manage data stores in the storage configuration:

        - Click :guilabel:`Add Data Store` to add a new data store. To 
          add an: 

          - |s3| data store, complete step 5 in :ref:`deploy-s3`. 
          - |service| data store, follow steps 5 to 7 in 
            :ref:`deploy-atlas-datastore`.
          - |http| data store, follow steps 5 to 7 in 
            :ref:`deploy-atlas-datastore`.
          - {+adl+} dataset, follow steps 5 and 6 in 
            :ref:`deploy-adl-datastore`.

          Corresponds to ``stores`` |json| configuration 
          setting. 

        - Click the :icon-fa4:`pencil` for the store to edit the 
          data store name. 
       
          Corresponds to ``stores.[n].name`` |json| configuration 
          setting.

        - Click :icon-fa4:`trash-o` associated with the data store to 
          remove the data store.

        To manage databases in the storage configuration:

        - Click :guilabel:`Create Database` to add databases and  
          collections.

          Corresponds to ``databases`` |json| configuration setting.

        - Click the :icon-fa4:`pencil` for the database to edit the 
          database name. 
       
          Corresponds to ``databases.[n].name`` |json| configuration 
          setting.

        - Click :icon-fa4:`trash-o` associated with the database to 
          remove the database.

        To manage collections and views in the storage configuration: 

        - Click the :icon-fa4:`pencil` for the: 
        
          - Collection to edit the collection name. 
       
            Corresponds to ``databases.[n].collections.name`` |json| 
            configuration setting.

          - View to edit the view name and pipeline.

            Corresponds to ``databases.[n].views.[n].name`` and 
            ``databases.[n].views.[n].pipeline`` |json| configuration 
            settings respectively.

        - Click :icon-fa4:`plus` associated with the: 
        
          - Database to add collections to the database.

            Corresponds to ``databases.[n].collections`` |json| 
            configuration setting.

          - Collection to add :manual:`views </core/views/>` on the 
            collection. To create a view, you must specify: 
       
            - The name of the view.

            - The :manual:`pipeline </core/aggregation-pipeline/#std-label-aggregation-pipeline>` 
              to apply to the view.

            Corresponds to ``databases.[n].views`` |json| configuration 
            setting.

        - Click :icon-fa4:`trash-o` associated with the collection or 
          view to remove the collection or view.

     .. tab:: JSON Editor 
        :tabid: json 

        Edit the |json| configuration settings shown in the UI for 
        ``stores`` and ``databases``. To learn more about the 
        configuration settings, see :ref:`config-adf`.

---
ref: manage-data-stores-ui-step5
stepnum: 7
inherit:
  file: steps-adf-deploy-source.yaml
  ref: save-configuration
...
