title: "Download snapshots."
optional: true
stepnum: 1
level: 4
ref: download-snapshots-mp
content: |

  If you have backup enabled and want to retain snapshots:

  a. Download any snapshots that you want to keep:

     - :doc:`Download the snapshots for a replica set 
       </tutorial/restore-replica-set>`.
     - :doc:`Download the snapshots for a sharded cluster 
       </tutorial/restore-sharded-cluster>`.

  #. :ref:`Stop all backups <stop-backup>`.

     .. important::
     
        All existing snapshots remain available for download until they 
        expire, but |onprem| captures no new snapshots.

---
title: "Prepare backup components."
optional: true
stepnum: 2
level: 4
ref: prepare-backup-mp
content: |

  If you want backup enabled for your MongoDB deployment in the new 
  project, :doc:`prepare your backup components
  </core/backup-preparations>`.

---
title: "Prepare the old project."
stepnum: 3
level: 4
ref: prepare-old-project-mp
content: |

  a. :doc:`Deactivate the backup and monitoring {+mdbagent+} functions 
     </tutorial/mongodb-agent-functions/>` in the old project.

  #. :doc:`Unmanage the MongoDB deployment in the old project, but continue to monitor it </tutorial/unmanage-deployment>`.

---
title: "Prepare the new project."
stepnum: 4
level: 4
ref: prepare-new-project-mp
content: |

  a. :ref:`Create a new project <create-project>` to use as the 
     destination project.
  
  #. Click :guilabel:`Settings` in the left navigation.

  #. Note the :guilabel:`Project ID` value on the 
     :guilabel:`Project Settings` tab.

  #. :doc:`Create a new Agent API key </tutorial/manage-agent-api-key>`.

---
title: "Prepare the {+mdbagent+}."
stepnum: 5
level: 4
ref: prepare-agent-mp
content: |

  .. note::

     If you have multiple deployments in your project and a 
     {+mdbagent+} installed only on the hosts that you plan to move, 
     you must install new agents on servers that you will not move to 
     the new project.

  a. :ref:`Stop the {+mdbagent+} <stop-mdb-agent>`.

  #. Edit the :doc:`{+mdbagent+} configuration file 
     </reference/mongodb-agent-settings/>` to update the 
     :setting:`mmsGroupId` and :setting:`mmsApiKey` settings with the 
     values from for the new project.

  #. (Optional) If the new project is a new Ops Manager, update the 
     :setting:`mmsBaseUrl` setting.

  #. :ref:`Start the {+mdbagent+} <start-mdb-agent>`.

     The MongoDB deployment servers should appear on the 
     :guilabel:`Servers` and :guilabel:`Agents` tabs.

---
title: "Migrate the MongoDB deployment."
stepnum: 6
level: 4
ref: migrate-deployment-mp
content: |

  a. :doc:`Activate the backup and monitoring {+mdbagent+} functions 
     </tutorial/mongodb-agent-functions/>` in the new project.

  #. :ref:`Add the MongoDB deployment to your new project 
     <add-existing-mongodb-hosts>`.

  #. (Optional) :doc:`Start backups 
     </tutorial/stop-restart-terminate-backup>`.

---
title: "Remove the old project."
optional: true
stepnum: 7
level: 4
ref: remove-project-mp
content: |

  .. warning::

     This step permanetly deletes your old project and its related 
     artifacts.

  a. :ref:`Terminate all backups <terminate-backup>` in the old project.

     .. important::

        If you don't terminate all backups in the old project, all 
        existing snapshots remain available for download until they 
        expire and occupy disk space. You can't remove the MongoDB 
        deployment and delete the old project unless your terminate all 
        backups.

  #. :doc:`Completely remove the MongoDB deployment 
     </tutorial/unmanage-deployment>` from the old project.

  #. :ref:`Delete the old project <delete-project>`.

...
