title: "Click :guilabel:`Sign in with PagerDuty`."
stepnum: 1
level: 4
ref: go-to-pagerduty
content: | 
  You are redirected to PagerDuty.
---
title: "Log into PagerDuty using your PagerDuty credentials."
stepnum: 2
level: 4
ref: pagerduty-log-in
---
title: "Select PagerDuty services to integrate with MongoDB."
stepnum: 3
level: 4
ref: pagerduty-select-services
content: |
  From the dropdown menu, select the PagerDuty service that you 
  want to integrate with MongoDB. 

  .. note::
     
     You can select multiple services, but you will be prompted 
     to pick a single default in the next step.
  
  PagerDuty redirects you back to your |service| project and displays a 
  :guilabel:`PagerDuty Configuration` modal. 
---
title: "Select a default service to integrate with MongoDB."
stepnum: 3
level: 4
ref: pagerduty-select-service
content: |
  From the :guilabel:`PagerDuty Configuration` modal, select one 
  default service to integrate. |service| automatically 
  provides an integration key.
---
title: "(Optional) Click :guilabel:`Test Integration` to confirm that 
  your configuration is valid."
stepnum: 4
level: 4
ref: test-pagerduty-key
content: |
  When you click :guilabel:`Test Integration`, the PagerDuty 
  configuration modal displays a banner with a success or 
  failure message.
---
title: "Click :guilabel:`Save` to integrate PagerDuty 
  with |service|."
stepnum: 5
level: 4
ref: activate-pagerduty-key
content: |
...
