stepnum: 1
level: 4
inherit:
  file: steps-source-project-nav.yaml
  ref: project-nav-deployment-topology
---
title: "On the line listing the cluster, replica set, or process, click the ellipsis icon and select :guilabel:`Connect to this instance`."
stepnum: 2
level: 4
ref: connect-to-instance-info
content: |
  |mms| provides a |mongo| shell command that you can use 
  to connect to the MongoDB process.
...
