title: "Configure the proxy settings."
stepnum: 1
ref: configure-proxy
content: |

  a. Click the :guilabel:`Admin` link at the top left.
  #. Click :guilabel:`Ops Manager Config`.
  #. Click :guilabel:`Miscellaneous`.
  #. Set the options for the proxy under the
     :guilabel:`HTTP/HTTPS Proxy` section:

     .. list-table::
        :header-rows: 1
        :widths: 20 80

        * - Field
          - Action

        * - :setting:`Proxy Host`
          - Specify the hostname of the proxy server.

        * - :setting:`Proxy Port`
          - Specify the port of the proxy server.

        * - :setting:`Non Proxy Hosts`
          - Specify a pipe-separated (``|``) list of internal hosts
            to bypass the outgoing proxy you configured.

        * - :setting:`Proxy Username`
          - If the proxy server requires authentication, specify the username with which to authenticate.

        * - :setting:`Proxy Password`
          - If the proxy server requires authentication, specify the password with which to authenticate.

  .. caution::

     |onprem| doesn't support :abbr:`NTLM (Windows NT LAN Manager)`
     protocol authentication for proxies.

---
title: "Restart |onprem|."
stepnum: 2
ref: stop-ops-manager
pre: |
  Use the command appropriate to your platform.
content: |

  .. list-table::
     :widths: 30 70
     :header-rows: 1

     * - Platform

       - Restart Service Command

     * - RHEL, CentOS, Amazon Linux and Ubuntu

       -
         .. code-block:: sh

            sudo service mongodb-mms restart

     * - Other Linux distributions

       -
         .. code-block:: sh

            <install_dir>/bin/mongodb-mms restart



...
