stepnum: 1
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: click-deployment
---
title: "On the line listing the deployment item, click :guilabel:`Modify`."
stepnum: 2
level: 4
ref: modify
---
title: "Modify Cluster-Wide Settings."
stepnum: 3
level: 4
ref: make-changes
content: |

  The :guilabel:`Replica Set Configuration` section contains the
  following cluster-wide configuration settings.

  .. list-table::
     :header-rows: 1
     :widths: 25 75

     * - Setting
       - Description

     * .. include:: /includes/extracts/deploy-replica-set-auth-schema-version.rst

     * .. include:: /includes/extracts/deploy-replica-set-feature-compatibility-version.rst

     * .. include:: /includes/extracts/deploy-replica-set-settings.rst

     * .. include:: /includes/extracts/deploy-process-name.rst

     * .. include:: /includes/extracts/deploy-version.rst

     * .. include:: /includes/extracts/deploy-log-file.rst

---
title: "Configure Each Replica Set Member."
stepnum: 4
level: 4
ref: modify-member
content: |

  |mms| lists each replica set member under the
  :guilabel:`MongoD Settings` heading of the
  :guilabel:`Member Configuration` section. Each replica set member
  has the following configurable options:

  .. list-table::
     :header-rows: 1
     :widths: 25 75
 
     * - Setting
       - Description
 
     * .. include:: /includes/extracts/deploy-member-configuration-member.rst
 
     * .. include:: /includes/extracts/deploy-member-configuration-hostname.rst
 
     * .. include:: /includes/extracts/deploy-member-configuration-port.rst
 
     * .. include:: /includes/extracts/deploy-member-configuration-votes.rst
 
     * .. include:: /includes/extracts/deploy-member-configuration-priority.rst
 
     * .. include:: /includes/extracts/deploy-member-configuration-delay.rst
 
     * .. include:: /includes/extracts/deploy-member-configuration-build-indexes.rst
 
     * .. include:: /includes/extracts/deploy-member-configuration-tags.rst
 
     * .. include:: /includes/extracts/deploy-member-configuration-add-mongod.rst

---
title: "Configure your Replication Settings."
stepnum: 5
level: 4
ref: modify-replication
content: |

  The :guilabel:`Replication Settings` section contains the following
  configuration options for the replica set:

  .. list-table::
     :header-rows: 1
     :widths: 25 75

     * - Setting
       - Description

     * .. include:: /includes/extracts/deploy-member-replication-protocol-version.rst

     * .. include:: /includes/extracts/deploy-member-replication-chaining-allowed.rst

     * .. include:: /includes/extracts/deploy-member-replication-write-concern-majority-journal-default.rst

     * .. include:: /includes/extracts/deploy-member-replication-heartbeat-timeouts.rst

     * .. include:: /includes/extracts/deploy-member-replication-election-timeout.rst

     * .. include:: /includes/extracts/deploy-member-replication-catch-up-timeout.rst

     * .. include:: /includes/extracts/deploy-member-replication-catch-up-takeover-delay.rst

---
title: "Modify Advanced Configuration Options."
stepnum: 6
level: 4
ref: modify-advanced
source:
  file: steps-deploy-replica-set.yaml
  ref: set-advanced
---
title: "Click :guilabel:`Save`."
stepnum: 7
level: 4
ref: modify-save
content: |

  |mms| redirects you to the deployment page, where you must review
  your changes before deploying the updated configuration.
---
stepnum: 8
level: 4
ref: modify-review
source:
  file: steps-source-deployment-page.yaml
  ref: review-deployment
---
stepnum: 9
level: 4
ref: modify-deploy
source:
  file: steps-source-deployment-page.yaml
  ref: confirm-deployment
...
