---
ref: view-all-database-deployments
stepnum: 1
level: 4
title: "Click :guilabel:`Databases` at the top of the |service| console."
content: |

  The :guilabel:`{+Database-Deployments+}` page displays.
---
ref: search-and-filter-clusters
stepnum: 4
level: 4
title: "Use the search box and dropdown menus to filter the list of {+database-deployments+}."
content: |

  The :guilabel:`{+Database-Deployments+}` page groups {+clusters+} and
  {+serverless-instances+} under their |service| project.

  To filter the returned list of {+database-deployments+}:

  - Use the search box. Enter the
    :ref:`organization name <organizations>`,
    :ref:`project name <projects>`, or {+cluster+}/{+serverless-instance+} name
    to limit returned {+database-deployments+} to specific organizations,
    projects, or {+clusters+}/{+serverless-instances+}.

  - Use the dropdown menus to limit the returned list using one or more
    of the following filters:

    .. include:: /includes/list-tables/all-clusters-filter.rst

  To display clusters that have not contacted |service| in the last 6
  months, click :guilabel:`Show Inactive Clusters`.
...
