title: Create Data Directories.
stepnum: 1
level: 4
ref: deploy-cluster-mirrored-create-data-dir
pre: |
  Create data directories for each of the three config server instances. By 
  default, a config server stores its data files in the 
  /data/configdb directory. You can choose a different location. 
  To create a data directory, issue a command similar to the following:
action:
  language: sh
  code: |
    mkdir /data/configdb
---
title: Start up the Config Server :binary:`~bin.mongod`.
stepnum: 2
level: 4
ref: deploy-cluster-mirrored-start-config
action:
  - pre: |
      **Configuration File**
  
      If using a configuration file, set the :setting:`security.keyFile` option
      to the keyfile's path and the :setting:`sharding.clusterRole` 
      option to ``configsvr``. Start the component, as in the following
      example:
    language: yaml
    code: |
      security:
        keyFile: <path-to-keyfile>
      sharding:
        clusterRole: configsvr
    post: |
       Include any other settings as appropriate for your deployment.
       See :doc:`/reference/configuration-options` for information on 
       using a configuration file.
  - pre: |
      **Command Line**
  
      If using the command line option, when starting the component, specify 
      the ``--keyFile`` and ``--configsvr`` parameters, as in the
      following example:
    language: sh
    code: |
       mongod --keyFile <path-to-keyfile> --configsvr --dbpath <path to data>
    post: |
       Include any other options as appropriate for your deployment.
post: |
  Repeat this step until all three config servers are online.
...
