stepnum: 1
level: 4
ref: login
title: "Log into |service|."   
---
stepnum: 2
level: 4
ref: click-security-advanced
inherit:
  ref: project-nav-advanced-page
  file: steps-source-project-nav.yaml
---
stepnum: 3
title: "Toggle the button next to :guilabel:`LDAP Authentication` to :guilabel:`On`."
level: 4
ref: toggle-on
content: |

  .. note::

     You might incur additional costs when you enable this feature. 
     See :ref:`advanced-security`.

---
stepnum: 4
title: "Enter the server details and bind credentials for your LDAP
       server in the :guilabel:`Configure Your LDAP Server` panel."
level: 4
ref: configure-ldap-server
---
stepnum: 5
title: "Enter a certificate issued from a Certificate Authority (CA) for your LDAP server in the :guilabel:`CA Root Certificate` field."
optional: true
level: 4
ref: copy-ssl-certificate
content: |

   You may provide a self-signed certificate.
---
stepnum: 6
title: "Click :guilabel:`Verify and Save`."
level: 4
ref: verify-and-save
content: |
   
   Wait for |service| to deploy your changes. |service| verifies that
   your clusters can connect to, authenticate with, and query your LDAP
   server using the configuration details that you provide.
...
