stepnum: 1
level: 4
inherit: 
  file: steps-source-project-nav.yaml
  ref: project-nav-deployment-page
---
title: "On the line listing the deployment item, click :guilabel:`Modify`."
stepnum: 2
level: 4
ref: modify
---
title: "Modify the Standalone Settings."
stepnum: 3
level: 4
ref: make-changes
content: |

  The :guilabel:`Standalone Settings` section contains the following
  configuration settings:

  .. list-table::
     :header-rows: 1
     :widths: 25 75

     * - Setting
       - Description

     * - :guilabel:`Hostname`
       - Hostname to which |mms| deploys the |mongod|. This hostname
         can be a hostname, an |fqdn|, an |ipv4| address, or an |ipv6|
         address. You can only deploy to hosts under |mms| automation.
         For complete documentation on adding servers to |mms|
         automation, see :doc:`/tutorial/add-servers-automation/`.

     * .. include:: /includes/extracts/deploy-member-configuration-port.rst

     * .. include:: /includes/extracts/deploy-version.rst

     * .. include:: /includes/extracts/deploy-replica-set-auth-schema-version.rst

     * .. include:: /includes/extracts/deploy-replica-set-feature-compatibility-version.rst

     * .. include:: /includes/extracts/deploy-log-file.rst

---
title: "Modify Advanced Configuration Options."
stepnum: 4
level: 4
ref: set-advanced
content: |
  The :guilabel:`Advanced Configuration Options` section allows you to
  set MongoDB :doc:`runtime options
  </reference/deployment-advanced-options>` for each MongoDB process
  in your deployment.

  To add an option:

  a. Click :guilabel:`Add Option`.

  #. Click :guilabel:`Select a Startup Option` and select the
     :doc:`configuration option </reference/deployment-advanced-options>`.

  #. |mms| displays a context-sensitive input for configuring an
     acceptable value for the selected option.

  #. Click :guilabel:`Add` to add the selected option and its
     corresponding value to the process.

  For descriptions of the available :guilabel:`Advanced
  Configuration Options`, see
  :doc:`/reference/deployment-advanced-options`.
---
title: "Click :guilabel:`Save`."
stepnum: 5
level: 4
ref: modify-save
content: |

  |mms| redirects you to the :guilabel:`Deployment` page, where you must
  review your changes before deploying the updated configuration.
---
stepnum: 6
level: 4
ref: modify-review
source:
  file: steps-source-deployment-page.yaml
  ref: review-deployment
---
stepnum: 7
level: 4
ref: modify-deploy
source:
  file: steps-source-deployment-page.yaml
  ref: confirm-deployment
...
