ref: click-adf-connect-button
level: 4
source: 
  file: steps-adf-connect-shell.yaml
  ref: getting-started-connect-dialog
---
ref: nav-to-dl
level: 4
title: "Choose the type of connection that you wish to configure."
content: |
  You can choose one of the following options: 

  - :guilabel:`Standard connection` - to configure this type of 
    connection, you must do the following: 

    1. :ref:`add-ip-address`
    #. :ref:`create-mdb-user`

  - :guilabel:`Private endpoint` - to configure this type of 
    connection, you must do the following: 

    #. :ref:`config-private-endpoint`
    #. :ref:`create-mdb-user`

  .. note:: 

     If you specify ``0.0.0.0`` in your project :atlas:`IP access 
     list </security/ip-access-list/>`, |service| will accept all 
     connections including those over PrivateLink.

...
