stepnum: 1
ref: click-alerts
inherit:
  file: steps-source-org-nav.yaml
  ref: org-nav-alerts-page
--- 
title: "Choose whether to create a new alert setting or clone an existing one."
stepnum: 2
level: 4
ref: add-alert
content: |
  To create a new alert:

  a. Click :guilabel:`Add Alert`.

  To clone an existing alert setting:

  a. Click the :guilabel:`Alert Settings` tab.
  #. Locate the alert setting you want to clone.
  #. Click :icon:`ellipsis-h` then :guilabel:`Clone` in that alert
     setting's row.

---
title: "Choose the :guilabel:`Target`."
stepnum: 3
level: 4
ref: choose-target
content: |

  Click :guilabel:`User` or :guilabel:`Billing` under
  :guilabel:`Select a Target`.

---
title: "Choose the :guilabel:`Condition`."
stepnum: 4
level: 4
ref: choose-condition
content: |

  Under :guilabel:`Select a Condition`:

  - If you chose :guilabel:`User`, select:

    - :alert:`User(s) in the organization do not have 2FA enabled <Users do not have two-factor authentication enabled>`
    - :alert:`User has joined the organization <User joined the organization>`
    - :alert:`User has left the organization <User left the organization>`
    - :alert:`User's role has been changed <User had their role changed>`

  - If you chose :guilabel:`Billing`:

    a. Select from the following options:

       - :alert:`Credit card is about to expire`
       - :alert:`Amount billed yesterday is above <Amount billed ($) yesterday is above the threshold>`
       - :alert:`Current bill for any single project is above <Current bill ($) for any single project is above the threshold>`
       - :alert:`Current bill for the organization is above <Current bill ($) for the organization is above the threshold>`

    b. If :guilabel:`above $` appears next to the option you selected,
       specify the amount in :abbr:`USD (United States Dollars)`
       where |service| should trigger the alert if the selected
       condition exceeds that value.

---
title: "Select the :guilabel:`Notification Method`."
stepnum: 5
level: 4
ref: notify
content: |

  Under the :guilabel:`Add Notification Method` heading, click the
  button for the particular notification method you want to use.

  .. include:: /includes/list-table-alert-notification-methods-org.rst

---
title: "Click :guilabel:`Save`."
stepnum: 6
level: 4
ref: save
...
