stepnum: 1
level: 4
inherit: 
  file: steps-source-project-nav.yaml
  ref: project-nav-deployment-page
---
title: "On the line listing the deployment item, click :guilabel:`Modify`."
stepnum: 2
level: 4
ref: modify
---
title: "Configure Cluster-Wide Settings."
stepnum: 3
level: 4
ref: configure-cluster
content: |

  The :guilabel:`Cluster Configuration` section contains the following
  cluster-wide configuration settings.

  .. list-table::
     :header-rows: 1
     :widths: 25 75

     * - Setting
       - Description

     * .. include:: /includes/extracts/deploy-sharded-shard-name.rst

     * .. include:: /includes/extracts/deploy-replica-set-auth-schema-version.rst

     * .. include:: /includes/extracts/deploy-replica-set-feature-compatibility-version.rst

     * .. include:: /includes/extracts/deploy-sharded-process-name.rst

     * .. include:: /includes/extracts/deploy-sharded-version.rst

     * .. include:: /includes/extracts/deploy-sharded-log-file.rst


---
title: "Configure Each Shard in Your Cluster."
stepnum: 4
level: 4
ref: configure-cluster-members-shards
content: |

  From the :guilabel:`Member Configuration` section, click
  :guilabel:`Shard Settings` to open the :term:`shard` configuration
  options. |mms| lists each shard in the cluster and the |mongod|
  processes associated to that shard. Each shard process has the the
  following options. You cannot modify options that are greyed out:

  .. list-table::
     :header-rows: 1
     :widths: 25 75

     * - Setting
       - Description

     * .. include:: /includes/extracts/deploy-member-configuration-member.rst

     * .. include:: /includes/extracts/deploy-member-configuration-hostname.rst

     * .. include:: /includes/extracts/deploy-member-configuration-port.rst

     * .. include:: /includes/extracts/deploy-member-configuration-votes.rst

     * .. include:: /includes/extracts/deploy-member-configuration-priority.rst

     * .. include:: /includes/extracts/deploy-member-configuration-delay.rst

     * .. include:: /includes/extracts/deploy-member-configuration-build-indexes.rst

     * .. include:: /includes/extracts/deploy-member-configuration-tags.rst

     * .. include:: /includes/extracts/deploy-member-configuration-add-mongod.rst

  .. include:: /includes/facts/sharded-clusters/add-a-shard.rst

---
title: "Configure Each Configuration Server in Your Cluster."
stepnum: 5
level: 4
ref: configure-cluster-members-configuration-servers
source:
  file: steps-deploy-sharded-cluster.yaml
  ref: configure-cluster-members-configuration-servers
---
title: "Configure Each ``mongos`` in Your Cluster."
stepnum: 6
level: 4
ref: configure-cluster-members-mongos
content: |

  From the :guilabel:`Member Configuration` section, click
  :guilabel:`Mongos Settings` to open the :binary:`~bin.mongos`
  configuration options. Each :binary:`~bin.mongos` process has the
  following options. You cannot modify options that are greyed out:

  .. list-table::
     :header-rows: 1
     :widths: 25 75

     * - Setting
       - Description

     * .. include:: /includes/extracts/deploy-sharded-member-configuration-hostname.rst

     * .. include:: /includes/extracts/deploy-sharded-member-configuration-port.rst

     * .. include:: /includes/extracts/deploy-sharded-member-configuration-add-mongos.rst

---
title: "Configure Each Replica Set in your Cluster."
stepnum: 7
level: 4
ref: modify-replication
source:
  file: steps-deploy-sharded-cluster.yaml
  ref: configure-cluster-replication
---
title: "Modify Advanced Configuration Options."
stepnum: 8
level: 4
ref: modify-advanced
source:
  file: steps-deploy-replica-set.yaml
  ref: set-advanced
---
title: "Click :guilabel:`Save`."
stepnum: 9
level: 4
ref: modify-save
content: |

  |mms| redirects you to the deployment page, where you must review
  your changes before deploying the updated configuration.
---
stepnum: 10
level: 4
ref: modify-review
source:
  file: steps-source-deployment-page.yaml
  ref: review-deployment
---
stepnum: 11
level: 4
ref: modify-deploy
source:
  file: steps-source-deployment-page.yaml
  ref: confirm-deployment
...
