---
title: "Click :guilabel:`Preferences` at the top of the page and then click 
       :guilabel:`Public API Access` in the left navigation pane."
stepnum: 1
level: 4
ref: cm-public-api-access
---
title: "In the :guilabel:`Access List`, click :guilabel:`Add` and enter an address."
stepnum: 2
level: 4
ref: add-ip-addresses
content: |
  Enter an IP address or CIDR range. To add multiple entries in the
  access list, repeat this step.

  You can enter any of the following:

  .. list-table::
     :header-rows: 1

     * - Entry

       - Grants

     * - An IP address

       - Access to available operations from that address.

     * - A CIDR-notated range of IP addresses

       - Access to available operations from those addresses.

  If you leave the access list empty, you have no access to
  certain operations.
...
