---
stepnum: 1
source:
  ref: account-nav-two-factor-auth
  file: steps-source-account-nav.yaml
---
stepnum: 2
source:
  file: steps-source-2fa.yaml
  ref: security-enable-2fa
---
stepnum: 3
source:
  file: steps-source-2fa.yaml
  ref: security-2fa-authenticator-configure-atlas
---
title: "On your mobile device or web browser, install Google Authenticator."
ref: security-2fa-authenticator-install
stepnum: 4
content: |

  Although only :guilabel:`Google Authenticator` is displayed in the UI,
  any TOTP mobile app or web browser plug-in may be used.

  .. note:: 
     Wherever you see the phrase **Google Authenticator** in this
     procedure, you can substitute the name of your preferred |2fa| app.

  .. _Google Authenticator: https://www.google.com/landing/2step/

  .. _Authy: https://authy.com/features/

  .. _Duo Mobile: https://duo.com/product/trusted-users/two-factor-authentication/duo-mobile

  .. list-table::
     :widths: 40 15 15 15 15
     :header-rows: 1

     * - App
       - iOS
       - Android
       - Windows Phone
       - Blackberry

     * - `Google Authenticator`_
       - `Link <https://itunes.apple.com/us/app/google-authenticator/id388497605>`__
       - `Link <https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2>`__
       - 
       - 

     * - `Duo Mobile`_
       - `Link <https://itunes.apple.com/us/app/duo-mobile/id422663827>`__
       - `Link <https://play.google.com/store/apps/details?id=com.duosecurity.duomobile>`__
       - `Link <https://www.microsoft.com/en-us/p/duo-mobile/9nblggh08m1g#activetab=pivot:overviewtab>`__
       - 

     * - `Authy`_
       - `Link <https://itunes.apple.com/us/app/google-authenticator/id388497605>`__
       - `Link <https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2>`__
       - 
       - 

     * - Microsoft Authenticator
       - `Link <https://itunes.apple.com/us/app/microsoft-authenticator/id983156458?mt=8>`__
       - `Link <https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en_US>`__
       - `Link <https://www.microsoft.com/en-us/p/microsoft-authenticator/9nblgggzmcj6?cid=msft_web_chart>`__
       - 

     * - Gauth
       - 
       - 
       - 
       - `Link <https://appworld.blackberry.com/webstore/content/19908006/?countrycode=US&lang=en>`__
    
---
title: "Add |service| to Google Authenticator."
ref: security-2fa-authenticator-add-service
stepnum: 5
content: |

  #. Start Google Authenticator.

  #. Click **+**.

  #. Choose how to pair the Google Authenticator app with |service|.
  
     - If your mobile device or web browser supports scanning barcodes,
       click :guilabel:`Scan a barcode`.

       Enable the device's camera, if prompted, and point the device at 
       the |service| page to capture the barcode.
     
     - If your mobile device or web browser does not support scanning
       barcodes, or if you prefer to enter a key, click
       :guilabel:`Enter provided key`.

       1. |service| displays the |service| :guilabel:`Account` with a
          :guilabel:`Key`.

       #. In Google Authenticator, click :guilabel:`Enter provided key` 
          then enter the account and key.

          (Duo Mobile, Authy and other apps have similar prompts.)
       
       After the barcode is scanned or account and key are entered, 
       the Google Authenticator app produces a 6-digit code 
       to verify the pairing.
       
  #. Once you receive the verification code, enter that code into the 
     into the :guilabel:`Verify your code` boxes. Each digit is
     entered in its own box.

  |service| automatically verifies the code and saves your settings.

  .. seealso::

     - Pairing third-party applications with `Duo Mobile 
       <https://guide.duo.com/third-party-accounts>`__

     - Pairing third-party applications with `Authy
       <https://support.authy.com/hc/en-us/articles/360006303934-Add-a-New-Two-Factor-Authentication-2FA-Account-Token-in-the-Authy-App>`__

     - Pairing third-party applications with `Microsoft Authenticator
       <https://support.microsoft.com/en-us/help/4026727/microsoft-account-how-to-use-the-microsoft-authenticator-app>`__

...
    
