title: "Click :guilabel:`Deployment`."
stepnum: 0
level: 4
ref: click-deployment
---
title: "Click :guilabel:`Deployment`, then the :guilabel:`Processes` tab."
stepnum: 0
level: 4
ref: click-deployment-processes
---
title: "Click :guilabel:`Deployment`, then the :guilabel:`Processes` tab, then the :guilabel:`Topology` view."
stepnum: 0
level: 4
ref: click-deployment-processes-topology
---
title: "Click :guilabel:`Deployment`, then the :guilabel:`Processes` tab, then the :guilabel:`List` view."
stepnum: 0
level: 4
ref: click-deployment-processes-list
---
title: "Click :guilabel:`Deployment`, then :guilabel:`Servers`."
stepnum: 0
level: 4
ref: click-deployment-servers
---
title: "Click :guilabel:`Deployment`, then :guilabel:`Agents`."
stepnum: 0
level: 4
ref: click-deployment-agents
---
title: "Click :guilabel:`Deployment`, then :guilabel:`Security`."
stepnum: 0
level: 4
ref: click-deployment-security
---
title: "Click :guilabel:`Deployment`, then the :guilabel:`Security` tab, and then :guilabel:`Authentication & SSL`."
stepnum: 0
level: 4
ref: click-deployment-security-authentication
---
title: "(Optional) For sharded clusters, filter which process type is listed."
stepnum: 0
level: 4
ref: filter-process-type
content: |

  For any process, click a button in its :guilabel:`Members` column to set
  which process type is listed.

  The four buttons are listed in the following order, left to right:
  :guilabel:`Shards`, :guilabel:`Configs`, :guilabel:`Mongos`, and
  :guilabel:`BIs`. 

  .. list-table::
     :widths: 20 80
     :header-rows: 1

     * - Process
       - Displays

     * - :guilabel:`Shards`

       - :program:`mongod` processes that host your data.

     * - :guilabel:`Configs`

       - :program:`mongod` processes that run as :term:`config
         servers <config server>` to store a sharded cluster's metadata.

     * - :guilabel:`Mongos`

       - :program:`mongos` processes that route data in a sharded cluster.

     * - :guilabel:`BIs`

       - :abbr:`BI (Business Intelligence)` processes access data in a sharded cluster.

---
title: "Optional. Make changes before you deploy."
stepnum: 0
level: 4
ref: drag
pre: |
  If needed, you can reconfigure processes and change the topology.
action:
  - heading: "To modify settings for a MongoDB process:"
    content: |
      a. Click the :guilabel:`Processes` tab.

      b. On the line listing the process, click :guilabel:`Modify`.

      c. Make changes as desired and click :guilabel:`Apply`.

  - heading: "To move a process to a different server:"
    content: |
      a. Click the :guilabel:`Servers` tab.

         .. note::
            The colored bar on the right of each server indicates the replica
            set or sharded cluster to which the server belongs.

      b. Drag and drop the process to a different server.

---
title: "Click :guilabel:`Review & Deploy` to review your changes."
stepnum: 0
level: 4
ref: review-deployment
---
title: "Review and approve your changes."
stepnum: 0
level: 4
ref: confirm-deployment
content: |

  |mms| displays your proposed changes.

  a. If you are satisfied, click :guilabel:`Confirm & Deploy`.
  b. Otherwise, click :guilabel:`Cancel` and you can make
     additional changes.
---
title: "Click :guilabel:`Review & Deploy` to review your changes."
stepnum: 0
level: 4
ref: review-deployment-2
---
title: "Review and approve your changes."
stepnum: 0
level: 4
ref: confirm-deployment-2
content: |

  |mms| displays your proposed changes.

  a. If you are satisfied, click :guilabel:`Confirm & Deploy`.
  b. Otherwise, click :guilabel:`Cancel` and you can make
     additional changes.
---
title: "Click :guilabel:`Review & Deploy`."
stepnum: 0
level: 4
ref: review-deployment-simple
---
title: "Click :guilabel:`Confirm & Deploy`."
stepnum: 0
level: 4
ref: confirm-deployment-simple
...
