ref: network-access-pl-aws
level: 4
stepnum: 1
inherit:
  file: steps-source-project-nav.yaml
  ref: project-nav-nw-access-page
---
ref: select-dedicated-aws
level: 4
stepnum: 2
inherit:
  file: steps-source-privatelink.yaml
  ref: create-private-endpoint
content: |

  {{dedicatedCluster}}
  
---
ref: create-private-endpoint-aws
level: 4
stepnum: 3
inherit:
  file: steps-source-privatelink.yaml
  ref: click-resource-button
content: | 

  {{dedicated}}

---
ref: select-cloud-provider-aws
stepnum: 4
level: 4
inherit:
  file: steps-source-privatelink.yaml
  ref: select-cloud-provider
content: |

  {{aws}}

---
ref: select-region-pl-aws
level: 4
stepnum: 5
inherit:
  ref: select-region
  file: steps-source-privatelink.yaml
post: |

  |service| creates |vpc| resources in the region
  you selected. This might take several minutes to complete.
---
level: 4
stepnum: 6
ref: configure-private-endpoint-aws
inherit:
  ref: configure-private-endpoint
  file: steps-source-privatelink.yaml
content: |

  {{aws}}

---

ref: finalize-private-endpoint-aws
level: 4
stepnum: 7
inherit:
  ref: finalize-private-endpoint
  file: steps-source-privatelink.yaml
content: |

  {{aws}}

---
ref: resource-sg-pl-aws
level: 4
stepnum: 8
inherit:
  ref: resource-sg-pl
  file: steps-source-privatelink.yaml

---
ref: attach-sg-pl-aws
level: 4
stepnum: 9
inherit:
  ref: attach-sg-pl
  file: steps-source-privatelink.yaml

---
ref: verify-private-endpoint-aws
level: 4
stepnum: 10
inherit:
  ref: verify-active-pl-aws
  file: steps-source-privatelink.yaml

...
