title: "Set up the Okta LDAP interface."
level: 4
ref: set-up-okta-ldap
content: |

  a. To learn more about setting up the Okta |ldap| interface,   see the 
     `Okta documentation <https://help.okta.com/en/prod/Content/Topics/Directory/LDAP-interface-main.htm>`__.

  #. Note your ``<okta-instance-id>``. You must provide it
     in several places during the configuration process.

     The instance name is located in the URL you use to sign in to your
     Okta account:

     .. code-block:: sh
        :copyable: false

        https://<okta-instance-id>.admin.okta.com

---
title: "Create a bind user."
level: 4
ref: bind-user-okta
content: |

  a. `Create a new Okta user <https://help.okta.com/en/prod/Content/Topics/Directory/eu-people.htm>`__
     to use as the |service| bind user. The bind user is an Okta 
     user that you use to query the account and to authenticate  
     database users' credentials when they connect to an |service| 
     database.

     .. important::

        Don't use your own user account for the bind user.

  #. Use the following template to determine the full Distinguished Name
     (DN) of your bind user: 

     .. code-block:: sh

        uid=<bind-user-email>,dc=<okta-instance-id>,dc=okta,dc=com

     For example, if your ``<bind-user-email>`` is 
     ``bind@example.com`` and your ``<okta-instance-id>`` is 
     ``mdb-example``, your bind user's DN is:  

     .. code-block:: sh
        :copyable: false

        uid=bind@example.com,ou=users,dc=mdb-example,dc=okta,dc=com

---
title: "Create database users in Okta."
level: 4
ref: create-db-users-okta
content: |

  If they don't exist already, create users in Okta that you want to 
  grant database access to:

  a. Navigate to your Okta People page.

  #. Click :guilabel:`Add Person`.

  #. Enter the user's details. Use email addresses for usernames.

     .. note:: 

        Avoid entering email addresses with plus symbols (`+`). The
        |service| |ldap| integration may encounter issues with email
        addresses containing plus symbols.

  #. Click :guilabel:`Save`.

...
