stepnum: 1
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: click-deployment-processes-topology
---
title: "Shut down the deployment."
stepnum: 2
level: 4
ref: shutdown-cloud
content: |

  a. Click :icon-mms:`ellipsis` for the deployment that you want to
     shut down.

  #. Click :guilabel:`Shutdown`.

  #. Click :guilabel:`Shutdown Process` to confirm.

---
stepnum: 3
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: review-and-confirm
...
