title: "Create a profile."
stepnum: 0
level: 4
ref: create-profile
content: |

  .. tabs::

     .. tab:: Default Profile
        :tabid: default-profile

        This command creates a :ref:`profile <mcli-profiles>` called
        ``default`` in the :ref:`mcli-config-file`.

        Run the :ref:`mcli-config-command` command:

        .. code-block:: sh
              
          mongocli config {{serviceOption}}
        
     .. tab:: Named Profile
        :tabid: named-profile

        This command creates a :ref:`profile <mcli-profiles>` with a
        custom name in the :ref:`mcli-config-file`. To use this profile
        in a command, you must specify the profile with the
        ``--profile`` flag.

        Run the :ref:`mcli-config-command` command:

        .. code-block:: sh
              
          mongocli config {{serviceOption}} --profile <profile-name>

---
title: "Create a profile for the {{service}} project."
stepnum: 0
level: 4
ref: quick-create-profile
content: |
  Run the following :ref:`command <mcli-config-command>` to create a
  :ref:`profile <mcli-profiles>` called ``default``.

  .. code-block:: sh 

     mongocli config {{serviceOption}}

---
title: "Enter the :opsmgr:`URL you use to access Ops Manager </reference/config/ui-settings/#URL-to-Access-Ops-Manager>`."
stepnum: 0
level: 4
ref: enter-base-url
content: |

  .. code-block:: sh
     :copyable: false

     ? URL to Access Ops Manager: http://mms.example.com:8080

---
title: "Enter your {{apiKeys}}."
stepnum: 0
level: 4
optional: true
ref: enter-api-key
content: |

  When prompted, enter the ``Public API Key`` and ``Private API Key``
  for your {{service}} deployment.

  .. code-block:: sh
     :copyable: false
               
     ? Public API Key: abcdef
     ? Private API Key: [? for help]
     ************************************

---
title: "Choose your default organization."
stepnum: 0
level: 4
ref: enter-orgid
content: | 

  If you entered |api| keys, the command displays the name and ID of organizations that your |api| key can access.

  a. Select your organization:
      
     - Press the :kbd:`Down Arrow` and :kbd:`Up Arrow` 
       keys to highlight the desired organization, or
     - Type the organization name to filter the available 
       organizations.
    
     .. code-block:: sh
        :copyable: false

        ? Choose a default organization:  [Use arrows to move, type to filter]
        > Org1 (5e39bf1212121e685774c81c)

  #. Press :kbd:`Enter`.

  If you didn't enter |api| keys, the command prompts you to enter your
  ``Default Project ID``.

---
title: "Choose your default project."
stepnum: 0
level: 4
ref: enter-projectid
content: |

  If you entered |api| keys, the command displays the name and ID of
  projects that your |api| key can access.

  a. Select your project:
      
     - Press the :kbd:`Down Arrow` and :kbd:`Up Arrow`  
       keys to highlight the desired project, or
     - Type the project name to filter the available 
       projects.

     .. code-block:: sh
        :copyable: false

        ? Choose a default project:  [Use arrows to move, type to filter]
          Project1 (5e5ebffd0c04a97009061234)
          Project2 (5cfacee6014b761b07f15678)
        > Project3 (5e39bf4979358e6857741212)
          Project4 (5c815cc7014b768fb67e3434)

  #. Press :kbd:`Enter`.

  If you didn't enter |api| keys, the command prompts you to enter your
  ``Default Organization ID``.

---
title: "Verify your profile."
stepnum: 0
level: 4
ref: verify-profile
content: |

  View the :ref:`configuration file <mcli-config-file>` or run the 
  :ref:`mcli-config-describe-command` command to verify your profile.

  .. include:: /includes/admonitions/secure-config-file.rst

  .. tabs::
     :hidden:
    
     .. tab:: Default Profile
        :tabid: default-profile

        .. example::

           The following command returns the settings 
           in the {+default-profile+}:

           .. code-block:: sh
              :copyable: false

              mongocli config describe default
          
           The command returns the following settings. For security
           purposes, the command redacts |api| keys in the output.

           .. code-block:: sh
              :copyable: false
              
              {{opsMgrUrl}}
              org_id = 5f1f39ffc902201990f12345
              private_api_key = redacted
              project_id = 7ehf04abc10defb66c7d1234c
              public_api_key = redacted
              service = {{serviceName}}

     .. tab:: Named Profile
        :tabid: named-profile
        
        .. example::

           The following command returns the settings 
           in the profile named ``myMongoDB``:

           .. code-block:: sh
              :copyable: false

              mongocli config describe myMongoDB
          
           The command returns following settings. For security
           purposes, the command redacts |api| keys in the output.

           .. code-block:: sh
              :copyable: false
              
              {{opsMgrUrl}}
              org_id = 5f1f39ffc902201990f12345
              private_api_key = redacted
              project_id = 7ehf04abc10defb66c7d1234c
              public_api_key = redacted
              service = {{serviceName}}


...
