title: "Copy your PEM certificate to ``/etc/mongodb-mms/``."
stepnum: 1
level: 4
ref: copy
content: |
  Issue the following sequence of commands:

  .. code-block:: sh

     sudo cp -a mms-ssl-unified.crt /etc/mongodb-mms/
     sudo chown mongodb-mms-agent:mongodb-mms-agent /etc/mongodb-mms/mms-ssl-unified.crt
     sudo chmod 600 /etc/mongodb-mms/mms-ssl-unified.crt

---
title: "Edit the following parameter in the configuration file."
stepnum: 2
level: 4
ref: edit
content: |

  .. include:: /includes/list-table-automation-agent-conf-file-locations.rst

  .. example::

      The following settings specifies the
      :asetting:`httpsCAFile` file as
      ``/etc/mongodb-mms/mms-ssl-unified.crt``.

     .. code-block: sh

        httpsCAFile=/etc/mongodb-mms/mms-ssl-unified.crt
---
title: "Restart the Automation Agent for the configuration update to take effect."
stepnum: 3
level: 4
ref: restart
content: |

  .. example::

     .. code-block: sh

        sudo /etc/init.d/mongodb-mms-automation-agent restart
...
