title: "From the :guilabel:`Clusters` view, click the :guilabel:`Security` tab, then :guilabel:`Peering`."
level: 4
ref: click-security
stepnum: 1
---
title: "Click :guilabel:`New Peering Connection`."
level: 4
ref: click-new-peering-connection
stepnum: 2
---
title: "Select your cloud provider in the :guilabel:`Peering Connection` modal, then click :guilabel:`Next`."
level: 4
ref: select-cloud-provider
stepnum: 3
---
title: "Enter the desired CIDR next to :guilabel:`Atlas CIDR`."
level: 4
ref: enter-Atlas-CIDR
content: |

   .. tabs::

     tabs:

     - id: aws
       name: AWS
       content: |

          For AWS, the |service| CIDR must be at least /24 and at most /21.

     - id: gcp
       name: GCP
       content: |

          For GCP, the |service| CIDR must be /18 or larger.

     - id: azure
       name: Azure
       content: |

          For Azure, the |service| CIDR must be at least /24 and at most /21.
      
stepnum: 4
---
title: "Click :guilabel:`Initiate Peering`."
level: 4
ref: click-initialte-peering
stepnum: 5
...
