title: "Set the source for |onprem| and {+mdbagent+}s to install binaries to the :guilabel:`Ops Manager Application Server`."
stepnum: 1
level: 4
ref: edit-config-file-remote
content: |

  a. Click :guilabel:`Admin` in the upper right corner to open system
     administration.

  #. From the :guilabel:`General` tab, click
     :guilabel:`Ops Manager Config`.

  #. Click the :guilabel:`Miscellaneous` tab at the top of the page.

  #. In the :guilabel:`MongoDB Version Management` section, select the 
     following settings:

     .. list-table::
        :widths: 30 70
        :header-rows: 1

        * - Option
          - Action

        * - :guilabel:`Installer Download Source`

          - Select :guilabel:`remote`.

            All necessary installers are downloaded over the internet 
            from |company| or from another |http| or |https| endpoint 
            that the hosts can access.

        * - :guilabel:`Base URL`

          - |http| endpoint to fetch MongoDB binaries from. If the
            endpoint uses |https|, |mms| validates the certificate using
            the |certauth| file set in :setting:`httpsCAFile`. If
            unset, |mms| downloads MongoDB binaries from the remote
            URLs as listed in the :ref:`Network Requirements <network-requirements>`.

            |application| hosts require an internet connection.

        * - :guilabel:`Versions Directory`
          - Accept the platform default value unless you need to
            change it to meet a requirement for your environment.

            The default locations for the :setting:`Versions Directory`
            depend on your |onprem| host platform:

            .. list-table::
               :header-rows: 1
               :widths: 30 70

               * - Platform
                 - Versions Directory Default Path

               * - RHEL, Ubuntu
                 - ``/opt/mongodb/mms/mongodb-releases``

               * - Linux Archive
                 - ``<userSelected>/mongodb-releases``

               * - Windows
                 - ``C:\MMSData\MongoDBReleases``

            The |application| expects the MongoDB binaries to be
            stored in this directory on every |onprem| host.

        * - :guilabel:`Backup Versions Auto Download`
          - Select ``true`` if your :opsmgr:`Backup Daemon </reference/glossary/#std-term-backup-daemon>` and
            |application| run on the same platform (chip
            architectures, operating systems, or operating system
            versions). If they run on separate platforms, select
            ``false``.

        * - :guilabel:`Backup Versions Auto Download Enterprise Builds`
          - Select ``true`` if you want the Backup Daemon to download
            MongoDB Enterprise builds as well as MongoDB Community
            builds.

            Queryable Backups require MongoDB Enterprise. 

        * - :guilabel:`Required Module for Backup`
          - Select which build of MongoDB you want the
            :opsmgr:`Backup Daemon </reference/glossary/#term-backup-daemon>` to use for the :opsmgr:`head database </reference/glossary/#std-term-head-database>`.
            Select :guilabel:`Enterprise Required` if you want the
            Backup Daemon to download only MongoDB Enterprise builds.

            .. include:: /includes/head-database-backup-deprecated.rst
---
stepnum: 2
level: 4
ref: confirm-deployment-remote
source:
  file: steps-configure-hybrid-mode.yaml
  ref: confirm-deployment
...
