inherit:
  file: steps-source-project-nav.yaml
  ref: project-nav-settings-page
ref: nav-to-project-settings
stepnum: 1
---
title: "View or modify project settings."
level: 4
ref: project-settings
stepnum: 2
content: |

  :guilabel:`Project Settings` displays the configurable settings.
  See :ref:`group-settings-page` to view the setting descriptions.

  .. cond:: onprem

     If you access |mms| as a user with the :authrole:`Global Owner` 
     role, you can also update :guilabel:`Admin Project Settings` under 
     the :guilabel:`Global Admin Only` section. See
     :ref:`admin-only-group-settings` to view the
     administrative setting descriptions.
...
