ref: network-access-pl
level: 4
stepnum: 1
inherit:
  file: steps-source-project-nav.yaml
  ref: project-nav-nw-access-page
---
ref: create-private-endpoint
level: 4
stepnum: 2
inherit:
  file: steps-source-privatelink.yaml
  ref: create-private-endpoint
---
ref: select-cloud-provider-aws
stepnum: 3
level: 4
inherit:
  file: steps-source-privatelink.yaml
  ref: select-cloud-provider
content: |

  {{gcp}}

---
ref: select-region-pl
level: 4
stepnum: 4
inherit:
  ref: select-region
  file: steps-source-privatelink.yaml
post: |

  |service| creates |vpc| resources in the region
  you selected. This might take several minutes to complete.
---
level: 4
stepnum: 5
ref: configure-private-endpoint-aws
inherit:
  ref: configure-private-endpoint
  file: steps-source-privatelink.yaml
content: |

  {{gcp}}

---
ref: verify-private-endpoint
level: 4
stepnum: 6
inherit:
  ref: verify-active-pl-gcp
  file: steps-source-privatelink.yaml

...
