title: "Navigate to the Project Backup configuration page."
stepnum: 1
ref: nav-to-backup-config
content: |

   a. Click :guilabel:`Admin`
   b. Click :guilabel:`Projects`
   c. Under the <Project Name>, click :guilabel:`More ...`.
   d. In the row for :guilabel:`Backup Configuration`, click :guilabel:`View`.

   .. seealso:: :ref:`admin-console-general-projects`

---
title: "Complete the KMIP fields."
stepnum: 2
ref: complete-group-kimp-fields
content: |
   .. list-table::
      :widths: 20 40

      * - :guilabel:`KMIP client certificate path`

        - Type the absolute path for the client certificate file on the
          |mms| host. |onprem| uses this certificate to authenticate
          itself to the KMIP server.

          A single file can hold both the CA and client certificate.

      * - :guilabel:`KMIP client certificate password`

        - *Optional* Only enter if the certificate specified in
          :guilabel:`KMIP client certificate path` is encrypted.
---
title: "Click :guilabel:`Save Changes`."
stepnum: 3
ref: save-group-kimp-changes
...
