title: "Log into |service|."   
level: 4
ref: login
---
stepnum: 2
level: 4
ref: click-security-advanced-authz
source:
  ref: project-nav-advanced-page
  file: steps-source-project-nav.yaml
---
title: "Toggle the button next to :guilabel:`LDAP Authorization` to :guilabel:`On`."
level: 4
ref: toggle-on
---
title: "Enter the server details and bind credentials for your LDAP server in the :guilabel:`Configure Your LDAP Server` panel."
level: 4
ref: enter-password
---
title: "Enter a query template in :guilabel:`Query Template`."
level: 4
ref: enter-query-template
optional: true
content: |

  When a user attempts to perform an action, |service| executes the 
  :manual:`LDAP query template 
  </reference/configuration-options/#security.ldap.authz.queryTemplate>`
  to obtain the LDAP groups to which the authenticated user belongs.
  |service| permits the action if the query returns at least one group 
  that is authorized to perform the action. |Service| does not permit 
  the action if the query returns no groups that are authorized to 
  perform the action.
  
  |service| substitutes the authenticated username in the ``{USER}`` 
  placeholder when it runs the query. The query is relative to the host 
  specified in :guilabel:`Server Hostname`. 
  
  The formatting for the query must conform to `RFC4515 
  <https://tools.ietf.org/search/rfc4515>`_

  If you do not provide a query template, |service| applies the default
  value: ``{USER}?memberOf?base``.
---
title: "Click :guilabel:`Verify and Save`."
level: 4
ref: verify-and-save
content: |

  Wait for |service| to deploy your changes. |service| verifies that
  your clusters can connect to, authenticate with, and query your LDAP
  server using the configuration details that you provide.
...
