---
title: "Configure ``kubectl`` to default to your namespace."
level: 4
stepnum: 0
ref: configure-kubectl-namespace
content: |

  If you have not already, run the following command to execute all 
  ``kubectl`` commands in the namespace you :ref:`created <k8s-prerequisites>`:

  .. code-block:: sh

     kubectl config set-context $(kubectl config current-context) --namespace=<namespace>
...
