stepnum: 1
level: 4
inherit:
  file: steps-source-project-nav.yaml
  ref: project-nav-deployment-topology
---
title: "On the card with the replica set, click :guilabel:`Modify`."
stepnum: 2
level: 4
ref: edit-replica-set
---
title: "Configure the replica set."
stepnum: 3
level: 4
ref: configure
content: |

  In the :guilabel:`Replica Set Configuration` section, complete the
  following fields.

  .. list-table::
     :widths: 30 70

     * - :guilabel:`Auth Schema Version`
       - Select the schema for storing the user data for your
         deployment. If you are upgrading from a MongoDB version older
         than 3.0, MongoDB 3.0 uses a different schema for user data
         than previous versions. For compatibility information, see the
         :ref:`Security Changes <legacy-auth-model-removed>`
         in the MongoDB 3.0 release notes.

     * - :guilabel:`Feature Compatibility` (Optional)
       - Select the :manual:`feature compatibility set
         </reference/command/setFeatureCompatibilityVersion>`. This
         field appears if your deployment MongoDB version is
         ``3.4`` or later.

     * - :guilabel:`Version`
       - Select the MongoDB version for your replica set.

     * - :guilabel:`Log File`
       - Specify the location and name of the log file for the 
         |mongod| process. The location must exist on the host.
---
title: "Click :guilabel:`Save`."
level: 4
ref: click-save
stepnum: 4
---
stepnum: 5
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: review-deployment
---
stepnum: 6
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: confirm-deployment
...
