title: "Fork these repositories into your own GitHub account."
ref: fork-repos
content: |
  `This guide from GitHub <https://guides.github.com/activities/forking/>`_ covers the specifics.

  - https://github.com/mongodb/docs
  - https://github.com/mongodb/docs-ecosystem
  - https://github.com/mongodb/docs-primer
  - https://github.com/mongodb/docs-assets
  - https://github.com/mongodb/docs-tools
  - https://github.com/10gen/mms-docs
  - https://github.com/10gen/cloud-docs
  - https://github.com/mongodb/docs-bi-connector
---
title: "Clone and prepare MongoDB Documentation Assets."
ref: clone-docs-assets
action:
  language: sh
  code: |
    git clone git@github.com:<yourid>/docs-assets.git
    cd docs-assets
    git remote add upstream git@github.com:mongodb/docs-assets.git
---
title: "Clone and prepare MongoDB Documentation Toolset."
ref: prep-docs-tools
action:
  language: sh
  code: |
    git clone git@github.com:<yourid>/docs-tools.git
    cd docs-tools
    git remote add upstream git@github.com:mongodb/docs-tools.git
---
title: "Clone and prepare MongoDB Manual documentation."
ref: clone-docs
action:
  language: sh
  code: |
    git clone git@github.com:<yourid>/docs.git
    cd docs
    giza generate assets
    git remote add upstream git@github.com:mongodb/docs.git
---
title: "Clone and prepare MongoDB Primer documentation."
ref: clone-docs-primer
action:
  language: sh
  code: |
    git clone git@github.com:<yourid>/docs-primer.git
    cd docs-primer
    git remote add upstream git@github.com:mongodb/docs-primer.git
---
title: "Clone and prepare the Cloud/Ops Manager documentation."
ref: clone-mms-docs
action:
  language: sh
  code: |
    git clone git@github.com:<yourid>/mms-docs.git
    cd mms-docs
    git remote add upstream git@github.com:10gen/mms-docs.git
---
title: "Clone and prepare the Atlas documentation."
ref: clone-cloud-docs
action:
  language: sh
  code: |
    git clone git@github.com:<yourid>/cloud-docs.git
    cd cloud-docs
    git remote add upstream git@github.com:10gen/cloud-docs.git
---
title: "Clone and prepare the BI Connector documentation."
ref: clone-bi-docs
action:
  language: sh
  code: |
    git clone git@github.com:<yourid>/docs-bi-connector.git
    cd docs-bi-connector
    git remote add upstream git@github.com:10gen/docs-bi-connector.git
...
