title: "Click :guilabel:`Deployment`, then :guilabel:`Processes`."
stepnum: 1
ref: select-deployment
---
title: "Click :guilabel:`Modify` next to the MongoDB process for which
        you want to configure auditing."
stepnum: 2
ref: click-modify
---
title: "Click :guilabel:`Advanced Options`."
stepnum: 3
ref: click-advanced-options
---
title: "Click :guilabel:`+ Add Option`."
stepnum: 4
ref: click-add-option
---
title: "Select :guilabel:`auditLogDestination` from the :guilabel:`Startup Option` menu."
stepnum: 5
ref: select-auditlogDestination
---
title: "Select the desired destination for audit events from the :guilabel:`Value` menu."
stepnum: 6
ref: set-auditlogDestination
---
title: "(Optional) If you selected ``file`` as the audit log destination,
       repeat step 4 and specify the following additional properties:"
stepnum: 7
ref: set-file-properties
content: |
   - ``auditLogFormat``: ``JSON`` or ``BSON``

   - ``auditLogPath``: the desired location of the audit log file
---
title: "(Optional) To filter which events are audited, repeat steps 1-4
       and add the ``auditLogFilter`` property."
stepnum: 8
ref: set-filter
content: |
   For information about how to create filters, see 
   :manual:`Configure Audit Filters</tutorial/configure-audit-filters>`.
---
title: "Click :guilabel:`Apply` to deploy your auditing configuration."
stepnum: 9
ref: click-apply
...
