title:
  text: "Install Google Authenticator from either the Google Play store or the iOS Apple Store, depending on your device."
  character: "`"
stepnum: 1
ref: install
---
title:
  text: Run Google Authenticator.
  character: "`"
stepnum: 2
ref: run
---
title:
  text: "Click ``Begin Setup``."
  character: "`"
stepnum: 3
ref: begin
---
title:
  text: "When prompted, select how you will enter the shared private key."
  character: "`"
stepnum: 4
ref: private-key
content: |
  Under ``Manually Add an Account``, select either ``Scan a barcode`` or
  ``Enter provided key``. Stay on this screen while you use the next steps
  to access the barcode or key in |mms|.
---
title:
  text: "In |mms|, click on your user name in the upper-right hand corner and select :guilabel:`Account`"
  character: "`"
stepnum: 5
ref: select-profile
---
title:
  text: "Select the pencil icon for :guilabel:`Two Factor Authentication`."
  character: "`"
stepnum: 6
ref: configure-two-factor
content: |
  Or, if this is the first time you are setting up an account, click the
  :guilabel:`Configure` button to the right side of the
  :guilabel:`Account` page and follow the instructions.
# Is that "Or..." paragraph accurate?
---
title:
  text: "Select :guilabel:`Use Google Authenticator`."
  character: "`"
stepnum: 7
ref: authenticator
content: |
  |mms| provides a barcode and a :guilabel:`Can't scan the barcode?` link.
---
title:
  text: "Scan or enter the shared private key."
  character: "`"
stepnum: 8
ref: barcode
content: |
  If your smartphone can scan barcodes, then scan the barcode. Otherwise,
  click :guilabel:`Can't scan the barcode?` and type the provided
  :guilabel:`Key` into your smartphone.
---
title:
  text: "Enter the Google Authenticator code in |mms|."
  character: "`"
stepnum: 9
ref: code
content: |
  After you scan the barcode or enter the key, Google Authenticator
  generates a 6-digit code. Enter that in the box provided in |mms| and
  click :guilabel:`Verify`.
---
title:
  text: "Click :guilabel:`Save Changes`."
  character: "`"
stepnum: 10
ref: save
...
