---
title: "(Optional) For sharded clusters, filter which process type is listed."
stepnum: 0
level: 4
ref: filter-process-type
content: |

  The four buttons are listed in the following order, left to right:
  :guilabel:`Shards`, :guilabel:`Configs`, :guilabel:`Mongos`, and
  :guilabel:`BIs`. 

  .. list-table::
     :widths: 20 80
     :header-rows: 1

     * - Process
       - Displays

     * - :guilabel:`Shards`

       - :program:`mongod` processes that host your data.

     * - :guilabel:`Configs`

       - :program:`mongod` processes that run as :term:`config
         servers <config server>` to store a sharded cluster's metadata.

     * - :guilabel:`Mongos`

       - :program:`mongos` processes that route data in a sharded 
         cluster.

     * - :guilabel:`BIs`

       - :abbr:`BI (Business Intelligence)` processes that access data 
         in a sharded cluster.

---
title: "Optional. Make changes before you deploy."
stepnum: 0
level: 4
ref: drag
pre: |
  If needed, you can reconfigure processes and change the topology.
action:
  - heading: "To modify settings for a MongoDB process:"
    content: |
      a. Click the :guilabel:`Processes` tab.

      b. On the line listing the process, click :guilabel:`Modify`.

      c. Make changes as desired and click :guilabel:`Save`.

  - heading: "To move a process to a different server:"
    content: |
      a. Click the :guilabel:`Servers` tab.

         .. note::
            The colored bar on the right of each server indicates the replica
            set or sharded cluster to which the server belongs.

      b. Drag and drop the process to a different server.

---
title: "Click :guilabel:`Review & Deploy` to review your changes."
stepnum: 0
level: 4
ref: review-deployment
---
title: "Click :guilabel:`Confirm & Deploy` to deploy your changes."
stepnum: 0
level: 4
ref: confirm-deployment
content: |

  Otherwise, click :guilabel:`Cancel` and you can make
  additional changes.
---
title: "Click :guilabel:`Review & Deploy` to review your changes."
stepnum: 0
level: 4
ref: review-deployment-2
---
title: "Review and approve your changes."
stepnum: 0
level: 4
ref: confirm-deployment-2
content: |

  |mms| displays your proposed changes.

  a. If you are satisfied, click :guilabel:`Confirm & Deploy`.
  b. If you want to make further configuration changes, 
     click :guilabel:`Cancel`. Click :guilabel:`Modify` for the
     cluster to make additional changes.
---
title: "Click :guilabel:`Review & Deploy`."
stepnum: 0
level: 4
ref: review-deployment-simple
---
title: "Click :guilabel:`Confirm & Deploy`."
stepnum: 0
level: 4
ref: confirm-deployment-simple
---
title: "Click :guilabel:`Review & Deploy` to review your changes."
ref: review-and-confirm
level: 4
content: |

  |mms| displays your proposed changes.

  a. If you are satisfied, click :guilabel:`Confirm & Deploy`.
  b. If you want to make further configuration changes, 
     click :guilabel:`Cancel`. Click :guilabel:`Modify` for the
     cluster to make additional changes.
...
