title: "Add the ``krb5Principal`` value."
level: 4
ref: kerberos-agent-config-principal
stepnum: 1
pre: |
  Set the ``krb5Principal`` to the Kerberos SPN for the agent.

  .. example::

     .. code-block:: ini

        krb5Principal=<agent>-agent/db1.example.com@EXAMPLE.COM

---
title: "Add the ``krb5Keytab`` value."
level: 4
ref: kerberos-agent-config-keytab
stepnum: 2
pre: |
  Set the ``krb5Keytab`` to the complete absolute path of the
  keytab file for the agent.

  .. example::

     .. code-block:: ini

        krb5Keytab=/etc/mongodb-mms/<agent>-agent.keytab

---
title: "Restart the agent."
level: 4
ref: kerberos-agent-restart
stepnum: 3
...