stepnum: 1
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: click-deployment-processes-topology
---
title: "Click the ellipsis icon for the process and click :guilabel:`Pause Automation`."
stepnum: 2
level: 4
ref: pause
---
title: "Click :guilabel:`Pause Automation` again to confirm."
stepnum: 3
level: 4
ref: confirm-pause
---
stepnum: 4
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: review-deployment-simple
---
stepnum: 5
level: 4
source:
  file: steps-source-deployment-page.yaml
  ref: confirm-deployment-simple
...
