title: "In a web browser, open |onprem|."
stepnum: 1
level: 4
ref: open
---
title: "Create a new |onprem| group for Data Center #1."
stepnum: 2
level: 4
ref: create-group-1
content: |
  a. Click on your user name in the upper-right hand corner and select :guilabel:`My Groups`.

  #. Click :guilabel:`Add Group`.

  #. Enter the group name.

  #. Click :guilabel:`Create Group`.
---
title: "Create a second |onprem| group for the Data Center #2."
stepnum: 3
level: 4
ref: create-group-2
---
title: "Click the :guilabel:`Admin` link at the upper right of the page to open the Admin interface."
stepnum: 4
level: 4
ref: admin
---
title: "Configure backup resources."
stepnum: 5
level: 4
ref: configure-resources
content: |
  a. Click the :guilabel:`Backup` tab.

  b. Click the :guilabel:`Daemons` page and check that there are two daemons
     listed.

  c. Click the :guilabel:`Snapshot Storage` page.

  d. Create a 
     :doc:`file system store </tutorial/manage-filestore-storage>` 
     or a 
     :doc:`blockstore </tutorial/manage-blockstore-storage>` 
     using network storage or a MongoDB database in Data Center #2.

  e. Click :guilabel:`Save`.

  f. Click the :guilabel:`Oplog Storage` page. 

  g. Add an oplog store using a MongoDB database in Data Center #2.

  h. Click :guilabel:`Save`.

---
title: "Assign resources to the data centers."
stepnum: 6
level: 4
ref: assign-resources
content: |
  a. Click the :guilabel:`General` tab.

  b. Click the :guilabel:`Groups` page.

  c. Select the name of the group assigned to Data Center 1.

  d. Click the :guilabel:`View` link to the right of 
     :guilabel:`Backup Configuration`.

  e. Select the local options for Group 1 / Data Center 1.

     .. list-table::
        :header-rows: 1
        :widths: 25 75

        * - Menu
          - Option
        * - :guilabel:`Backup Daemons`
          - Choose :guilabel:`Select Backup Daemons` then check the daemon that is in Data Center 1.
        * - :guilabel:`Oplog Stores`
          - Choose :guilabel:`Select Oplog Stores` then check the oplog store that is in Data Center 1.
        * - :guilabel:`Snapshot Stores`
          - Choose :guilabel:`Select Snapshot Stores` then check the snapshot store that is in Data Center 1.

  f. Repeat steps a to e for Group 2.

---
title: "Install agents."
stepnum: 7
level: 4
ref: install-agents
content: |
  If you are using Automation:

  a. :doc:`Install the Automation Agent </tutorial/nav/install-automation-agent>` 
     for the group in Data Center 1 on each server in Data Center 1. 

  b. Install the Automation Agent for Data Center 2 on each server in Data
     Center 2. 

  c. The Automation Agent installs the Monitoring and Backup agents as needed.

  If you are not using Automation:

  a. Select the group assigned to Data Center 1 from the drop-down menu in the
     top navigation bar.

  b. Click :guilabel:`Deployment`, then the :guilabel:`Agents` tab.

  c. Click :guilabel:`Downloads & Settings`.

  d. Download and install the Monitoring and Backup agents for the group
     assigned to Data Center 1.

  e. Select the group in Data Center 2 from the drop-down menu in the top
     navigation bar.

  f. Download and install its :doc:`Monitoring </tutorial/nav/install-monitoring-agent>` and :doc:`Backup </tutorial/nav/install-backup-agent>` agents.

...
