title: "Navigate to the Backup configuration tab."
stepnum: 1
ref: nav-to-backup-config
content: |

   a. Click :guilabel:`Admin`.
   b. Click :guilabel:`General`.
   c. Click :guilabel:`Ops Manager Config`.
   d. Click :guilabel:`Backup` tab.

   .. seealso:: :ref:`admin-console-general-om-config`

---
title: "Complete the KMIP fields."
stepnum: 2
ref: complete-kimp-fields
content: |

   Update the following |kmip| host fields in the
   :guilabel:`KMIP Server Configuration` section:

   .. list-table::
      :widths: 20 40

      * - :setting:`KMIP Server Host`

        - Type the |fqdn| for the |kmip| host.

      * - :setting:`KMIP Server Port`

        - Type the port on which the |kmip| host is listening for
          |kmip| connections. The default |kmip| port is `5696
          <http://www.iana.org/assignments
          /service-names-port-numbers/service-names-port-
          numbers.xhtml?&page=95>`_.

      * - :setting:`KMIP Server CA File`

        - Type the absolute path for the |certauth| file on the |mms|
          host. This must be the same |certauth| file stored on the
          |kmip| host.

---
title: "Click :guilabel:`Save`."
stepnum: 3
ref: save-kimp-changes

...
