ref: go-clusters-view-cluster
level: 4
stepnum: 1
source:
  file: steps-connect-to-cluster-master.yaml
  ref: go-clusters-view

---
ref: go-clusters-review-secure
level: 4
stepnum: 2
source:
  file: steps-connect-to-cluster-master.yaml
  ref: go-clusters-secure
replacement:
  connChoice: your driver
---
ref: go-clusters-review-ip-access-list-connection
level: 4
stepnum: 3
source:
  file: steps-connect-to-cluster-master.yaml
  ref: go-clusters-ip-access-list-connection

---
ref: create-mongodb-user-cluster
level: 4
stepnum: 4
source:
  file: steps-connect-to-cluster-master.yaml
  ref: create-mongodb-user

---
title: "Select :guilabel:`Drivers`."
level: 4
stepnum: 5
ref: connect-details-driver
content: |

  In the :guilabel:`Choose a connection method` step, select
  :guilabel:`Drivers`.

---
title: "Select Your Driver and Version."
level: 4
stepnum: 6
ref: connect-select-driver
content: |

  Select your driver and version from the dropdown menus.
  The code sample containing a connection string displays.
  Replace ``<password>`` with the password specified when you created
  your database user. 

  .. include:: /includes/admonitions/notes/note-escape-special-chars-pwd.rst

  To learn more, see
  :driver:`Driver Compatibility </driver-compatibility-reference/>`.

...
