title: "Upload the certificate file to each |onprem| host."
ref: upload-|pem|
level: 4
stepnum: 1
content: |

  a. Upload your ``.pem`` file to each |application| host. This
     certificate must be uploaded to each |onprem| host so they can
     accept |tls| connections.

  b. Change the owner of the ``.pem`` file to the user and group that
     own the |onprem| process.

  c. Change the permissions of the ``.pem`` file so only the file
     owner can read and write the file.

---
title: "Enable |tls| for the |application|."
ref: configure-mms-host-for-https
level: 4
stepnum: 2
content: |

  a. Click :guilabel:`Admin` in the |mms| application to view the
     :guilabel:`Admin` interface.

  #. Click the :guilabel:`General` tab

  #. Click :guilabel:`Ops Manager Config`.

  #. Click :guilabel:`Web Server & Email`.

  #. Set the following options under :guilabel:`Web Server` heading:

     .. list-table::
        :stub-columns: 1
        :header-rows: 1
        :widths: 30 70

        * - Option
          - Action

        * - :setting:`URL to Access Ops Manager`
          - Provide the full |url| for |application| including port
            ``8443`` for |https| access.

            .. example::

               .. code-block:: ini
                  :copyable: false

                  https://opsmanager.example.com:8443

        * - :setting:`HTTPS PEM Key File`
          - Type the absolute file system path where the ``.pem``
            file is located on all |onprem| hosts in this box.

        * - :setting:`HTTPS PEM Key File Password`
          - If you encrypted the |https| |pem| Key File, type the
            password needed to decrypt it in this box.

        * - :setting:`Client Certificate Mode`
          - Select if client applications or {+mdbagent+}s must
            present a |tls| certificate when connecting to a
            |tls|\-enabled |onprem|. |onprem| checks for certificates
            from these client hosts when they try to connect. If you
            choose to require the client |tls| certificates, make sure
            they are valid.

            Accepted values are:

            - :guilabel:`None`
            - :guilabel:`Required for Agents Only`
            - :guilabel:`Required for All Requests`

  #. Click :guilabel:`Save`.

---
title: "*(Optional)* Change the minimum |tls| version."
ref: tls-minimum
level: 4
stepnum: 3
content: |

  In :ref:`opsmgr-server-4.4.13` and later, the |application|
  requires its clients to use |tls| version 1.2 by default.

  To change the minimum |tls| version:

  a. Click :guilabel:`Admin` in the |mms| application to view the
     ``Admin`` interface.

  #. Click the :guilabel:`General` tab

  #. Click :guilabel:`Ops Manager Config`.

  #. Click :guilabel:`Custom`.

  #. Configure the minimum |tls| version.

  #. Enter :setting:`mms.minimumTLSVersion` in the :guilabel:`Key` box.

  #. Enter a minimum |tls| version in the :guilabel:`Value` box.

     The following values are accepted:

     - ``TLSv1``
     - ``TLSv1.1``
     - ``TLSv1.2``

  #. Click :guilabel:`Save`.

---
title: "*(Optional)* Specify which |tls| cipher suites you want to exclude."
ref: cipher-exclusions
level: 4
stepnum: 4
content: |

  To exclude specific |tls| cipher suites from |tls| connections
  with the |application|.

  a. Click :guilabel:`Admin` in the |mms| application to view the
     ``Admin`` interface.

  #. Click the :guilabel:`General` tab

  #. Click :guilabel:`Ops Manager Config`.

  #. Click :guilabel:`Custom`.

  #. Enter :setting:`mms.disableCiphers` in the :guilabel:`Key` box.

  #. Enter a comma-separated list of cipher suites to disable in the
     :guilabel:`Value` box.

     .. important::
        Cipher suite names used in |mms| must follow :rfc:`RFC 5246
        <5246#appendix-C>` naming conventions. Do not use the OpenSSL
        naming convention.

        .. example::

           Use ``TLS_RSA_WITH_NULL_SHA256``, not ``NULL-SHA256``

  #. Click :guilabel:`Save`.

---
title: "Restart each |onprem| host to enable |tls|."
ref: restart
level: 4
stepnum: 5
content: |

  Restart the |application| per the instructions to
  :doc:`Start and Stop Ops Manager Application
  </tutorial/start-and-stop-application>`.
...
