file: /tutorial/deploy-replica-set
description: |
  Configure a three-member :term:`replica set` for either a
  development or production system.
---
file: /tutorial/deploy-geographically-distributed-replica-set
description: |
  Create a geographically distributed replica set to
  protect against location-centered availability limitations
  (e.g. network and power interruptions).
---
file: /tutorial/add-replica-set-arbiter
description: |
  Add an :term:`arbiter` to give a replica set an odd number of voting
  members to prevent :ref:`election <replica-set-elections>` ties. An
  arbiter does not hold data.
---
file: /tutorial/convert-standalone-to-replica-set
description: |
  Convert an existing standalone :program:`mongod` instance into a
  three-member replica set.
---
file: /tutorial/expand-replica-set
description: |
  Add a :program:`mongod` instance to an existing replica set.
---
file: /tutorial/remove-replica-set-member
description: |
  Remove a :program:`mongod` instance from a replica set.
---
file: /tutorial/replace-replica-set-member
description: |
  Update the replica set configuration when the hostname of a member's
  corresponding :program:`mongod` instance has changed.
...
