file: /tutorial/install-on-prem-with-rpm-packages
name: "Install with RPM Package"
description: |
  Install |onprem| on Red Hat, Fedora, CentOS, and Amazon AMI Linux.
---
file: /tutorial/install-on-prem-with-deb-packages
name: "Install with DEB Package"
description: |
  Install |onprem| on Debian and Ubuntu systems.
---
file: /tutorial/install-on-prem-from-archive
name: "Install from Archive on Linux"
description: |
  Install |onprem| on other Linux systems, without using package management.
...
