---
file: /tutorial/configure-local-mode
description: |
  Procedures for configure |onprem| and/or the {+aagent+}s to 
  use locally hosted MongoDB installation binaries.
---
file: /tutorial/configure-application-high-availability
name: "Deploy a Highly Available Application"
description: |
  Outlines the process for achieving a highly available |mms|
  deployment.
---
file: /tutorial/configure-backup-high-availability
name: "Deploy Highly Available Backups"
description: |
  Make the Backup system highly available.
---
file: /tutorial/assign-snapshot-stores-to-data-center
description: |
  Assign snapshot stores to specific data centers.
---
file: /tutorial/use-with-http-proxy
name: "Pass Outgoing Traffic through HTTP Proxy"
description: |
  Configure |onprem| to pass all outgoing requests through an HTTP or
  HTTPS proxy.
...
