file: /tutorial/deploy-shard-cluster
description: |
  Set up a sharded cluster by creating the needed data directories,
  starting the required MongoDB instances, and configuring the cluster
  settings.
---
file: /tutorial/choose-a-shard-key
description: |
  Choose the field that MongoDB uses to parse a collection's documents
  for distribution over the cluster's shards. Each shard holds documents
  with values within a certain range.
---
file: /tutorial/shard-collection-with-a-hashed-shard-key
description: |
  Shard a collection based on hashes of a field's values in order to
  ensure even distribution over the collection's shards.
---
file: /tutorial/add-shards-to-shard-cluster
description: |
  Add a shard to add capacity to a sharded cluster.
---
file: /tutorial/deploy-config-servers
description: |
  Convert a test deployment with one config server to a production
  deployment with three config servers.
---
file: /tutorial/convert-replica-set-to-replicated-shard-cluster
description: |
  Convert a replica set to a sharded cluster in which each shard is its
  own replica set.
---
file: /tutorial/convert-sharded-cluster-to-replica-set
description: |
  Replace your sharded cluster with a single replica set.
...

