file: /tutorial/create-project-using-configmap
description: |
  Create a |k8s-configmap| to link the |k8s-op-short| to your |com|
  Project.
---
file: /tutorial/create-operator-credentials
description: |
  Create a |k8s| secret so the |k8s-op-short| can create and update
  |k8s-objs| in your |com| Project.
...