file: /tutorial/deploy-shard-cluster
description: |
  Set up a :term:`sharded cluster` by creating the needed data
  directories, starting the required MongoDB instances, and
  configuring the cluster settings.
---
file: /tutorial/choose-a-shard-key
description: |
  Choose the field that MongoDB uses to parse a collection's documents
  for distribution over the cluster's shards. Each shard holds documents
  with values within a certain range.
---
file: /tutorial/shard-collection-with-a-hashed-shard-key
description: |
  Shard a collection based on hashes of a field's values in order to
  ensure even distribution over the collection's shards.
---
file: /tutorial/enable-authentication-in-sharded-cluster
description: |
  Control access to a sharded cluster through a key file and
  the :setting:`keyFile` setting on each of the cluster's components.
---
file: /tutorial/view-sharded-cluster-configuration
description: |
  View status information about the cluster's databases, shards, and
  chunks.
---
file: /tutorial/add-shards-to-shard-cluster
description: |
  Add a shard to add capacity to a sharded cluster.
---
file: /tutorial/convert-replica-set-to-replicated-shard-cluster
description: |
  Convert a :term:`replica set` to a sharded cluster in which each shard
  is its own replica set.
...
