file: /tutorial/deploy-replica-set
description: |
  Configure a three-member replica set for either a
  production system.
---
file: /tutorial/deploy-replica-set-for-testing
description: |
  Configure a three-member replica set for either a
  development and testing systems.
---
file: /tutorial/deploy-geographically-distributed-replica-set
description: |
  Create a geographically redundant replica set to
  protect against location-centered availability limitations
  (e.g. network and power interruptions).
---
file: /tutorial/add-replica-set-arbiter
description: |
  Add an arbiter give a replica set an odd number of voting
  members to prevent election ties.
---
file: /tutorial/convert-standalone-to-replica-set
description: |
  Convert an existing standalone ``mongod`` instance into a
  three-member replica set.
---
file: /tutorial/expand-replica-set
description: |
  Add a new member to an existing replica set.
---
file: /tutorial/remove-replica-set-member
description: |
  Remove a member from a replica set.
---
file: /tutorial/replace-replica-set-member
description: |
  Update the replica set configuration when the hostname of a member's
  corresponding ``mongod`` instance has changed.
...
