name = "visual-studio-extension"
title = "C# Analyzer"
toc_landing_pages = ["/analyze-code"]

[constants]
product = "MongoDB C# Analyzer"
product-short = "C# Analyzer"
product-source-repo = "https://github.com/mongodb/mongo-csharp-analyzer"
# The home page is the project's Github repo for the time being. This may change
# to a DevRel article or product page such as
# https://www.mongodb.com/kafka-connector if someone writes such a page in the future.
product-home-page = "{+product-source-repo+}"
product-nuget-link = "https://www.nuget.org/packages/MongoDB.Analyzer"
product-package-name = "MongoDB.Analyzer"
product-version = "1.5"
product-version-full = "{+product-version+}.0"
product-settings-file-constant = "mongodb.analyzer.json"
product-jira = "https://jira.mongodb.org/browse/VS"

query-api = "MongoDB Query API"

driver-long = "MongoDB .NET/C# driver"
driver-short = ".NET/C# driver"
driver-docs = "https://www.mongodb.com/docs/drivers/csharp/current"
