[assets.output_paths]
repository_path = "source/includes"

[[assets.sources.repository]]
repo = "mongodb/mongo-rust-driver"

[[assets.sources.repository.targets]]
source = "src/test/lambda_examples/auth.rs"
output = "drivers-examples/auth.rs"

[[assets.sources.repository.targets]]
source = "src/test/lambda_examples/no_auth.rs"
output = "drivers-examples/no_auth.rs"

[[assets.sources.repository]]
repo = "mongodb/mongo-csharp-driver"
version = "v2.26.0"

[[assets.sources.repository.targets]]
source = "tests/MongoDB.Driver.Examples/Aws/AwsLambdaExamples.cs"
output = "drivers-examples/AwsLambdaExamples.cs"

[[assets.sources.repository]]
repo = "mongodb/mongo-go-driver"
version = "v1.15.1"
targets = [
    {source = "examples/_example_aws_lambda_handler.go", output = "drivers-examples/_example_aws_lambda_handler.go"}
]

[[assets.sources.repository]]
repo = "mongodb/mongo-java-driver"

[[assets.sources.repository.targets]]
source = "driver-sync/src/examples/documentation/ExampleAwsLambdaHandler.java"
output = "drivers-examples/ExampleAwsLambdaHandler.java"

[[assets.sources.repository]]
repo = "mongodb/node-mongodb-native"
version = "v6.7.0"

[[assets.sources.repository.targets]]
source = "test/integration/node-specific/examples/aws_handler.js"
output = "drivers-examples/aws_handler.js"

[[assets.sources.repository.targets]]
source = "test/integration/node-specific/examples/handler.js"
output = "drivers-examples/handler.js"

[[assets.sources.repository]]
repo = "mongodb/mongo-python-driver"
version = "4.7.3"
targets = [
    { source = "test/auth_aws/test_auth_aws.py", output = "drivers-examples/test_auth_aws.py" },
]

[[assets.sources.repository]]
repo = "mongodb/mongo-ruby-driver"
version = "v2.20.0"

[[assets.sources.repository.targets]]
source = "spec/integration/aws_lambda_examples_spec.rb"
output = "drivers-examples/aws_lambda_examples_spec.rb"

[[assets.sources.repository]]
repo = "mongodb/atlas-sdk-go"

[[assets.sources.repository.targets]]
source = "docs/doc_1_concepts.md"
output = "sdk/go/markdown/concepts.txt"

[[assets.sources.repository.targets]]
source = "docs/doc_2_error_handling.md"
output = "sdk/go/markdown/error_handling.txt"

[[assets.sources.repository.targets]]
source = "docs/doc_3_migration.md"
output = "sdk/go/markdown/migration.txt"

[[assets.sources.repository.targets]]
source = "docs/doc_4_authentication.md"
output = "sdk/go/markdown/authentication.txt"

[[assets.sources.repository.targets]]
source = "docs/doc_5_best_practices.md"
output = "sdk/go/markdown/best_practices.txt"

[[assets.sources.repository]]
repo = "10gen/mongosql-rs"

[[assets.sources.repository.targets]]
source = "errors.md"
output = "mongosql/markdown/errors.txt"