# The items in the ``builders`` list are the name of Sphinx builders
# supported by ``sphinx-build``.
#
# The ``prerequsites`` list stores all targets that must build before
# sphinx can begin.
#
# The ``generated-source`` list stores all the targets that generate rst.

prerequisites:
  - setup
  - generate-source
generated-source:
  - tables
  - api
  - toc
  - releases
  - generate-manpages
  - intersphinx
  - images
  - composites
### --- ####
root-base:
  languages: ['es', 'fr', 'ja', 'it', 'zh']
web-base:
  inherit: root-base
  tags:
    - web
print-base:
  inherit: root-base
  tags:
    - print
### --- ####
dirhtml:
  builder: dirhtml
  inherit: web-base
html:
  builder: html
  inherit: web-base
html-python:
  builder: html
  inherit: web-base
  tags:
    - python
html-mongo:
  builder: html
  inherit: web-base
  tags:
    - mongo
latex:
  builder: latex
  inherit: print-base
epub:
  builder: epub
  inherit: print-base
singlehtml:
  builder: singlehtml
  inherit: root-base
  tags:
    - web
man:
  builder: man
  inherit: root-base
  tags:
    - manpage
gettext:
  builder: gettext
  tags:
    - print
    - web
    - manpage
linkcheck:
  builder: linkcheck
  inherit: root-base
  tags:
    - web
texinfo:
  builder: texinfo
  inherit: root-base
  tags:
    - print
...