ref: custom-zone-mapping-desc
content: |
  
  *Type*: array

  *Required*

  List that contains :doc:`Global {+Cluster+} </global-clusters>`
  parameters that map zones to geographic regions. For a full list of
  available parameters, see the |service| :oas-atlas-tag:`Global
  {+Clusters+} API </Global-Clusters>`.

---
ref: custom-zone-mapping-location-desc
content: |

  *Type*: string

  *Required*

  Code that represents a location that maps to a zone in your :doc:`Global
  {+Cluster+} </global-clusters>`.

---
ref: custom-zone-mapping-zone-desc
content: |

   *Type*: string

   *Required*

   Human-readable label that identifies the zone in your :doc:`Global
   {+Cluster+} </global-clusters>`.

---
ref: managed-namespaces-desc
content: |
  
  *Type*: array

  *Required*

  List that contains information to create a managed namespace in a
  specified :doc:`Global {+Cluster+} </global-clusters>` to create. For
  a full list of available parameters, see the |service|
  :oas-atlas-tag:`Global {+Clusters+} API
  </Global-Clusters>`.

---
ref: managed-namespaces-collection-desc
content: |

  *Type*: string

  *Required*

  Human-readable label of the collection to manage in this :doc:`Global
  {+Cluster+} </global-clusters>`.

---
ref: managed-namespaces-db-desc
content: |

  *Type*: string

  *Required*

  Human-readable label of the database to manage in this :doc:`Global
  {+Cluster+} </global-clusters>`.

---
ref: managed-namespaces-is-custom-shard-key-hashed-desc
content: |

  *Type*: boolean

  *Optional*

  Flag that indicates whether to hash the custom shard key for
  the specified collection. This parameter defaults to ``false``.

  - Set to ``true`` to enable a custom shard key for the collection.
  - Set to ``false`` to disable a custom shard key for the collection.
    If diabled, MongoDB uses :manual:`ranged sharding </core/ranged-sharding/>`.

  To learn more, see :manual:`Hashed Shard Keys </reference/method/sh.shardCollection/#hashed-shard-keys>`.

---
ref: managed-namespaces-is-custom-shard-key-unique-desc
content: |

  *Type*: boolean

  *Optional*

  Flag that indicates whether the custom shard key for the specified
  collection is unique. This parameter defaults to ``false``.

  - Set to ``true`` to enable a unique custom shard key for the collection.
  - Set to ``false`` to disable a unique custom shard key for the collection.

---
ref: managed-namespaces-num-initial-chunks-desc
content: |

  *Type*: integer

  *Optional*

  Minimum number of chunks to initially create when sharding an empty
  collection with a :manual:`hashed shard key </core/hashed-sharding/>`.
   
  To learn more, see :ref:`shard-global-collection`.

---
ref: managed-namespaces-presplit-hashed-zones-desc
content: |

  *Type*: boolean

  *Optional*

  Flag that indicates whether MongoDB Cloud should create and
  distribute initial chunks for an empty or non-existing collection.
  This parameter defaults to ``false``.

  - Set to ``true`` to have MongoDB Cloud create and distribute initial chunks for an empty or non-existing collection.
  - Set to ``false`` to not have MongoDB Cloud create and distribute initial chunks for an empty or non-existing collection..

...
