name = "kotlin-sync"
title = "Kotlin Sync Driver"
eol = true

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/drivers/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/objects.inv",
              ]

toc_landing_pages = [
    "/read",
    "/indexes",
    "work-with-indexes",
    "/data-formats",
    "/aggregation"
]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-long = "MongoDB Kotlin Sync Driver"
driver-short = "Kotlin Sync driver"
language = "Kotlin"
version-number = "5.0"
full-version = "{+version-number+}.0"
version = "v{+version-number+}"
mdb-server = "MongoDB Server"
stable-api = "Stable API"
api = "https://mongodb.github.io/mongo-java-driver/{+version-number+}/apidocs/mongodb-driver-kotlin-sync"
java-api = "https://mongodb.github.io/mongo-java-driver/{+version-number+}"
core-api = "{+java-api+}/apidocs/mongodb-driver-core/"
kotlin-docs = "https://kotlinlang.org"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <https://www.mongodb.com/docs/languages/kotlin/kotlin-sync-driver/current/>`__ to learn how to `upgrade your version of the Kotlin Sync driver <https://www.mongodb.com/docs/languages/kotlin/kotlin-sync-driver/current/reference/upgrade/>`__.\
    """
