[build]
publish = "dist"
base = "content/pymongo-arrow-driver"

[build.environment]
REPO_NAME = "docs-pymongo-arrow"
SECRETS_SCAN_ENABLED = "false"
MUT_COMMANDS_ENABLED = "false"


[context.production.environment]
ENV = "dotcomprd"

[context.preprd.environment]
ENV = "dotcomstg"

[context.deploy-preview.environment]
ENV = "prd"

[context.branch-deploy.environment]
ENV = "prd"

[context.preview-server.environment]
ENV = "prd"

[context.dev.environment]
ENV = "stg"


### OFFLINE REDIRECTS
### ALIAS REDIRECTS
### PAGE-SPECIFIC REDIRECTS
### WILDCARD REDIRECTS
### CATCH ALLS
## redirects any pages not at any of the active versions to current (makes eols technically unnecessary)


### ALIAS REDIRECTS
[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/master/*"
to = "/docs/languages/python/pymongo-arrow-driver/upcoming/:splat"

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/v1.10/*"
to = "/docs/languages/python/pymongo-arrow-driver/current/:splat"
status = 302


### PAGE-LEVEL REDIRECTS (none)


### WILDCARD REDIRECTS
[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/:version/quick-start/"
to = "/docs/languages/python/pymongo-arrow-driver/:version/get-started/"

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/:version/installation/"
to = "/docs/languages/python/pymongo-arrow-driver/:version/get-started/"

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/:version/comparison/"
to = "/docs/languages/python/pymongo-arrow-driver/:version/reference/comparison/"

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/:version/previous-versions/"
to = "/docs/languages/python/pymongo-arrow-driver/:version/reference/previous-versions/"

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/:version/whats-new/"
to = "/docs/languages/python/pymongo-arrow-driver/:version/reference/release-notes/"

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/:version/faq/"
to = "/docs/languages/python/pymongo-arrow-driver/:version/"

#Online versions: dict_keys(['upcoming', 'current', 'v1.9', 'v1.8', 'v1.7', 'v1.6', 'v1.5', 'v1.4', 'v1.3'])

### CATCH ALLS (add slug to paths without slug)
[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/upcoming/*"
to = "/docs/languages/python/pymongo-arrow-driver/upcoming/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/current/*"
to = "/docs/languages/python/pymongo-arrow-driver/current/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/v1.9/*"
to = "/docs/languages/python/pymongo-arrow-driver/v1.9/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/v1.8/*"
to = "/docs/languages/python/pymongo-arrow-driver/v1.8/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/v1.7/*"
to = "/docs/languages/python/pymongo-arrow-driver/v1.7/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/v1.6/*"
to = "/docs/languages/python/pymongo-arrow-driver/v1.6/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/v1.5/*"
to = "/docs/languages/python/pymongo-arrow-driver/v1.5/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/v1.4/*"
to = "/docs/languages/python/pymongo-arrow-driver/v1.4/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/v1.3/*"
to = "/docs/languages/python/pymongo-arrow-driver/v1.3/:splat"
status = 200

[[redirects]]
from = "/docs/languages/python/pymongo-arrow-driver/*"
to = "/docs/languages/python/pymongo-arrow-driver/current/:splat"
