[build]
    publish = "dist"
    base = "content/kafka-connector"

[build.environment]
    REPO_NAME = "docs-kafka-connector"
    SECRETS_SCAN_ENABLED = "false"
    OFFLINE_SNOOTY_ENABLED = "false"
    SEARCH_MANIFEST_ENABLED = "false"
    MUT_COMMANDS_ENABLED = "false"

[context.production.environment]
    ENV = "dotcomprd"

[context.preprd.environment]
    ENV = "dotcomstg"

[context.deploy-preview.environment]
    ENV = "prd"

[context.branch-deploy.environment]
    ENV = "prd"

[context.preview-server.environment]
    ENV = "prd"

[context.dev.environment]
    ENV = "stg"

### EOL REDIRECTS
### ALIAS REDIRECTS
### WILDCARD REDIRECTS
### PAGE-SPECIFIC REDIRECTS (divided into subsections by version, if applicable)(not applicable for kafka)
### CATCH ALLS
 ##redirects any pages not at any of the active versions to current (makes eol's technically unecessary)



### EOL REDIRECTS
# [v1.0, v1.1, v1.2, v1.3, v1.4, v1.5, v1.6, v1.7, v1.8, v1.9, v1.10, v1.11] 

[[redirects]]
from = "/docs/kafka-connector/v1.0/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.1/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.2/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.3/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.4/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.5/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.6/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.7/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.8/*"
to = "/docs/kafka-connector/current/:splat"
 
[[redirects]]
from = "/docs/kafka-connector/v1.9/*"
to = "/docs/kafka-connector/current/:splat"

[[redirects]]
from = "/docs/kafka-connector/v1.10/*"
to = "/docs/kafka-connector/current/:splat"

[[redirects]]
from = "/docs/kafka-connector/v1.11/*"
to = "/docs/kafka-connector/current/:splat"

### ALIAS REDIRECTS
[[redirects]]
from = "/docs/kafka-connector/v1.15/*"
to = "/docs/kafka-connector/current/:splat"

[[redirects]]
from = "/docs/kafka-connector/master/*"
to = "/docs/kafka-connector/upcoming/:splat"

### WILDCARD REDIRECTS
#14
[[redirects]] 
from = "/docs/kafka-connector/:version/fundamentals/post-processors/"
to = "/docs/kafka-connector/:version/sink-connector/fundamentals/post-processors/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-compatibility/"
to = "/docs/kafka-connector/:version/compatibility/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-configure-ssl/"
to = "/docs/kafka-connector/:version/security-and-authentication/tls-and-x509/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-connect-migration/"
to = "/docs/kafka-connector/:version/migrate-from-kafka-connect-mongodb/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-connection-mongodb/"
to = "/docs/kafka-connector/:version/introduction/connect/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-docker-example/"
to = "/docs/kafka-connector/:version/quick-start/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-installation/"
to = "/docs/kafka-connector/:version/introduction/install/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-sink-cdc/"
to = "/docs/kafka-connector/:version/sink-connector/fundamentals/change-data-capture/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-sink-data-formats/"
to = "/docs/kafka-connector/:version/introduction/data-formats/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-sink-postprocessors/"
to = "/docs/kafka-connector/:version/sink-connector/fundamentals/post-processors/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-sink-properties/"
to = "/docs/kafka-connector/:version/sink-connector/configuration-properties/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-sink-time-series-example/"
to = "/docs/kafka-connector/:version/tutorials/migrate-time-series/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-sink/"
to = "/docs/kafka-connector/:version/sink-connector/"

[[redirects]] 
from = "/docs/kafka-connector/:version/kafka-source/"
to = "/docs/kafka-connector/:version/source-connector/"


### CATCH ALLS 
#ensure we don't redirect to current if the path already includes a slug
[[redirects]]
from = "/docs/kafka-connector/v1.12/*"
to = "/docs/kafka-connector/v1.12/:splat"
status = 200
 
[[redirects]]
from = "/docs/kafka-connector/v1.13/*"
to = "/docs/kafka-connector/v1.13/:splat"
status = 200
 
[[redirects]]
from = "/docs/kafka-connector/v1.14/*"
to = "/docs/kafka-connector/v1.14/:splat"
status = 200
 
[[redirects]]
from = "/docs/kafka-connector/current/*"
to = "/docs/kafka-connector/current/:splat"
status = 200
 
[[redirects]]
from = "/docs/kafka-connector/upcoming/*"
to = "/docs/kafka-connector/upcoming/:splat"
status = 200
 
#add 'current' slug to paths missing it
[[redirects]]
from = "/docs/kafka-connector/*"
to = "/docs/kafka-connector/current/:splat"