## Sample Netlify toml file for new monorepo projects

# 1. Create a netlify.toml file at the root of your new project subdirectory
# 2. Copy the contents of this file into new netlify.toml file. 
# 3. Replace the "BASE" and "REPO_NAME" vars with the appropriate values 

[build]
    publish = "dist"
        base = "content/kotlin-sync"

[build.environment]
    REPO_NAME = "docs-kotlin-sync"
    SECRETS_SCAN_ENABLED = "false"
    MUT_COMMANDS_ENABLED = "false"

[context.production.environment]
    ENV = "dotcomprd"

[context.preprd.environment]
    ENV = "dotcomstg"

[context.deploy-preview.environment]
    ENV = "prd"

[context.branch-deploy.environment]
    ENV = "prd"

[context.preview-server.environment]
    ENV = "prd"

[context.dev.environment]
    ENV = "stg"


### EOL REDIRECTS
### ALIAS REDIRECTS
### WILDCARD REDIRECTS
### PAGE-SPECIFIC REDIRECTS (divided into subsections by version, if applicable)
### CATCH ALLS
 ##redirects any pages not at any of the active versions to current (makes eol's technically unecessary)





### EOL REDIRECTS
eol-redirects: only applicable for versioned projects. should only be used for offline versions
eol redirects redirect from an eol'ed version of a project to the `current` (or in some cases, `upcoming` or `manual`) version
utilize a wildcard (asterisk/:splat pairing) to preserve the path when redirecting
ex: 
[[redirects]] 
from = "/docs/v2.2/*"
to = "/docs/manual/:splat"
[[redirects]]
from = "/docs/atlas/cli/v1.9/*"
to = "/docs/atlas/cli/current/:splat"

### ALIAS REDIRECTS
Alias redirects:  only applicable for versioned projects 
redirects from a version's alias to the main slug of a given version
utilize a wildcard (asterisk/:splat pairing) to preserve the path when redirecting
may also be used for redirecting away from old slugs that are no longer use (ex 'master')
Most times we'll want to add a 302 status code for these if the redirect will change when new versions are released
this indicates to google that it's a temporary redirect
ex:
[[redirects]]
from = "/docs/kafka-connector/v1.15/*"
to = "/docs/kafka-connector/current/:splat"
status = 302

[[redirects]]
from = "/docs/kafka-connector/master/*"
to = "/docs/kafka-connector/upcoming/:splat"


### WILDCARD REDIRECTS
Wildcard redirects: redirects that apply to every version using a placeholder
and/or redirects that apply to a number of paths 
ex: 
[[redirects]] 
from = "/docs/:version/4.2-compatibility/"
to = "/docs/:version/"

[[redirects]] 
from = "/docs/:version/administration/backup/"
to = "/docs/:version/core/backups/"

### PAGE-SPECIFIC REDIRECTS
Page-specific redirects (divided into subsections by version, if applicable)
Redirects from one specified path to another specified path


### CATCH ALLS (used for versioned sites)
1. redirects any pages not at any of the active versions to current 
2. redirects any page that would otherwise eol to the homepage of that specific version

