groups:
  ## A mapping of top level components presented on the changelog
  ## page, to the components in Jira that populate that group. Maps
  ## group names to lists of components.

  "Security":
    - Security
    - Queryable Encryption
    - Field Level Encryption
  "Sharding":
    - Sharding
  "Replication":
    - Replication
  "Query":
    - Querying
    - Query Execution
    - Query Language
    - Query Planning
    - Indexing
    - Index Maintenance
    - Geo
    - Text Search
  "Write Operations":
    - Write Ops
  "Aggregation":
    - Aggregation Framework
    - MapReduce
  "JavaScript":
    - JavaScript
  "WiredTiger":
    - WiredTiger
  "MMAP":
    - MMAPv1
  "Storage":
    - Storage
  "Catalog":
    - Catalog
  "TTL":
    - TTL
  "GridFS":
    - GridFS
  "Operations":
    - Operations
    - Admin
    - Diagnostics
    - Logging
    - Shell
    - Usability
    - HTTP Console
    - Client-side Field-level Encryption
  "Build and Packaging":
    - Build
    - Build/compile
    - Packaging
    - Mobile
    - Change streams
  "Internals":
    - Testing
    - Python tests
    - Testing Infrastructure
    - Stability
    - Performance
    - Portability
    - Networking
    - Internal Code
    - Internal Client
    - Concurrency
    - IDL
    - Upgrade/Downgrade
    - go-openssl
    - Cache and eviction
    - Backup
    - Checkpoints
    - Documentation
  "Tools":
    - Tools
    - All Tools
    - bsondump
    - mongodump
    - mongoexport
    - mongofiles
    - mongoimport
    - mongooplog
    - mongorestore
    - mongosniff
    - mongostat
    - mongotop
    - mongoreplay
    - llmgo

ordering:
  # Defines an order of groups. Issues with multiple components use
  # the first component defined in the ordering. Issues without
  # components use the last element in the ordering.

  - Security
  - Sharding
  - Replication
  - Query
  - Write Operations
  - Aggregation
  - Catalog
  - JavaScript
  - WiredTiger
  - MMAP
  - Storage
  - TTL
  - GridFS
  - Operations
  - Build and Packaging
  - Tools
  - Internals

nesting:
  # Define nesting relationships between groups above. Map group names
  # to lists of group names. Generally nested components should appear
  # before their parent heading in the ordering, so that
  # double-categorized issues get put in the more specific category.

  Storage:
    - WiredTiger
    - MMAP
...
