name = "voyageai"
title = "Voyage AI by MongoDB"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

toc_landing_pages = [
  "/api-and-clients",
  "/management/api-keys",
  "/management/billing",
  "/management/monitor-usage",
  "/management/organization-project-access",
  "/management/rate-limits",
  "/api-reference/overview",
  "/api-reference/error-codes",
  "/models",
  "/models/contextualized-chunk-embeddings",
  "/models/multimodal-embeddings",
  "/models/rerankers",
  "/models/text-embeddings",
  "/quickstart",
  "/tutorials/rag",
  "/tutorials/semantic-search"
]

[constants]
atlas-admin-api = "Atlas Administration API"
atlas-ui = "Atlas UI"
llm = "large language model"
model-api-key = "model API key"
model-api-keys = "model API keys"
rag = "RAG"
service = "Atlas"
voyageai = "Voyage AI"
voyage-full = "Voyage AI by MongoDB"
voyage = "Voyage"
voyage-api = "Embedding and Reranking API"
voyage-api-full = "Atlas Embedding and Reranking API"

[substitutions]
api = ":abbr:`API (Application Programming Interface)`"
service = "Atlas"
service-full = "MongoDB Atlas"

[[composables]]
id = "client"
title = "Language"
default = "python"
options = [
  {id = "python", title = "Python"},
  {id = "curl", title = "cURL"},
  {id = "typescript", title = "TypeScript"},
  {id = "go", title = "Go"},
  {id = "java", title = "Java"},
]

[[composables]]
id = "client-curl-default"
title = "Language"
default = "python"
options = [
  {id = "python", title = "Python"},
  {id = "curl", title = "cURL"},
  {id = "typescript", title = "TypeScript"},
  {id = "go", title = "Go"},
  {id = "java", title = "Java"},
]

[[composables]]
id = "llm-provider"
title = "LLM Provider"
default = "anthropic"
options = [
  {id = "anthropic", title = "Anthropic"},
  {id = "openai", title = "OpenAI"},
]

[[composables]]
id = "language-no-interface"
title = "Language"
default = "python"
options = [
  {id = "csharp", title = "C#"},
  {id = "go", title = "Go"},
  {id = "nodejs", title = "Node.js"},
  {id = "typescript", title = "TypeScript"},
  {id = "python", title = "Python"},
]

[[composables]]
id = "vector-storage"
title = "Vector Storage"
default = "mongodb"
options = [
  {id = "mongodb", title = "MongoDB"},
  {id = "in-memory", title = "In Memory"},
]

[[banners]]
# Voyage AI site-wide preview banner
targets = [
  "*"
]
variant = "warning"
value = """\
The Embedding and Reranking API is in `Preview <https://www.mongodb.com/docs/preview-features/>`__. The feature and the corresponding documentation might change at any time during the preview period.
"""
