# The items in the ``sphinx`` list are the name of Sphinx builders
# supported by ``sphinx-build``.

- 'dirhtml'
- 'latex'
- 'epub'
- 'html'
- 'gettext'
- 'man'
- 'json'
- 'changes'
- 'doctest'
- 'linkcheck'
- 'texinfo'
...
