# Each YAML document has the following schema:
#
# from: "the path to the redirected URL"
# to: "the path to the new location for the resource"
# type: "currently this script only supports 'redirect', and
#        ignores all documents with another type."
# code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
# outputs: "a list of branches/paths as follows:"
#
# - 'all': generates redirects for all published branches, but *not* 'manual'. But giza will take care of manual as part of integration.yaml logic in redirects.py
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################
### Giza requires this file, even if no redirects
### More as a safety -- in case, we remove redirects during deploys
from: '/'
to: '/master'
type: 'redirect'
code: 301
outputs:
  - {'/': 'https://docs.mongodb.com/ruby-driver'}
---

from: '/aggregation-framework'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/replica-sets'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/read-preference'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/write-concern'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/bulk-write-operations'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/authentication-examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/gridfs'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/tailable-cursors'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/web-examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/faq'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/style-guide'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/credits'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x'
---
from: '/bson'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/reference/additional-resources'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/reference/driver-compatibility'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/bson-v3'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/bson-v4'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-callbacks'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-documents'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-indexes'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-installation'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-nested-attributes'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-persistence'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-queries'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-rails'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-relations'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-upgrade'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/mongoid-validation'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/tutorial/ruby-mongoid-tutorial'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'v1.x'
---
from: '/installation'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorials'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-admin-tasks'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-create-client'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-indexing'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-aggregation'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-crud-operations'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-projections'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-bulk-operations'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-geospatial-search'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-text-search'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-collection-tasks'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-driver-gridfs'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
---
from: '/tutorial/ruby-mongoid-tutorial'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0'
...
