# Each YAML document has the following schema:
#
# from: "the path to the redirected URL"
# to: "the path to the new location for the resource"
# type: "currently this script only supports 'redirect', and
#        ignores all documents with another type."
# code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
# outputs: "a list of branches/paths as follows:"
#
# - 'all': generates redirects for all published branches, but *not* 'manual'. But giza will take care of manual as part of integration.yaml logic in redirects.py
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################
### Giza requires this file, even if no redirects
### More as a safety -- in case, we remove redirects during deploys
from: '/'
to: '/master'
type: 'redirect'
code: 301
outputs:
  - {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---

from: '/aggregation-framework'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/replica-sets'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/read-preference'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/write-concern'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/bulk-write-operations'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/authentication-examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/gridfs'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tailable-cursors'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/web-examples'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/faq'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/style-guide'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/credits'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
### for v1.x, have to do after-v1.x since the construct with : {x:y} only seems to take before/after
from: '/bson-tutorials'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/contribute'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/reference/additional-resources'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/reference/driver-compatibility'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/bson-v3'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/bson-v4'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'after-v1.x': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/installation'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/ruby-driver-tutorials'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-admin-tasks'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-create-client'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-indexing'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-aggregation'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-crud-operations'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-projections'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-bulk-operations'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-geospatial-search'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-text-search'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-collection-tasks'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/tutorials/ruby-driver-gridfs'
to: '/quick-start'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.0': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
---
from: '/whats-new'
to: '/'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.3': {'/ruby-driver': 'https://docs.mongodb.com/ruby-driver'}
...
