from: '/connect'
to: '/connect-to-cluster/'
type: 'redirect'
code: 301
outputs:
  - {'': 'https://docs.atlas.mongodb.com'}

## NOTE -- can later on change the outputs to 'atlas' only
---
from: '/manage-alerts'
to: '/configure-alerts/'
type: 'redirect'
code: 301
outputs:
  - {'': 'https://docs.atlas.mongodb.com'}
---
from: '/tutorial/scale-cluster'
to: '/scale-cluster/'
type: 'redirect'
code: 301
outputs:
  - {'': 'https://docs.atlas.mongodb.com'}
---
from: '/tutorial/restore-replica-set'
to: '/restore-cluster/'
type: 'redirect'
code: 301
outputs:
  - {'': 'https://docs.atlas.mongodb.com'}
---
from: '/reference/api/users'
to: '/reference/api-resources'
type: 'redirect'
code: 301
outputs:
  - {'': 'https://docs.atlas.mongodb.com'}
---
from: '/group-settings'
to: '/tutorial/manage-project-settings'
type: 'redirect'
code: 301
outputs:
  - {'': 'https://docs.atlas.mongodb.com'}
---
from: '/tutorial/transition-free-tier-to-paid'
to: '/scale-cluster'
type: 'redirect'
code: 301
outputs:
  - {'': 'https://docs.atlas.mongodb.com'}
...
