name: opsmanager-large
alt: "A highly available deployment uses horizontal scaling of the application database and backup blockstore database, as well as multiple backup daemons."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
---
name: opsmanager-medium
alt: "A typical deployment uses replica sets for the application database and backup blockstore database."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
---
name: opsmanager-test
alt: "The minimal deployment is suitable for development or testing, and hosts the application and backup daemon, as well as associated databases on a single server."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
---
name: opsmanager-network-diagram
alt: "Network diagram showing flows of data between Ops Manager's components."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/opsmanager-network-diagram-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: http-pull-point-in-time-restore
alt: "Describes internal data flows of HTTP Pull point-in-time restore process."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/http-pull-point-in-time-restore-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: http-pull-snapshot-restore
alt: "Describes internal data flows of HTTP Pull snapshot restore process."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/http-pull-snapshot-restore-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: scp-point-in-time-archive
alt: "Describes internal data flows of point-in-time restore process with SCP archive delivery."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/scp-point-in-time-archive-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: scp-point-in-time-individual-files
alt: "Describes internal data flows of point-in-time restore process with SCP individual files delivery."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/scp-point-in-time-individual-files-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: scp-snapshot-archive
alt: "Describes internal data flows of snapshot restore process with SCP archive delivery."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/scp-snapshot-archive-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: scp-snapshot-individual-files
alt: "Describes internal data flows of snapshot restore process with SCP individual files delivery."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/scp-snapshot-individual-files-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: backup-flow
alt: "Diagram showing the flow of data for Ops Manager's backup components when using snapshot storage."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
---
name: backup-flow-blockstore
alt: "Diagram showing the flow of data for Ops Manager's backup components when using a Backup Blockstore for snapshot storage."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/backup-flow-blockstore-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: backup-flow-filesystem-storage
alt: "Diagram showing the flow of data for Ops Manager's backup components when using a Backup Filesystem Store for snapshot storage."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 2100
  - type: web
    dpi: 72
    width: 700
    target: ../../_images/backup-flow-filesystem-storage-fullsize.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 2100
---
name: dual-data-center-backup
alt: "Diagram showing the flow of data for Ops Manager's backup components when using two Data Centers."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 1800
  - type: web
    dpi: 72
    width: 633
    target: ../../_images/dual-data-center-backup.png
  - type: target
    tag: fullsize
    dpi: 96
    width: 1800
---
name: network-ports
alt: "Diagram showing the connections between Ops Manager's components."
output:
  - type: print
    tag: 'print'
    dpi: 300
    width: 1800
  - type: web
    dpi: 72
    width: 684
  - type: target
    tag: fullsize
    dpi: 96
    width: 1800

...
