base:
  links:
    - { 'hosted/current': 'v1.5' }
    - { 'hosted/upcoming': '{{current_branch}}' }
  targets:
    - latex-hosted
    - json-hosted
    - singlehtml-hosted
    - dirhtml-hosted
    - html-hosted
    - htaccess-hosted
    - latex-saas
    - json-saas
    - singlehtml-saas
    - dirhtml-saas
    - html-saas
    - htaccess-saas
  doc-root: []
fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
...