name: mongodb
url: http://docs.mongodb.org/manual/
path: mongodb.inv
---
name: pymongo
url: http://api.mongodb.org/python/current/
path: pymongo.inv
---
name: python
url: http://docs.python.org/2/
path: python2.inv
---
name: python2
url: http://docs.python.org/2/
path: python2.inv
---
name: python3
url: http://docs.python.org/3/
path: python3.inv
---
name: django
url: https://django.readthedocs.org/en/latest/
path: django.inv
---
# name: djangomongodbengine
# url: http://django-mongodb.org/
# path: djangomongodb.inv
# ---
name: djangotoolbox
url: http://djangotoolbox.readthedocs.org/en/latest/
path: djangotoolbox.inv
...
