name: mongodb
url: https://docs.mongodb.com/manual/
path: mongodb.inv
---
name: motor
url: https://motor.readthedocs.io/en/stable/
path: motor.inv
---
name: phplib
url: https://docs.mongodb.com/php-library/master/
path: phplib.inv
---
name: compass
url: https://docs.mongodb.com/compass/current/
path: objects.inv
---
name: clouddocs
url: https://docs.atlas.mongodb.com/
path: cloud-docs.inv
...
