# Weirdly, giza wants a non-empty list of two or more, so we have to include extraneous/unused one --hence the python
name: python
url: https://docs.python.org/2/
path: python2.inv
---
name: mongodb
url: https://www.mongodb.com/docs/manual/
path: mongodb.inv
...