name: mongodb
url: https://docs.mongodb.com/manual/
path: mongodb.inv
---
name: python
url: https://docs.python.org/2/
path: python2.inv
---
name: python2
url: https://docs.python.org/2/
path: python2.inv
---
name: python3
url: https://docs.python.org/3/
path: python3.inv
---
name: biconnector
url: https://docs.mongodb.com/bi-connector/current/
path: biconnector.inv
---
name: opsmanager
url: https://docs.opsmanager.mongodb.com/current/
path: objects.inv

...
