name: pymongo
url: https://api.mongodb.com/python/current/
path: pymongo.inv
---
name: motor
url: https://motor.readthedocs.io/en/stable/
path: motor.inv
---
name: phplib
url: https://docs.mongodb.com/php-library/master/
path: phplib.inv
---
name: clouddocs
url: https://docs.atlas.mongodb.com/
path: cloud-docs.inv
---
name: compassdocs
url: https://docs.mongodb.com/compass/current/
path: compass-docs.inv
---
name: databasetools
url: https://docs.mongodb.com/database-tools/
path: database-tools-docs.inv
...
