fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  links: 
    - { 'current': 'master' }
  targets:
    - html
    - dirhtml
  doc-root:
    - ''
    - '.htaccess'
  branch-root: null
...