name: python2
url: https://docs.python.org/2/
path: python2.inv
---
name: mongodb
url: https://docs.mongodb.com/manual/
path: mongodb.inv
---
name: ecosystem
url: https://docs.mongodb.com/ecosystem/
path: eco.inv
...
