# The build system only reads this if in the master branch. In other
# branches, we check out the file from the master branch.

version:
  published:
    - '2.6'
    - '2.4'
    - '2.2'
  stable: '2.6'
  upcoming: null
git:
  branches:
    manual: 'master'
    published:
      - 'master'
      - 'v2.4'
      - 'v2.2'
      # the branches/published list **must** be ordered from most to
      # least recent release.
...