# The build system only reads this if in the master branch. In other
# branches, we check out the file from the master branch.

version:
  published:
    - '1.6'
    - '1.5'
    - '1.4'
    - '1.3'
    - '1.2'
    - '1.1'
  stable: '1.5'
  upcoming: '1.6'
git:
  branches:
    manual: 'v1.5'
    published:
      - 'master'
      - 'v1.5'
      - 'v1.4'
      - 'v1.3'
      - 'v1.2'
      - 'v1.1'
      # the branches/published list **must** be ordered from most to
      # least recent release.
...