from: '/release-notes/2.8'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/2.8'
to: '/release-notes/3.0'
type: 'redirect'
code: 301
outputs:
  - {'manual': "v3.0" }
---
from: '/release-notes/2.8-upgrade'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
  - 'manual'
---
from: '/release-notes/2.8-downgrade'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
  - 'manual'
---
from: '/release-notes/2.8-compatibility'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
  - 'manual'
---
from: '/release-notes/2.8-changes'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
  - 'manual'
---
from: '/release-notes/2.8-general-improvements'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
  - 'manual'
---
from: '/tutorial/install-mongodb-on-amazon'
to: '/installation'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
  - 'manual'
---
from: '/tutorial/install-mongodb-on-suse'
to: '/installation'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
  - 'manual'
---
from: '/release-notes/2.8'
to: '/release-notes/3.0'
type: 'redirect'
code: 303
outputs:
  - {'master': 'v3.0'}
  - 'after-v2.6'
---
from: '/release-notes/2.8-upgrade'
to: '/release-notes/3.0-upgrade'
type: 'redirect'
code: 303
outputs:
  - {'master': 'v3.0'}
  - 'after-v2.6'
---
from: '/release-notes/2.8-downgrade'
to: '/release-notes/3.0-downgrade'
type: 'redirect'
code: 303
outputs:
  - {'master': 'v3.0'}
  - 'after-v2.6'
---
from: '/release-notes/2.8-compatibility'
to: '/release-notes/3.0-compatibility'
type: 'redirect'
code: 303
outputs:
  - {'master': 'v3.0'}
  - 'after-v2.6'
---
from: '/release-notes/2.8-general-improvements'
to: '/release-notes/3.0'
type: 'redirect'
code: 303
outputs:
  - {'master': 'v3.0'}
  - 'after-v2.6'
---
from: '/release-notes/2.8-changes'
to: '/release-notes/3.0-changes'
type: 'redirect'
code: 303
outputs:
  - {'master': 'v3.0'}
  - 'after-v2.6'
---
from: '/release-notes/3.0'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/3.0-upgrade'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/3.0-downgrade'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/3.0-compatibility'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/3.0-general-improvements'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/3.0-general-improvements'
to: '/release-notes/3.0'
type: 'redirect'
code: 303
outputs:
  - {'master': 'v3.0'}
  - 'after-v2.6'
---
from: '/release-notes/3.0-changes'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/3.0-scram'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/tutorial/install-mongodb-on-red-hat-centos-or-fedora-linux'
to: '/tutorial/install-mongodb-on-red-hat'
type: redirect
code: 301
outputs:
  - 'before-v2.4'
  - 'manual'
---
from: '/tutorial/tutorial/install-mongodb-enterprise-on-red-hat'
to: '/tutorial/install-mongodb-enterprise-on-red-hat'
type: redirect
code: 301
outputs:
  - 'before-v2.4'
  - 'manual'
---
from: '/'
to: '/'
type: 'redirect'
code: 303
outputs:
  - { "v2.8": "v3.0"}
...
