### KLUGE --  giza redirects.py logic for outputs is wonky
### treats '' and '/' for outputs differently in deciding what to 
### join to the from uri and to uri.  sigh.
### As a temporary stopgap, will use {'': '/'}
code: 303
edition: cloud
from: '/tutorial/manage-deployments-with-automation'
to: '/tutorial/add-servers'
type: redirect
outputs: 
   - {'': '/'}
---
code: 301
edition: classic
from: '/tutorial/nav/manage-hosts-classic'
to: '/tutorial/nav/manage-hosts'
type: redirect
outputs: 
   - {'': '/'}
---
code: 303
from: '/core/dashboards'
to: '/user-guide'
type: redirect
outputs: 
   - {'': '/'}
edition:
  - classic
  - cloud
---
code: 301
from: /tutorial/use-mms-public-api
outputs: 
   - {'': '/'}
to: /tutorial/enable-public-api
type: redirect
edition: cloud
---
code: 303
from: /reference/cluster-configuration-structure
outputs: 
   - {'': '/'}
to: /reference/cluster-configuration
type: redirect
edition: cloud
---
code: 303
from: /user-guide
outputs: 
   - {'': '/'}
to: /tutorial/nav/monitoring
type: redirect
edition:
  - cloud
  - classic
---
code: 303
from: /tutorial/nav/deploy
to: /administration
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 303
from: /tutorial/nav/security
to: /administration
type: redirect
outputs: 
   - {'': '/'}
edition:
  - classic
---
code: 303
from: /tutorial/register-user
to: /tutorial/manage-users
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 303
from: /tutorial/enable-backup-for-replica-set
to: /tutorial/enable-backup
type: redirect
outputs: 
   - {'': '/'}
edition:
  - classic
  - cloud
---
code: 303
from: /tutorial/enable-backup-for-sharded-cluster
to: /tutorial/enable-backup
type: redirect
outputs: 
   - {'': '/'}
edition:
  - classic
  - cloud
---
code: 303
from: /tutorial/nav/backup-use-activate
to: /tutorial/nav/backup-use
type: redirect
outputs: 
   - {'': '/'}
edition:
  - classic
  - cloud
---
code: 301
from: /concepts/backup-preparations
to: /core/backup-preaparations
type: redirect
outputs: 
   - {'': '/'}
edition:
  - classic
  - cloud
---
code: 301
from: /tutorial/nav/backup-use-restore
to: /tutorial/nav/backup-restore-deployments
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 301
from: /tutorial/stop-restart-disable-backup
to: /tutorial/stop-restart-terminate-backup
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 301
from: /tutorial/restore-select-delivery-format
to: /core/restore-overview
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 301
from: /tutorial/restore-from-snapshot
to: /tutorial/restore-replica-set
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 301
from: /tutorial/retrieve-snapshot-scp
to: /tutorial/restore-replica-set
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 303
from: /tutorial/restore-from-point-in-time-snapshot
to: /tutorial/restore-replica-set
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 301
from: /tutorial/edit-host-ssl-use
to: /tutorial/enable-ssl-for-a-group
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 301
from: /tutorial/enable-ssl-for-a-group
to: /tutorial/enable-ssl-for-a-deployment
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
  - classic
---
code: 303
from: /tutorial/nav/automation
to: /application
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 303
from: /tutorial/add-existing-host-to-automation
to: /tutorial/add-monitored-deployment-to-automation
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 303
from: /tutorial/add-existing-hardware
to: /tutorial/add-servers-automation
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 303
from: /tutorial/add-servers
to: /tutorial/nav/monitoring-and-manage
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/tutorial/nav/management
to: /tutorial/nav/manage-hosts
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
from: /tutorial/add-hosts-to-monitoring
to: /tutorial/add-existing-mongodb-processes
type: redirect
outputs: 
   - {'': '/'}
edition: cloud
---
code: 303
from: /tutorial/configure-block-size
to: /tutorial/nav/backup-use-operations
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/nav/management
to: /tutorial/nav/add-servers
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/configure-aws-hosts
to: /tutorial/provision-aws-servers
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/configure-aws-settings
to: /tutorial/configure-aws-integration
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/connect-to-aws-server-using-ssh
to: /tutorial/connect-to-cloud-server-using-ssh
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/nav/add-servers-through-aws-integration
to: /tutorial/nav/provision-aws-servers
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/provision-cloud-servers
to: /tutorial/provision-aws-servers
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/reactivate-hosts
to: /tutorial/nav/manage-hosts
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/remove-hosts
to: /tutorial/nav/manage-hosts
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/configure-cloud-server-settings
to: /tutorial/nav/provision-aws-servers
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /core/monitoring
to: /tutorial/view-diagnostics
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from:  /reference/host-statistics
to: /tutorial/view-diagnostics
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/manage-host-alerts
to: /tutorial/view-diagnostics
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/nav/monitoring-metrics
to: /tutorial/view-diagnostics
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/view-cluster-statistics
to: /tutorial/view-diagnostics
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /tutorial/view-replica-set-statistics
to: /tutorial/view-diagnostics
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: /core/settings
to: /tutorial/edit-your-user-account
type: redirect
outputs: 
  - {'': '/'}
edition:
  - cloud
---
code: 301
from: '/mms-manual.pdf'
to: '/'
type: redirect
outputs: 
   - {'': '/'}
edition: cloud
---
code: 301
from: /tutorial/nav/getting-started
to: /application
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: tutorial/configure-azure-integration
to: '/'
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: tutorial/nav/provision-azure-servers
to: '/'
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: tutorial/provision-azure-servers
to: '/'
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: tutorial/nav/provision-cloud-servers
to: '/tutorial/nav/add-servers'
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
---
code: 301
from: reference/api/nav/cloud-server-provisioning
to: '/reference/api/nav/automation'
type: redirect
outputs: 
   - {'': '/'}
edition:
  - cloud
...
