from: '/manual.tar.gz'
to: '/manual-master.tar.gz'
type: 'redirect'
code: 301
outputs:
  - 'master'
---
from: '/manual.tar.gz'
to: '/manual-v3.2.tar.gz'
type: 'redirect'
code: 301
outputs:
  - 'v3.2'
---
from: '/manual.tar.gz'
to: '/manual-v3.0.tar.gz'
type: 'redirect'
code: 301
outputs:
  - 'v3.0'
---
from: '/manual.tar.gz'
to: '/manual-v2.6.tar.gz'
type: 'redirect'
code: 301
outputs:
  - 'v2.6'
---
from: '/manual.tar.gz'
to: '/manual-v2.4.tar.gz'
type: 'redirect'
code: 301
outputs:
  - 'v2.4'
---
from: '/manual.tar.gz'
to: '/manual-v2.2.tar.gz'
type: 'redirect'
code: 301
outputs:
  - 'v2.2'
...
