from: "/reference/command/getoptime"
to: "/reference/command/nav-replication"
type: 'redirect'
code: 303
outputs:
  - 'after-v2.6'
  - 'master'
---
from: "/reference/command/closeAllDatabases"
to: "/reference/command/nav-administration"
type: 'redirect'
code: 303
outputs:
  - 'after-v2.6'
  - 'master'
---
from: '/reference/operator/aggregation/dateToString'
to: '/reference/operator/aggregation'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: /reference/method/db.addUser
to: /reference/method/db.createUser
type: 'redirect'
code: 303
outputs:
  - 'after-v2.6'
  - 'master'
---
from: '/reference/log-messages'
to: '/reference/configuration-options'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/reference/command/explain'
to: '/reference/method/cursor.explain'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: "/reference/command/replSetGetConfig"
to: "/reference/command/nav-replication"
type: 'redirect'
code: 303
outputs:
  - 'before-v2.6'
---
from: "/reference/command/repairCursor"
to: "/reference/command/nav-administration"
type: 'redirect'
code: 303
outputs:
  - 'before-v2.6'
---
from: '/reference/method/db.collection.explain'
to: '/reference/method/cursor.explain'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/reference/method/sh.removeTagRange'
to: '/reference/method/js-sharding'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/reference/method/db.getLogComponents'
to: '/reference/method'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/reference/method/db.setLogLevel'
to: '/reference/method'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/reference/explain-results'
to: '/reference/method/cursor.explain'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
...
