## The "edition" field controls the edition where the
## replacements are available. These replacements are available
## *both* in RST using |<name>| tokens and in generated content using
## {{<name>}} tokens.

edition: "onprem"
tokens:
  2fa: ":abbr:`2FA (two-factor authentication)`"
  a-application: "an Ops Manager Application" #use when you need to say a(n) ___
  a-mms: "an Ops Manager" #use when you need to say a(n) ___
  A-mms: "An Ops Manager" #use when you need to say a(n) ___
  admin-title-string: "Ops Manager"
  api-admin-backup-url: "``https://{OPSMANAGER-HOST}:{PORT}/api/public/v1.0/admin/backup``"
  api-url: "``https://{OPSMANAGER-HOST}:{PORT}/api/public/v1.0``"
  api: ":abbr:`API (Application Programming Interface)`"
  application-s: "Ops Manager Applications"
  application: "Ops Manager Application"
  aws: ":abbr:`AWS (Amazon Web Services)`"
  bic-full: ":bic:`MongoDB Connector for BI </>`"
  bic-short: ":bic:`BI Connector </>`"
  bson: ":abbr:`BSON (Binary Javascript Object Notation)`"
  certauth: "Certificate Authority"
  cidr: :abbr:`CIDR (Classless Inter-Domain Routing)`
  cifs: ":abbr:`CIFS (Common Internet File System)`"
  cloud: "MongoDB Cloud Manager"
  cloud-short: "Cloud Manager"
  csrs: ":abbr:`CSRS (Config Servers as Replica Sets)`"
  dn: ":abbr:`DN (Distinguished Name)`"
  dns: ":abbr:`DNS (Domain Name System)`"
  dns-srv: ":abbr:`DNS (Domain Name System)` :abbr:`SRV (Service)`"
  Epoch-time-ms: "Timestamp in the number of milliseconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
  epoch-time-ms: "timestamp in the number of milliseconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
  epoch-time: "Timestamp in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
  # epoch-time: "timestamp in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__',"
  Epoch-time: "Timestamp, in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
  html: ":abbr:`HTML (Hypertext Markup Language)`"
  faq: ":abbr:`FAQ (frequently asked questions)`"
  fcv: ":abbr:`FCV (Feature Compatibility Version)`"
  fcv-link: ":manual:`FCV </reference/command/setFeatureCompatibilityVersion>`"
  fqdn: ":abbr:`FQDN (fully qualified domain name)`"
  ftdc: ":abbr:`FTDC (full-time diagnostic data capture)`"
  gssapi: ":abbr:`GSSAPI (Generic Security Services Application Program Interface)`"
  hmac: ":abbr:`HMAC (hash-based message authentication code)`"
  http-service: "HTTP Service"
  http: :abbr:`HTTP (HyperText Transport Protocol)`
  https: :abbr:`HTTPS (Secure HyperText Transport Protocol)`
  iam: :abbr:`IAM (Identity and Access Management)`
  iana: ":abbr:`IANA (Internet Assigned Numbers Authority)`"
  idp: ":abbr:`IdP (Identity Provider)`"
  idps: ":abbr:`IdPs (Identity Providers)`"
  ietf: ":abbr:`IETF (Internet Engineering Task Force)`"
  index-page-title: "MongoDB Ops Manager"
  iops: :abbr:`IOPS (Input/Output Operations per Second)`
  ipaddr: :abbr:`IP (Internet Protocol)`
  ipv4: :abbr:`IPv4 (Internet Protocol version 4)`
  ipv6: :abbr:`IPv6 (Internet Protocol version 6)`
  iso3661: "`ISO 3661-1 <https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements>`__ country code"
  iso8601-duration: "Duration in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=851138376#Durations>`__ notation"
  iso8601-time: "Timestamp in :wikipedia:`ISO 8601 </ISO_8601?oldid=793821205>` date and time format"
  iso8601: "`ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=793821205>`__"
  iso: ":abbr:`ISO (International Organization for Standardization)`"
  jdk: ":abbr:`JDK (Java Development Kit)`"
  jedec: ":abbr:`JEDEC (Joint Electron Device Engineering Council Solid State Technology Association)`"
  jira: "`Jira <https://jira.mongodb.org>`__"
  json: ":abbr:`JSON (Javascript Object Notation)`"
  jvm: ":abbr:`JVM (Java Virtual Machine)`"
  k8s-configmap: "`ConfigMap <https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/>`__"
  k8s-configmaps: "`ConfigMaps <https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/>`__"
  k8s-crd: "`CustomResourceDefinition <https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/>`__"
  k8s-crds: "`CustomResourceDefinitions <https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/>`__"
  k8s-mdbrsc: "MongoDB Kubernetes resource"
  k8s-mdbrscs: "MongoDB Kubernetes resources"
  k8s-node: "`node <https://kubernetes.io/docs/concepts/architecture/nodes/>`__"
  k8s-nodes: "`nodes <https://kubernetes.io/docs/concepts/architecture/nodes/>`__"
  k8s-ns: "`namespace <https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/>`__"
  k8s-nss: "`namespaces <https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/>`__"
  k8s-obj: "`object <https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/>`__"
  k8s-objs: "`objects <https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/>`__"
  k8s-op-full: "MongoDB Enterprise Kubernetes Operator"
  k8s-op-short: "Kubernetes Operator"
  k8s-pod: "`pod <https://kubernetes.io/docs/concepts/workloads/pods/pod/>`__"
  k8s-pods: "`pods <https://kubernetes.io/docs/concepts/workloads/pods/pod/>`__"
  k8s-pv: "`Persistent Volume <https://kubernetes.io/docs/concepts/storage/persistent-volumes/>`__"
  k8s-pvc: "`Persistent Volume Claim <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims>`__"
  k8s-pvcs: "`Persistent Volume Claims <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims>`__"
  k8s-pvs: "`Persistent Volumes <https://kubernetes.io/docs/concepts/storage/persistent-volumes/>`__"
  k8s-rule: "`rule <https://kubernetes.io/docs/concepts/configuration/assign-pod-node/>`__"
  k8s-sc: "`StorageClass <https://kubernetes.io/docs/concepts/storage/storage-classes/>`__"
  k8s-secret: "`secret <https://kubernetes.io/docs/concepts/configuration/secret/>`__"
  k8s-secrets: "`secrets <https://kubernetes.io/docs/concepts/configuration/secret/>`__"
  k8s-statefulset: "`StatefulSet <https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/>`__"
  k8s-statefulsets: "`StatefulSets <https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/>`__"
  k8s: "Kubernetes"
  kdc: ":abbr:`KDC (Key Distribution Center)`"
  kmip: ":abbr:`KMIP (Key Management Interoperability)`"
  ldap: ":abbr:`LDAP (Lightweight Directory Access Protocol)`"
  ldaps: ":abbr:`LDAPS (Secure Lightweight Directory Access Protocol)`"
  mdb-support: "`MongoDB Support <https://support.mongodb.com>`__"
  mms-full: "MongoDB Ops Manager"
  mms: "Ops Manager"
  mms-register: ":mdbacct:`MongoDB Ops Manager registration page </register>`"
  mms-login: ":mdbacct:`MongoDB Ops Manager login page </login>`"
  mongo: ":binary:`~bin.mongo`"
  mongod: ":binary:`~bin.mongod`"
  mongos: ":binary:`~bin.mongos`"
  nas: ":abbr:`NAS (Network Attached Storage)`"
  nfs: ":abbr:`NFS (Network File System)`"
  onprem: "Ops Manager"
  pa: "Performance Advisor"
  pem: ":abbr:`PEM (Privacy-Enhanced Mail)`"
  pii: ":abbr:`PII (Personally identifiable information)`"
  piv: ":abbr:`PIV (personal identity verification)`"
  rdp: ":abbr:`RDP (Remote Desktop Protocol)`"
  rest: ":abbr:`REST (Representational State Transfer)`"
  restapi: ":abbr:`REST (Representational State Transfer)` :abbr:`API (Application Programming Interface)`"
  rhel: ":abbr:`RHEL (Red Hat Enterprise Linux)`"
  rpo: ":abbr:`RPO (recovery point objective)`"
  rto: ":abbr:`RTO (recovery time objective)`"
  s3: ":abbr:`S3 (Simple Storage Service)`"
  s: "Suite"
  san: ":abbr:`SAN (Storage Area Network)`"
  saml: ":abbr:`SAML (Security Assertion Markup Language)`"
  saml-sp: ":abbr:`SP (Service Provider)`"
  sasl: ":abbr:`SASL (Simple Authentication and Security Layer)`"
  sccc: ":abbr:`SCCC (Sync Cluster Connection Configuration)`"
  scp: ":abbr:`SCP (secure copy)`"
  service-short: "Atlas"
  service: "MongoDB Atlas"
  ses: ":abbr:`SES (Simple Email Service)`"
  sla: ":abbr:`SLA (Service Level Agreement)`"
  sms: ":abbr:`SMS (short message service)`"
  smtp: ":abbr:`SMTP (Simple Mail Transport Protocol)`"
  snmp: ":abbr:`SNMP (Simple Network Management Protocol)`"
  snmp-mib: ":abbr:`MIB (management information base)`"
  spn: ":abbr:`SPN (Service Principal Name)`"
  ssl: :abbr:`SSL (Secure Sockets Layer)`
  tcp: ":abbr:`TCP (Transmission Control Protocol)`"
  tls-ssl: :abbr:`TLS (Transport Layer Security)`/:abbr:`SSL (Secure Sockets Layer)`
  tls: :abbr:`TLS (Transport Layer Security)`
  totp-a: ":abbr:`TOTP (Time-based One-Time Password)` `algorithm <http://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm>`__"
  totp: ":abbr:`TOTP (Time-based One-Time Password)`"
  udp: ":abbr:`UDP (User Datagram Protocol)`"
  upn: ":abbr:`UPN (User Principal Name)`"
  uri: ":abbr:`URI (Uniform Resource Identifier)`"
  url: ":abbr:`URL (Uniform Resource Locator)`"
  utc: ":abbr:`UTC (Coordinated Universal Time)`"
  win-http-service: "MongoDB Ops Manager HTTP Service"
  xml: ":abbr:`XML (eXtensible Markup Language)`"
  yaml: ":abbr:`YAML (Yet Another Markup Language)`"
---
edition: "cloud"
tokens:
  2fa: ":abbr:`2FA (two-factor authentication)`"
  a-mms: "a Cloud Manager" #use when you need to say a(n) ___
  A-mms: "A Cloud Manager" #use when you need to say a(n) ___
  admin-title-string: "Cloud Manager"
  api-admin-backup-url: "``https://cloud.mongodb.com/api/public/v1.0/admin/backup``"
  api-url: "``https://cloud.mongodb.com/api/public/v1.0``"
  api: ":abbr:`API (Application Programming Interface)`"
  application: "Cloud Manager"
  aws: ":abbr:`AWS (Amazon Web Services)`"
  bic-full: ":bic:`MongoDB Connector for BI </>`"
  bic-short: ":bic:`BI Connector </>`"
  bson: ":abbr:`BSON (Binary Javascript Object Notation)`"
  certauth: "Certificate Authority"
  cidr: :abbr:`CIDR (Classless Inter-Domain Routing)`
  cifs: ":abbr:`CIFS (Common Internet File System)`"
  cloud: "MongoDB Cloud Manager"
  cloud-short: "Cloud Manager"
  csrs: ":abbr:`CSRS (Config Servers as Replica Sets)`"
  dn: ":abbr:`DN (Distinguished Name)`"
  dns: ":abbr:`DNS (Domain Name System)`"
  dns-srv: ":abbr:`DNS (Domain Name System)` :abbr:`SRV (Service)`"
  Epoch-time-ms: "Timestamp in the number of milliseconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__',"
  epoch-time-ms: "timestamp in the number of milliseconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__',"
  epoch-time: "Timestamp in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__"
  # epoch-time: "timestamp in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__',"
  Epoch-time: "Timestamp in the number of seconds that have elapsed since the `UNIX epoch <https://en.wikipedia.org/wiki/Unix_time?oldid=828172017>`__',"
  html: ":abbr:`HTML (Hypertext Markup Language)`"
  faq: ":abbr:`FAQ (frequently asked questions)`"
  fcv: ":abbr:`FCV (Feature Compatibility Version)`"
  fcv-link: ":manual:`FCV </reference/command/setFeatureCompatibilityVersion>`"
  fqdn: ":abbr:`FQDN (fully qualified domain name)`"
  ftdc: ":abbr:`FTDC (full-time diagnostic data capture)`"
  gssapi: ":abbr:`GSSAPI (Generic Security Services Application Program Interface)`"
  hmac: ":abbr:`HMAC (hash-based message authentication code)`"
  http: :abbr:`HTTP (HyperText Transport Protocol)`
  https: :abbr:`HTTPS (Secure HyperText Transport Protocol)`
  iam: :abbr:`IAM (Identity and Access Management)`
  iana: ":abbr:`IANA (Internet Assigned Numbers Authority)`"
  idp: ":abbr:`IdP (Identity Provider)`"
  idps: ":abbr:`IdPs (Identity Providers)`"
  ietf: ":abbr:`IETF (Internet Engineering Task Force)`"
  index-page-title: "MongoDB Cloud Manager"
  iops: :abbr:`IOPS (Input/Output Operations per Second)`
  ipaddr: :abbr:`IP (Internet Protocol)`
  ipv4: :abbr:`IPv4 (Internet Protocol version 4)`
  ipv6: :abbr:`IPv6 (Internet Protocol version 6)`
  iso3661: "`ISO 3661-1 <https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements>`__ country code"
  iso8601-duration: "Duration in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=851138376#Durations>`__ notation"
  iso8601-time: "Timestamp in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=793821205>`__ date and time format in |UTC|"
  iso8601: "`ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601?oldid=793821205>`__"
  iso: ":abbr:`ISO (International Organization for Standardization)`"
  jdk: ":abbr:`JDK (Java Development Kit)`"
  jedec: ":abbr:`JEDEC (Joint Electron Device Engineering Council Solid State Technology Association)`"
  jira: "`Jira <https://jira.mongodb.org>`__"
  json: ":abbr:`JSON (Javascript Object Notation)`"
  jvm: ":abbr:`JVM (Java Virtual Machine)`"
  k8s-configmap: "`ConfigMap <https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/>`__"
  k8s-configmaps: "`ConfigMaps <https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/>`__"
  k8s-crd: "`CustomResourceDefinition <https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/>`__"
  k8s-crds: "`CustomResourceDefinitions <https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/>`__"
  k8s-mdbrsc: "MongoDB Kubernetes resource"
  k8s-mdbrscs: "MongoDB Kubernetes resources"
  k8s-node: "`node <https://kubernetes.io/docs/concepts/architecture/nodes/>`__"
  k8s-nodes: "`nodes <https://kubernetes.io/docs/concepts/architecture/nodes/>`__"
  k8s-ns: "`namespace <https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/>`__"
  k8s-nss: "`namespaces <https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/>`__"
  k8s-obj: "`object <https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/>`__"
  k8s-objs: "`objects <https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/>`__"
  k8s-op-full: "MongoDB Enterprise Kubernetes Operator"
  k8s-op-short: "Kubernetes Operator"
  k8s-pod: "`pod <https://kubernetes.io/docs/concepts/workloads/pods/pod/>`__"
  k8s-pods: "`pods <https://kubernetes.io/docs/concepts/workloads/pods/pod/>`__"
  k8s-pv: "`Persistent Volume <https://kubernetes.io/docs/concepts/storage/persistent-volumes/>`__"
  k8s-pvc: "`Persistent Volume Claim <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims>`__"
  k8s-pvcs: "`Persistent Volume Claims <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims>`__"
  k8s-pvs: "`Persistent Volumes <https://kubernetes.io/docs/concepts/storage/persistent-volumes/>`__"
  k8s-rule: "`rule <https://kubernetes.io/docs/concepts/configuration/assign-pod-node/>`__"
  k8s-sc: "`StorageClass <https://kubernetes.io/docs/concepts/storage/storage-classes/>`__"
  k8s-secret: "`secret <https://kubernetes.io/docs/concepts/configuration/secret/>`__"
  k8s-secrets: "`secrets <https://kubernetes.io/docs/concepts/configuration/secret/>`__"
  k8s-statefulset: "`StatefulSet <https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/>`__"
  k8s-statefulsets: "`StatefulSets <https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/>`__"
  k8s: "Kubernetes"
  kdc: ":abbr:`KDC (Key Distribution Center)`"
  kmip: ":abbr:`KMIP (Key Management Interoperability)`"
  ldap: ":abbr:`LDAP (Lightweight Directory Access Protocol)`"
  ldaps: ":abbr:`LDAPS (Secure Lightweight Directory Access Protocol)`"
  mdb-support: "`MongoDB Support <https://support.mongodb.com>`__"
  mms-full: "MongoDB Cloud Manager"
  mms: "Cloud Manager"
  mms-register: ":mdbacct:`MongoDB Cloud Manager registration page </register>`"
  mms-login: ":mdbacct:`MongoDB Cloud Manager login page </login>`"
  mongo: ":binary:`~bin.mongo`"
  mongod: ":binary:`~bin.mongod`"
  mongos: ":binary:`~bin.mongos`"
  nas: ":abbr:`NAS (Network Attached Storage)`"
  nfs: ":abbr:`NFS (Network File System)`"
  onprem: "Ops Manager"
  pa: "Performance Advisor"
  pem: ":abbr:`PEM (Privacy-Enhanced Mail)`"
  pii: ":abbr:`PII (Personally identifiable information)`"
  piv: ":abbr:`PIV (Personal Identity Verification)`"
  rdp: ":abbr:`RDP (Remote Desktop Protocol)`"
  release-string: "\\  "
  rest: ":abbr:`REST (Representational State Transfer)`"
  restapi: ":abbr:`REST (Representational State Transfer)` :abbr:`API (Application Programming Interface)`"
  rhel: ":abbr:`RHEL (Red Hat Enterprise Linux)`"
  rpo: ":abbr:`RPO (recovery point objective)`"
  rto: ":abbr:`RTO (recovery time objective)`"
  s3: ":abbr:`S3 (Simple Storage Service)`"
  s: "Service"
  san: ":abbr:`SAN (Storage Area Network)`"
  saml: ":abbr:`SAML (Security Assertion Markup Language)`"
  saml-sp: ":abbr:`SP (Service Provider)`"
  sasl: ":abbr:`SASL (Simple Authentication and Security Layer)`"
  sca: ":abbr:`SCA (Strong Customer Authentication)`"
  sccc: ":abbr:`SCCC (Sync Cluster Connection Configuration)`"
  scp: ":abbr:`SCP (secure copy)`"
  service-short: "Atlas"
  service: "MongoDB Atlas"
  ses: ":abbr:`SES (Simple Email Service)`"
  sms: ":abbr:`SMS (short message service)`"
  smtp: ":abbr:`SMTP (Simple Mail Transport Protocol)`"
  snmp: ":abbr:`SNMP (Simple Network Management Protocol)`"
  snmp-mib: ":abbr:`MIB (management information base)`"
  spn: ":abbr:`SPN (Service Principal Name)`"
  ssl: :abbr:`SSL (Secure Sockets Layer)`
  tcp: ":abbr:`TCP (Transmission Control Protocol)`"
  tls-ssl: :abbr:`TLS (Transport Layer Security)`/:abbr:`SSL (Secure Sockets Layer)`
  tls: :abbr:`TLS (Transport Layer Security)`
  totp-a: ":abbr:`TOTP (Time-based One-Time Password)` `algorithm <http://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm>`__"
  totp: ":abbr:`TOTP (Time-based One-Time Password)`"
  udp: ":abbr:`UDP (User Datagram Protocol)`"
  upn: ":abbr:`UPN (User Principal Name)`"
  uri: ":abbr:`URI (Uniform Resource Identifier)`"
  url: ":abbr:`URL (Uniform Resource Locator)`"
  utc: ":abbr:`UTC (Coordinated Universal Time)`"
  xml: ":abbr:`XML (eXtensible Markup Language)`"
  yaml: ":abbr:`YAML (Yet Another Markup Language)`"
...
