# The items in the ``builders`` list are the name of Sphinx builders
# supported by ``sphinx-build``.
#
# The ``prerequsites`` list stores all targets that must build before
# sphinx can begin.
#
# The ``generated-source`` list stores all the targets that generate rst.

builders:
  - dirhtml
  - singlehtml
  - epub
  - html
  - gettext
  - changes
  - doctest
  - linkcheck
  - texinfo
prerequisites:
  - setup
  - intersphinx
  - generate-source
generated-source:
  - tables
### --- ####
web-base:
  tags:
    - web
print-base:
  tags:
    - print
### --- ####
dirhtml:
  builder: dirhtml
  inherit: web-base
html:
  builder: html
  inherit: web-base
epub:
  builder: epub
  inherit: print-base
singlehtml:
  builder: singlehtml
  inherit: web-base
...
