project: 'compass'
master_doc: 'index'
paths:
  static: ['source/.static']
theme:
  name: 'compass'
  sitename: 'MongoDB Compass'
  jira: 'DOCS'
  google_analytics: 'UA-7301842-8'
  nav_excluded:
    - /
sidebars:
  '**':
    - 'pagenav.html'
...
