project: 'ecosystem'
master_doc: 'contents'
paths:
  static: ['source/.static']
theme:
  name: 'ecosystem'
  sitename: 'MongoDB Ecosystem'
  jira: 'DOCS'
  google_analytics: 'UA-7301842-8'
  nav_excluded:
    - /drivers
    - /drivers/c
    - /drivers/cpp
    - /drivers/csharp
    - /drivers/go
    - /drivers/erlang
    - /drivers/node-js
    - /drivers/perl
    - /drivers/php
    - /drivers/python
    - /drivers/ruby
    - /drivers/scala
sidebars:
  '**':
    - 'pagenav.html'
...
