project: 'mms-manual'
master_doc: 'index'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  google_analytics: 'UA-7301842-7'
  book_path_base: 'mms-manual'
  repo: '10gen/mms-docs'
  jira: 'DOCS'
  sitename: 'Cloud Manager Docs'
  # Excluded means that a file appearing in this block will not automatically load as an .html page
  # when its corresponding link in the nav tree is clicked.
  nav_excluded:
    - /administration
    - /api
    - /application
    - /data-explorer
    - /faq
    - /installation
    - /organizations-projects
    - /performance-advisor
    - /performance-advisor/schema-advisor
    - /reference
    - /release-notes
    - /security/federated-authentication
    - /troubleshooting
    - /tutorial/configure-local-mode
    - /tutorial/manage-users
    - /tutorial/nav/access-control
    - /tutorial/nav/access-control-mongodb
    - /tutorial/nav/account-management
    - /tutorial/nav/add-servers
    - /tutorial/nav/advanced-deployments
    - /tutorial/nav/alert-resolutions
    - /tutorial/nav/alerts
    - /tutorial/nav/api-tutorials
    - /tutorial/nav/automation-agent
    - /tutorial/nav/backup-administration
    - /tutorial/nav/backup-agent
    - /tutorial/nav/backup-deployments
    - /tutorial/nav/backup-restore-deployments
    - /tutorial/nav/backup-use
    - /tutorial/nav/backup-use-operations
    - /tutorial/nav/configure-automation-agent
    - /tutorial/nav/configure-backup-agent
    - /tutorial/nav/configure-mongodb-agent
    - /tutorial/nav/configure-monitoring-agent
    - /tutorial/nav/getting-started
    - /tutorial/nav/groups-users
    - /tutorial/nav/install-application
    - /tutorial/nav/install-mongodb-agent
    - /tutorial/nav/legacy-agents
    - /tutorial/nav/manage-groups
    - /tutorial/nav/manage-hosts
    - /tutorial/nav/mongodb-agent
    - /tutorial/nav/mongodb-processes
    - /tutorial/nav/mongodb-versions
    - /tutorial/nav/monitor-and-manage
    - /tutorial/nav/monitoring-agent
    - /tutorial/nav/provision-aws-servers
    - /tutorial/nav/restore-overview
    - /tutorial/nav/security
    - /tutorial/nav/security-enable-authentication
    - /tutorial/nav/update-mongodb-agent
    - /tutorial/nav/upgrade-application
    - /tutorial/update-mongodb-agent.txt
sidebars:
  '**':
    - 'pagenav.html'
...
