project: 'php-library-manual'
master_doc: 'index'
paths:
  static: ['source/.static']
theme:
  name: 'php-library'
  project: 'docs-php-library'
  sitename: 'MongoDB PHP Library Documentation'
  repo: 'docs-php-library'
  jira: 'DOCS'
  google_analytics: 'UA-7301842-8'
  nav_excluded:
    - /
sidebars:
  '**':
    - 'pagenav.html'
...
