project: 'node-manual'
master_doc: 'index'
logo: ".static/logo.png"
paths:
  static: ['source/.static']
theme:
  name: 'ruby-driver'
  project: 'docs-node'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'node-driver'
  repo: 'docs-node'
  jira: 'DOCS'
  sitename: 'Node Driver'
  nav_excluded: []
sidebars:
  '**':
    - 'pagenav.html'
...
