project: 'docs-database-tools'
master_doc: 'index'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'database-tools'
  project: 'database-tools'
  sitename: 'MongoDB Database Tools'
  jira: 'DOCS'
  google_analytics: 'UA-7301842-8'
  repo: 'docs'
  jira: 'DOCS'
  nav_excluded:
    - /
sidebars:
  '**':
    - 'pagenav.html'
...
