project: 'mongodb-manual'
master_doc: 'contents'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'manual'
  project: 'manual'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'MongoDB-manual'
  repo: 'docs'
  jira: 'DOCS'
  sitename: 'MongoDB Docs'
  nav_excluded:
    - /administration/production-checklist
    - /aggregation
    - /applications/geospatial-indexes
    - /contributors/getting-started
    - /core/authentication
    - /core/authorization
    - /core/journaling
    - /core/map-reduce
    - /core/replica-set-architectures
    - /core/replica-set-high-availability
    - /core/replica-set-members
    - /core/sharded-cluster-components
    - /core/wiredtiger
    - /installation
    - /mongo
    - /products/bi-connector
    - /reference/command
    - /reference/indexes
    - /reference/method
    - /reference/operator/aggregation
    - /reference/operator/query
    - /reference/operator/query-modifier
    - /reference/operator/update
    - /reference/replication
    - /reference/security
    - /reference/sharding
    - /release-notes/2.4
    - /release-notes/2.6
    - /release-notes/2.8
    - /release-notes/3.0
    - /release-notes/3.2
    - /security
    - /storage
    - /tutorial/change-sharded-cluster-wiredtiger
sidebars:
  '**':
    - 'pagenav.html'
...
