# The items in the ``sphinx`` list are the name of Sphinx builders
# supported by ``sphinx-build``.
sphinx_builders:
  - 'dirhtml'
  - 'singlehtml'
  - 'html'
  - 'latex'
  - 'epub'
  - 'json'
prerequisites:
  - 'setup'
  - 'pdfs.yaml'
editions:
  - 'saas'
  - 'hosted'
### --- ####
web-base:
  tags:
    - web
    - website
print-base:
  tags:
    - print
### --- ####
hosted-web-base:
  inherit: hosted-base
  tags:
    - hosted
    - onprem
    - web
    - website
saas-web-base:
  inherit: saas-base
  tags:
    - saas
    - cloud
    - website
hosted-print-base:
  edition: hosted
  inherit: hosted-base
  tags:
    - hosted
    - onprem
    - print
saas-print-base:
  inherit: saas-base
  tags:
    - saas
    - cloud
    - print
### --- ####
dirhtml-saas:
  builder: dirhtml
  inherit: saas-web-base
dirhtml-hosted:
  builder: dirhtml
  inherit: hosted-web-base
html-saas:
  builder: html
  inherit: saas-web-base
html-hosted:
  builder: html
  inherit: hosted-web-base
gettext-saas:
  builder: gettext
  inherit: saas-web-base
gettext-hosted:
  builder: gettext
  inherit: hosted-web-base
singlehtml-saas:
  builder: singlehtml
  inherit: saas-web-base
singlehtml-hosted:
  builder: singlehtml
  inherit: hosted-web-base
epub-saas:
  builder: epub
  inherit: saas-print-base
epub-hosted:
  builder: epub
  inherit: hosted-print-base
latex-saas:
  builder: latex
  inherit: saas-print-base
latex-hosted:
  builder: latex
  inherit: hosted-print-base
json-saas:
  builder: json
  inherit: saas-web-base
json-hosted:
  builder: json
  inherit: hosted-web-base
### --- ####
root-base:
  languages: ['es', 'fr', 'ja', 'it', 'zh']
saas-base:
  inherit: root-base
  edition: saas
  excluded:
    - /application.txt
    - /administration.txt
    - /core/administration-interface.txt
    - /core/backup-alerts.txt
    - /core/deployments.txt
    - /core/functional-overview.txt
    - /core/requirements.txt
    - /core/system-overview.txt
    - /installation.txt
    - /reference/audit-events.txt
    - /reference/backup-daemon-binary.txt
    - /reference/configuration.txt
    - /reference/on-prem.txt
    - /reference/api/metrics.txt
    - /release-notes/application.txt
    - /tutorial/configure-application-high-availability.txt
    - /tutorial/configure-aws-hosts.txt
    - /tutorial/configure-backup-data-locality.txt
    - /tutorial/configure-backup-high-availability.txt
    - /tutorial/configure-for-ldap-authentication.txt
    - /tutorial/configure-jetty-https.txt
    - /tutorial/install-backup-server-with-deb-packages.txt
    - /tutorial/install-backup-server-with-rpm-packages.txt
    - /tutorial/install-on-prem-backup-server.txt
    - /tutorial/install-on-prem-from-archive.txt
    - /tutorial/install-on-prem-quick-start.txt
    - /tutorial/install-on-prem-with-deb-packages.txt
    - /tutorial/install-on-prem-with-rpm-packages.txt
    - /tutorial/manage-two-factor-authentication.txt
    - /tutorial/move-jobs-to-new-backup-daemon.txt
    - /tutorial/nav/backup-server-installation.txt
    - /tutorial/nav/install-on-prem.txt
    - /tutorial/nav/user-administration.txt
    - /tutorial/nav/high-availability.txt
    - /tutorial/nav/backup-jobs.txt
    - /tutorial/prepare-backing-mongodb-instances.txt
    - /tutorial/start-and-stop-application.txt
hosted-base:
  inherit: root-base
  edition: hosted
  excluded:
    - /automation.txt
    - /core/automation-checklist.txt
    - /reference/cluster-configuration.txt
    - /faq/automation.txt
    - /reference/automation-agent-structure.txt
    - /reference/automation-agent.txt
    - /release-notes/automation-agent.txt
    - /tutorial/getting-started-with-automation-and-provisioning.txt
    - /tutorial/getting-started-with-automation.txt
    - /tutorial/manage-deployments-with-automation.txt
    - /tutorial/nav/automation-getting-started.txt
...