project: 'atlas'
master_doc: 'index'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'mms-managed'
  google_analytics: 'UA-7301842-7'
  book_path_base: 'Managed Manual'
  repo: '10gen/cloud-docs'
  jira: 'WRITING'
  sitename: 'MongoDB Atlas'
  nav_excluded:
    - /getting-started
    - /alert-resolutions
    - /alerts
    - /analyze-slow-queries
    - /api
    - /api/atlas-admin-api
    - /api/data-api
    - /archive-snapshot
    - /atlas-search
    - /backup-restore-cluster
    - /backup/cloud-backup/overview
    - /backup/legacy-backup/overview
    - /backup/shared-tier/overview
    - /bi-connection
    - /billing
    - /cloud-providers-regions
    - /cluster-additional-settings
    - /cluster-lifecycle
    - /cluster-tier
    - /connect-to-database-deployment
    - /create-database-deployment
    - /create-new-serverless-instance
    - /database-auditing
    - /data-explorer
    - /data-lake
    - /faq
    - /global-cluster
    - /import
    - /import/mongomirror
    - /interact-with-data
    - /manage-clusters
    - /manage-database-deployments
    - /monitoring-alerts
    - /online-archive/manage-online-archive
    - /organizations-projects
    - /performance-advisor
    - /performance-advisor/schema-suggestions
    - /reference/api-resources
    - /reference/api/alerts
    - /reference/api/federation-configuration
    - /reference/atlas-search/analyzers
    - /reference/atlas-search/index-definitions
    - /reference/atlas-search/query-syntax
    - /reference/atlas-search/tutorial
    - /release-notes
    - /restoration
    - /sample-data
    - /scale-cluster
    - /security/federated-authentication
    - /security-aws-kms
    - /security-azure-kms
    - /security-gcp-kms
    - /security-kms-encryption
    - /security-ldaps
    - /setup-cluster-security
    - /tutorial/manage-organizations
    - /tutorial/manage-projects
    - /tutorial/manage-users
    - /tutorial/third-party-service-integrations
    - /triggers
    - /security/set-up-unified-aws-access
    - /monitor-cluster-metrics

sidebars:
  '**':
    - 'pagenav.html'
...
