project: 'mms-manual'
master_doc: 'index'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  google_analytics: 'UA-7301842-7'
  book_path_base: 'mms-manual'
  repo: '10gen/mms-docs'
  jira: 'DOCS'
  sitename: 'MMS Docs'
  nav_excluded:
sidebars:
  '**':
    - 'pagenav.html'
...