project: 'mongodb-manual'
master_doc: 'contents'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'manual'
  project: 'manual'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'MongoDB-manual'
  repo: 'docs'
  jira: 'DOCS'
  sitename: 'MongoDB Docs'
  nav_excluded:
    - /administration
    - /administration/production-checklist
    - /administration/indexes-management
    - /aggregation
    - /applications/geospatial-indexes
    - /applications/indexes
    - /contributors/getting-started
    - /core/2d
    - /core/2dsphere
    - /core/auditing
    - /core/authentication
    - /core/authorization
    - /core/backups
    - /core/read-isolation-consistency-recency
    - /core/databases-and-collections
    - /core/geohaystack
    - /core/index-single
    - /core/index-compound
    - /core/index-creation
    - /core/index-hashed
    - /core/index-multikey
    - /core/index-partial
    - /core/index-sparse
    - /core/index-text
    - /core/index-ttl
    - /core/index-unique
    - /core/index-wildcard
    - /core/journaling
    - /core/kerberos
    - /core/map-reduce
    - /core/operational-segregation
    - /core/query-optimization
    - /core/read-preference
    - /core/replica-set-architectures
    - /core/replica-set-high-availability
    - /core/replica-set-members
    - /core/replica-set-secondary
    - /core/transactions
    - /geospatial-queries
    - /replication
    - /core/sharded-cluster-components
    - /core/wiredtiger
    - /core/write-operations-atomicity
    - /crud
    - /indexes
    - /installation
    - /introduction
    - /mongo
    - /products/bi-connector
    - /reference/command
    - /reference/collation
    - /text-search
    - /tutorial/manage-the-database-profiler
    - /core/index-text
    - /reference/bson-types
    - /reference/configuration-options
    - /reference/indexes
    - /reference/method
    - /reference/operator/aggregation
    - /reference/operator/query
    - /reference/operator/query-modifier
    - /reference/operator/update
    - /reference/replication
    - /reference/read-concern
    - /reference/security
    - /reference/sharding
    - /reference/write-concern
    - /release-notes/2.4
    - /release-notes/2.6
    - /release-notes/2.8
    - /release-notes/3.0
    - /release-notes/3.2
    - /release-notes/3.4
    - /release-notes/3.6
    - /release-notes/4.0
    - /release-notes/4.2
    - /security
    - /sharding
    - /changeStreams
    - /core/zone-sharding
    - /core/hashed-sharding
    - /core/ranged-sharding
    - /storage
    - /tutorial/change-sharded-cluster-wiredtiger
    - /tutorial/insert-documents
    - /tutorial/query-documents
    - /tutorial/remove-documents
    - /tutorial/update-documents
    - /tutorial/enable-authentication
    - /tutorial/install-mongodb-on-ubuntu
    - /tutorial/install-mongodb-on-windows
    - /tutorial/install-mongodb-on-red-hat
    - /tutorial/install-mongodb-on-debian
    - /tutorial/install-mongodb-on-suse
    - /tutorial/install-mongodb-on-amazon
    - /tutorial/install-mongodb-enterprise-on-ubuntu
    - /tutorial/install-mongodb-enterprise-on-windows
    - /tutorial/install-mongodb-enterprise-on-red-hat
    - /tutorial/install-mongodb-enterprise-on-debian
    - /tutorial/install-mongodb-enterprise-on-suse
    - /tutorial/install-mongodb-enterprise-on-amazon
    - /tutorial/install-mongodb-on-os-x

sidebars:
  '**':
    - 'pagenav.html'
...
