project: 'kafka-connector'
master_doc: 'index'
paths:
  static: ['source/.static']
theme:
  name: 'bi-connector'
  sitename: 'MongoDB Kafka Connector'
  jira: 'DOCSP'
  google_analytics: 'UA-7301842-8'
  nav_excluded:
    - /
sidebars:
  '**':
    - 'pagenav.html'
...
