project: 'mongodb-manual'
master_doc: 'contents'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'manual'
  project: 'manual'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'MongoDB-manual'
  repo: 'docs'
  jira: 'DOCS'
  sitename: 'MongoDB Docs'
  nav_excluded: []
sidebars:
  '**':
    - 'pagenav.html'
...