# The items in the ``sphinx`` list are the name of Sphinx builders
# supported by ``sphinx-build``.
sphinx_builders:
  - 'dirhtml'
  - 'singlehtml'
  - 'html'
  - 'latex'
  - 'epub'
  - 'json'
prerequisites:
  - 'setup'
  - 'pdfs.yaml'
editions:
  - 'cloud'
  - 'classic'
  - 'onprem'
### --- ####
web-base:
  tags:
    - web
    - website
print-base:
  tags:
    - print
### --- ####
onprem-web-base:
  edition: onprem
  inherit: onprem-base
  tags:
    - onprem
    - hosted
    - web
    - website
onprem-print-base:
  edition: onprem
  inherit: onprem-base
  tags:
    - hosted
    - onprem
    - print
classic-web-base:
  edition: classic
  inherit: classic-base
  tags:
    - classic
    - web
    - website
classic-print-base:
  edition: classic
  inherit: classic-base
  tags:
    - classic
    - print
cloud-web-base:
  edition: cloud
  inherit: cloud-base
  tags:
    - cloud
    - web
    - website
cloud-print-base:
  edition: cloud
  inherit: cloud-base
  tags:
    - cloud
    - print
### --- ####
dirhtml-classic:
  builder: dirhtml
  inherit: classic-web-base
html-classic:
  builder: html
  inherit: classic-web-base
gettext-classic:
  builder: gettext
  inherit: classic-web-base
singlehtml-classic:
  builder: singlehtml
  inherit: classic-web-base
epub-classic:
  builder: epub
  inherit: classic-print-base
latex-classic:
  builder: latex
  inherit: classic-print-base
json-classic:
  builder: json
  inherit: classic-web-base
dirhtml-onprem:
  builder: dirhtml
  inherit: onprem-web-base
html-onprem:
  builder: html
  inherit: onprem-web-base
gettext-onprem:
  builder: gettext
  inherit: onprem-web-base
singlehtml-onprem:
  builder: singlehtml
  inherit: onprem-web-base
epub-onprem:
  builder: epub
  inherit: onprem-print-base
json-onprem:
  builder: json
  inherit: onprem-web-base
latex-onprem:
  builder: latex
  inherit: onprem-print-base

dirhtml-cloud:
  builder: dirhtml
  inherit: cloud-web-base
html-cloud:
  builder: html
  inherit: cloud-web-base
gettext-cloud:
  builder: gettext
  inherit: cloud-web-base
singlehtml-cloud:
  builder: singlehtml
  inherit: cloud-web-base
epub-cloud:
  builder: epub
  inherit: cloud-print-base
json-cloud:
  builder: json
  inherit: cloud-web-base
latex-cloud:
  builder: latex
  inherit: cloud-print-base
### --- ####
root-base:
  languages: ['es', 'fr', 'ja', 'it', 'zh']
### --- ####
saas-base:
  inherit: root-base
  excluded:
    - /core/administration-interface.txt
    - /core/backup-alerts.txt
    - /core/deployments.txt
    - /core/requirements.txt
    - /core/system-overview.txt
    - /installation.txt
    - /introduction.txt
    - /reference/audit-events.txt
    - /reference/configuration.txt
    - /reference/firewall-configuration.txt
    - /release-notes/application.txt
    - /tutorial/backup-the-backup-service.txt
    - /tutorial/configure-application-high-availability.txt
    - /tutorial/configure-backup-data-locality.txt
    - /tutorial/configure-backup-high-availability.txt
    - /tutorial/configure-for-ldap-authentication.txt
    - /tutorial/configure-ssl-connection-to-backing-mongodb.txt
    - /tutorial/configure-ssl-connection-to-web-interface.txt
    - /tutorial/install-basic-deployment.txt
    - /tutorial/install-on-prem-from-archive.txt
    - /tutorial/install-on-prem-windows.txt
    - /tutorial/install-on-prem-with-deb-packages.txt
    - /tutorial/install-on-prem-with-rpm-packages.txt
    - /tutorial/install-simple-test-deployment.txt
    - /tutorial/manage-two-factor-authentication.txt
    - /tutorial/move-jobs-to-new-backup-daemon.txt
    - /tutorial/nav/advanced-deployments.txt
    - /tutorial/nav/backup-jobs.txt
    - /tutorial/nav/configure-application.txt
    - /tutorial/nav/high-availability.txt
    - /tutorial/nav/upgrade-application-daemon.txt
    - /tutorial/prepare-backing-mongodb-instances.txt
    - /tutorial/start-and-stop-application.txt
    - /tutorial/test-new-deployment.txt
    - /tutorial/upgrade-on-prem-from-archive.txt
    - /tutorial/upgrade-on-prem-version-1_2-and-earlier.txt
    - /tutorial/upgrade-on-prem-with-deb-packages.txt
    - /tutorial/upgrade-on-prem-with-rpm-packages.txt
onprem-base:
  inherit: root-base
  edition: onprem
  excluded:
    - /reference/required-permissions-aws-user.txt
    - /tutorial/configure-aws-hosts.txt
    - /tutorial/configure-aws-settings.txt
    - /tutorial/connect-to-aws-server-using-ssh.txt
    - /tutorial/getting-started.txt
    - /tutorial/nav/getting-started.txt
    - /tutorial/provision-aws-servers.txt
classic-base:
  inherit: saas-base
  edition: classic
  excluded:
    - /application.txt
    - /reference/api/automation-config.txt
    - /reference/api/automation-status.txt
    - /reference/api/metrics.txt
    - /reference/cluster-configuration.txt
    - /reference/cluster-configuration-process-options.txt
    - /reference/deployment-advanced-options.txt
    - /reference/required-permissions-aws-user.txt
    - /release-notes/automation-agent.txt
    - /tutorial/add-existing-hardware.txt
    - /tutorial/add-existing-host-to-automation.txt
    - /tutorial/add-servers.txt
    - /tutorial/change-mongodb-version.txt
    - /tutorial/configure-aws-hosts.txt
    - /tutorial/configure-aws-settings.txt
    - /tutorial/connect-to-aws-server-using-ssh.txt
    - /tutorial/connect-to-mongodb.txt
    - /tutorial/create-cluster-with-api.txt
    - /tutorial/deploy-replica-set.txt
    - /tutorial/deploy-sharded-cluster.txt
    - /tutorial/deploy-standalone.txt
    - /tutorial/edit-replica-set.txt
    - /tutorial/enable-mongodb-access-control.txt
    - /tutorial/getting-started.txt
    - /tutorial/install-automation-agent-from-archive.txt
    - /tutorial/install-automation-agent-on-osx.txt
    - /tutorial/install-automation-agent-with-deb-package.txt
    - /tutorial/install-automation-agent-with-rpm-package.txt
    - /tutorial/manage-mongodb-roles.txt
    - /tutorial/manage-mongodb-users.txt
    - /tutorial/migrate-member-to-new-hardware.txt
    - /tutorial/move-agent-to-new-server.txt
    - /tutorial/nav/access-control-mongodb.txt
    - /tutorial/nav/add-servers.txt
    - /tutorial/nav/getting-started.txt
    - /tutorial/nav/management.txt
    - /tutorial/nav/install-automation-agent.txt
    - /tutorial/provision-aws-servers.txt
    - /tutorial/restart-deployment.txt
    - /tutorial/shut-down-deployment.txt
    - /tutorial/unmanage-deployment.txt
    - /tutorial/update-mongodb-version-of-deployment-via-api.txt
cloud-base:
  inherit: saas-base
  edition: cloud
  excluded:
# This entry is already in the "saas-base" section, but it appears that
# "cloud-base" needs at least one entry for the docs to build successfully.
    - /core/administration-interface.txt
...
