project: 'atlas'
master_doc: 'index'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'mms-managed'
  google_analytics: 'UA-7301842-7'
  book_path_base: 'Managed Manual'
  repo: '10gen/cloud-docs'
  jira: 'WRITING'
  sitename: 'MongoDB Atlas'
  nav_excluded:
    - /api
    - /backup-cluster
    - /connect-to-cluster
    - /create-new-cluster
    - /import
    - /import/mongomirror
    - /monitoring-alerts
    - /organizations-projects
    - /reference/api-resources
    - /reference/api/alerts
    - /setup-cluster-security
sidebars:
  '**':
    - 'pagenav.html'
...
