project: 'charts'
master_doc: 'index'
logo: ".static/logo.png"
paths:
  static: ['source/.static']
theme:
  name: 'charts'
  project: 'charts'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'charts'
  repo: 'docs-charts'
  jira: 'DOCS'
  sitename: 'Charts'
  nav_excluded:
     - /installation
     - /dashboards
     - /data-sources
     - /administration
     - /build-charts
     - /tutorials
     - /tutorial/order-data/order-data-tutorial-overview
     - /tutorial/movie-details/movie-details-tutorial-overview
     - /chart-types
     - /chart-type-reference/data-table
     - /chart-type-reference/geo-spatial
     - /chart-type-reference/choropleth
     - /chart-type-reference/grid-charts
     - /chart-type-reference/circular-charts
     - /customize-charts
     - /embedding-charts
     - /view-export-chart-data
     - /embedding-tutorials
     - /launch-charts

sidebars:
  '**':
    - 'pagenav.html'
...
