# The items in the ``sphinx`` list are the name of Sphinx builders
# supported by ``sphinx-build``.
sphinx_builders:
  - 'dirhtml'
  - 'singlehtml'
  - 'html'
prerequisites:
  - 'setup'
editions:
  - 'cloud'
  - 'onprem'
### --- ####
web-base:
  tags:
    - web
    - website
print-base:
  tags:
    - print
### --- ####
onprem-web-base:
  edition: onprem
  inherit: onprem-base
  tags:
    - onprem
    - hosted
    - web
    - website
onprem-print-base:
  edition: onprem
  inherit: onprem-base
  tags:
    - hosted
    - onprem
    - print
cloud-web-base:
  edition: cloud
  inherit: saas-base
  tags:
    - cloud
    - web
    - website
cloud-print-base:
  edition: cloud
  inherit: saas-base
  tags:
    - cloud
    - print
### --- ####
dirhtml-onprem:
  builder: dirhtml
  inherit: onprem-web-base
html-onprem:
  builder: html
  inherit: onprem-web-base
gettext-onprem:
  builder: gettext
  inherit: onprem-web-base
singlehtml-onprem:
  builder: singlehtml
  inherit: onprem-web-base
epub-onprem:
  builder: epub
  inherit: onprem-print-base
latex-onprem:
  builder: latex
  inherit: onprem-print-base
dirhtml-cloud:
  builder: dirhtml
  inherit: cloud-web-base
html-cloud:
  builder: html
  inherit: cloud-web-base
gettext-cloud:
  builder: gettext
  inherit: cloud-web-base
singlehtml-cloud:
  builder: singlehtml
  inherit: cloud-web-base
epub-cloud:
  builder: epub
  inherit: cloud-print-base
latex-cloud:
  builder: latex
  inherit: cloud-print-base
### --- ####
root-base:
  languages: ['es', 'fr', 'ja', 'it', 'zh']
### --- ####
saas-base:
  inherit: root-base
  excluded:
    - /admin-console.txt
    - /admin/admin-tab-alerts.txt
    - /admin/admin-tab-backup.txt
    - /admin/admin-tab-control-panel.txt
    - /admin/admin-tab-general.txt
    - /admin/admin-tab-server-pools.txt
    - /admin/backup/daemons-page.txt
    - /admin/backup/groom-priority-page.txt
    - /admin/backup/grooms-page.txt
    - /admin/backup/job-timeline-page.txt
    - /admin/backup/jobs-page.txt
    - /admin/backup/logs-page.txt
    - /admin/backup/oplog-stores-page.txt
    - /admin/backup/resource-usage-page.txt
    - /admin/backup/restores-page.txt
    - /admin/backup/snapshot-storage-page.txt
    - /admin/controlpanel/email-history-page.txt
    - /admin/controlpanel/send-test-message-page.txt
    - /admin/controlpanel/sms-history-page.txt
    - /admin/general/api-keys-page.txt
    - /admin/general/audits-page.txt
    - /admin/general/global-whitelist-page.txt
    - /admin/general/logs-page.txt
    - /admin/general/messages-page.txt
    - /admin/general/mongodb-usage-page.txt
    - /admin/general/ops-manager-config-page.txt
    - /admin/general/overview-page.txt
    - /admin/general/projects-page.txt
    - /admin/general/users-page.txt
    - /admin/general/version-manifest-page.txt
    - /administration.txt
    - /core/backup-overview.txt
    - /core/deployments.txt
    - /core/installation-checklist.txt
    - /core/requirements.txt
    - /core/system-alerts.txt
    - /core/system-overview.txt
    - /installation.txt
    - /reference/api/admin/backup/backup-daemon-config.txt
    - /reference/api/admin/backup/backup-group-config.txt
    - /reference/api/admin/backup/blockstore-config.txt
    - /reference/api/admin/backup/daemonConfigs/delete-one-backup-daemon-configuration.txt
    - /reference/api/admin/backup/daemonConfigs/get-all-backup-daemon-configurations.txt
    - /reference/api/admin/backup/daemonConfigs/get-one-backup-daemon-configuration-by-host.txt
    - /reference/api/admin/backup/daemonConfigs/update-one-backup-daemon-configuration.txt
    - /reference/api/admin/backup/file-system-store-config.txt
    - /reference/api/admin/backup/groups/get-all-backup-group-configurations.txt
    - /reference/api/admin/backup/groups/get-one-backup-group-configuration-by-id.txt
    - /reference/api/admin/backup/groups/update-one-backup-group-configuration.txt
    - /reference/api/admin/backup/oplog-store-config.txt
    - /reference/api/admin/backup/oplog/mongoConfigs/create-one-oplog-configuration.txt
    - /reference/api/admin/backup/oplog/mongoConfigs/delete-one-oplog-configuration.txt
    - /reference/api/admin/backup/oplog/mongoConfigs/get-all-oplog-configurations.txt
    - /reference/api/admin/backup/oplog/mongoConfigs/get-one-oplog-configuration-by-id.txt
    - /reference/api/admin/backup/oplog/mongoConfigs/update-one-oplog-configuration.txt
    - /reference/api/admin/backup/s3-blockstore-config.txt
    - /reference/api/admin/backup/snapshot/fileSystemConfigs/create-one-file-system-store-configuration.txt
    - /reference/api/admin/backup/snapshot/fileSystemConfigs/delete-one-file-system-store-configuration.txt
    - /reference/api/admin/backup/snapshot/fileSystemConfigs/get-all-file-system-store-configurations.txt
    - /reference/api/admin/backup/snapshot/fileSystemConfigs/get-one-file-system-store-configuration-by-id.txt
    - /reference/api/admin/backup/snapshot/fileSystemConfigs/update-one-file-system-store-configuration.txt
    - /reference/api/admin/backup/snapshot/mongoConfigs/create-one-blockstore-configuration.txt
    - /reference/api/admin/backup/snapshot/mongoConfigs/delete-one-blockstore-configuration.txt
    - /reference/api/admin/backup/snapshot/mongoConfigs/get-all-blockstore-configurations.txt
    - /reference/api/admin/backup/snapshot/mongoConfigs/get-one-blockstore-configuration-by-id.txt
    - /reference/api/admin/backup/snapshot/mongoConfigs/update-one-blockstore-configuration.txt
    - /reference/api/admin/backup/snapshot/s3Configs/create-one-s3-blockstore-configuration.txt
    - /reference/api/admin/backup/snapshot/s3Configs/delete-one-s3-blockstore-configuration.txt
    - /reference/api/admin/backup/snapshot/s3Configs/get-all-s3-blockstore-configurations.txt
    - /reference/api/admin/backup/snapshot/s3Configs/get-one-s3-blockstore-configuration-by-id.txt
    - /reference/api/admin/backup/snapshot/s3Configs/update-one-s3-blockstore-configuration.txt
    - /reference/api/admin/backup/sync-store-config.txt
    - /reference/api/admin/backup/sync/mongoConfigs/create-one-sync-store-configuration.txt
    - /reference/api/admin/backup/sync/mongoConfigs/delete-one-sync-store-configuration.txt
    - /reference/api/admin/backup/sync/mongoConfigs/get-all-sync-store-configurations.txt
    - /reference/api/admin/backup/sync/mongoConfigs/get-one-sync-store-configuration-by-id.txt
    - /reference/api/admin/backup/sync/mongoConfigs/update-one-sync-store-configuration.txt
    - /reference/api/agents/get-agent-versions-global.txt
    - /reference/api/agents/get-agent-versions-per-project.txt
    - /reference/api/api-keys/global/create-one-global-api-key.txt
    - /reference/api/api-keys/global/create-one-global-whitelist.txt
    - /reference/api/api-keys/global/delete-one-global-api-key.txt
    - /reference/api/api-keys/global/delete-one-global-whitelist.txt
    - /reference/api/api-keys/global/get-all-global-api-key-roles.txt
    - /reference/api/api-keys/global/get-all-global-api-keys.txt
    - /reference/api/api-keys/global/get-all-global-whitelist.txt
    - /reference/api/api-keys/global/get-one-global-api-key.txt
    - /reference/api/api-keys/global/get-one-global-whitelist.txt
    - /reference/api/api-keys/global/update-one-global-api-key.txt
    - /reference/api/api-keys/global/update-one-global-whitelist.txt
    - /reference/api/controlled-features/get-all-feature-control-policies.txt
    - /reference/api/controlled-features/get-controlled-features-for-one-project.txt
    - /reference/api/controlled-features/update-controlled-features-for-one-project.txt
    - /reference/api/diagnostic-archives.txt
    - /reference/api/diagnostics/get-project-diagnostic-archive.txt
    - /reference/api/encryption-keys.txt
    - /reference/api/events/get-all-events-global.txt
    - /reference/api/events/get-one-event-global.txt
    - /reference/api/feature-control-policies.txt
    - /reference/api/global-alert-configuration-get-all-open-alerts-triggered.txt
    - /reference/api/global-alert-configurations-create-one.txt
    - /reference/api/global-alert-configurations-delete-one.txt
    - /reference/api/global-alert-configurations-get-all.txt
    - /reference/api/global-alert-configurations-get-one.txt
    - /reference/api/global-alert-configurations-toggle-one.txt
    - /reference/api/global-alert-configurations-update-one.txt
    - /reference/api/global-alert-configurations.txt
    - /reference/api/global-alerts-ack-one.txt
    - /reference/api/global-alerts-get-all.txt
    - /reference/api/global-alerts-get-one.txt
    - /reference/api/global-alerts.txt
    - /reference/api/global-api-key-whitelists.txt
    - /reference/api/global-api-keys.txt
    - /reference/api/global-events.txt
    - /reference/api/group-server-pool-properties.txt
    - /reference/api/group-server-pool-requests.txt
    - /reference/api/group-server-pool-servers.txt
    - /reference/api/group-server-pool.txt
    - /reference/api/groups/add-or-remove-tags-from-one-group.txt
    - /reference/api/groups/get-all-groups-with-specific-tags-for-current-user.txt
    - /reference/api/groups/map-ldap-groups-to-manager-roles.txt
    - /reference/api/kmip-keys/get-master-key.txt
    - /reference/api/kmip-keys/rotate-master-key.txt
    - /reference/api/nav/administration-backup.txt
    - /reference/api/nav/server-pool.txt
    - /reference/api/server-pool-properties.txt
    - /reference/api/server-pool-requests.txt
    - /reference/api/server-pool-servers.txt
    - /reference/api/server-pool.txt
    - /reference/api/usage/generate-daily-usage-snapshot.txt
    - /reference/api/user-create-first.txt
    - /reference/api/users/delete-one-user.txt
    - /reference/api/version-manifest.txt
    - /reference/api/version-manifest/update-version-manifest.txt
    - /reference/api/version-manifest/view-version-manifest.txt
    - /reference/audit-events.txt
    - /reference/config/ui-settings.txt
    - /reference/configuration.txt
    - /reference/faq/faq-security.txt
    - /reference/snmp-traps.txt
    - /reference/third-party-licenses.txt
    - /reference/troubleshooting/system.txt
    - /reference/troubleshooting/upgrades.txt
    - /tutorial/add-message-to-interface.txt
    - /tutorial/assign-snapshot-stores-to-data-center.txt
    - /tutorial/backup-the-backup-service.txt
    - /tutorial/configure-application-high-availability.txt
    - /tutorial/configure-backup-high-availability.txt
    - /tutorial/configure-block-size.txt
    - /tutorial/configure-for-ldap-authentication.txt
    - /tutorial/configure-for-saml-authentication.txt
    - /tutorial/configure-local-mode.txt
    - /tutorial/configure-ssl-connection-to-backing-mongodb.txt
    - /tutorial/configure-ssl-connection-to-web-interface.txt
    - /tutorial/enable-appdb-monitoring.txt
    - /tutorial/encrypt-snapshots.txt
    - /tutorial/encrypt-user-credentials.txt
    - /tutorial/getting-started-with-deployments.txt
    - /tutorial/install-on-prem-from-archive.txt
    - /tutorial/install-on-prem-windows.txt
    - /tutorial/install-on-prem-with-deb-packages.txt
    - /tutorial/install-on-prem-with-rpm-packages.txt
    - /tutorial/install-simple-test-deployment.txt
    - /tutorial/manage-blockstore-storage.txt
    - /tutorial/manage-filestore-storage.txt
    - /tutorial/manage-global-alerts.txt
    - /tutorial/manage-oplog-storage.txt
    - /tutorial/manage-ports.txt
    - /tutorial/manage-s3-blockstore-storage.txt
    - /tutorial/manage-two-factor-authentication.txt
    - /tutorial/monitoring-large-deployments.txt
    - /tutorial/move-jobs-to-new-backup-daemon.txt
    - /tutorial/nav/advanced-deployments.txt
    - /tutorial/nav/backup-storage.txt
    - /tutorial/nav/install-application.txt
    - /tutorial/prepare-backing-mongodb-instances.txt
    - /tutorial/request-servers-from-pool.txt
    - /tutorial/resolve-pre-flight-check.txt
    - /tutorial/restore-full-snapshot-http.txt
    - /tutorial/restore-pit-snapshot-http.txt
    - /tutorial/retrieve-debug-diagnostics.txt
    - /tutorial/server-pool.txt
    - /tutorial/set-snapshot-expiry.txt
    - /tutorial/start-and-stop-application.txt
    - /tutorial/update-version-manifest.txt
    - /tutorial/upgrade-ops-manager.txt
    - /tutorial/use-with-http-proxy.txt
onprem-base:
  inherit: root-base
  edition: onprem
  excluded:
    - /core/pricing.txt
    - /reference/alerts/host-exposed.txt
    - /reference/api/invoices.txt
    - /reference/api/organizations/organization-get-all-invoices.txt
    - /reference/api/organizations/organization-get-one-invoice.txt
    - /reference/api/organizations/organization-get-pending-invoices.txt
    - /reference/api/ssh-keys.txt
    - /reference/faq/faq-billing.txt
    - /reference/faq/faq-mongodb-32-eol.txt
    - /reference/health-score.txt
    - /reference/legal/cloud-licensing.txt
    - /reference/legal/cloud-manager-backup-changes.txt
    - /reference/legal/cloud-manager-backup-license.txt
    - /reference/monitoring-metrics-per-plan.txt
    - /reference/required-permissions-aws-user.txt
    - /security/federated-authentication.txt
    - /security/federation-advanced-options.txt
    - /security/manage-domain-mapping.txt
    - /security/manage-idps.txt
    - /security/manage-org-mapping.txt
    - /tutorial/configure-aws-integration.txt
    - /tutorial/getting-started.txt
    - /tutorial/remove-group-from-automation.txt
    - /tutorial/reopen-locked-account.txt
    - /tutorial/restore-deployment-to-atlas.txt
...
