project: 'mongodb-manual'
master_doc: 'contents'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'manual'
  project: 'manual'
  google_analytics: 'UA-7301842-8'
  book_path_base: 'MongoDB-manual'
  repo: 'docs'
  jira: 'DOCS'
  sitename: 'MongoDB Docs'
  nav_excluded: 
    - /core/replica-set-members
    - /core/replica-set-architectures
    - /core/replica-set-high-availability
    - /applications/replication
    - /core/sharded-cluster-components
    - /core/index-types
    - /reference/security
    - /reference/indexes
    - /reference/replication
    - /reference/sharding
    - /release-notes/2.4
    - /release-notes/2.6
sidebars:
  '**':
    - 'pagenav.html'
...