name = "pymongo-arrow"
title = "PyMongoArrow"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

toc_landing_pages = []

[constants]
driver-short = "PyMongoArrow"
driver-long = "MongoDB PyMongoArrow"
version-number = "1.9"
version = "v{+version-number+}"
patch-version-number = "{+version-number+}.0"
legacy-documentation = "https://mongo-arrow.readthedocs.io/en"
api-root = "https://mongo-arrow.readthedocs.io/en/{+patch-version-number+}/api/index.html"
