file: reference/program/bsondump
name: bsondump
title: MongoDB BSON Utility
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongo
name: mongo
title: MongoDB Shell
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongod
name: mongod
title: MongoDB Server
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongos
name: mongos
title: MongoDB Sharded Cluster Query Router
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongodump
name: mongodump
title: MongoDB Data Dump Utility
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongoexport
name: mongoexport
title: MongoDB Export Utility
authors:
  - MongoDB Documentation Project
section: 1
---
file:  reference/program/mongofiles
name: mongofiles
title: MongoDB GridFS Utility
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongoimport
name: mongoimport
title: MongoDB Import Utility
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongorestore
name: mongorestore
title: MongoDB Data Restoration Tool
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongostat
name: mongostat
title: MongoDB Use Statistics
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongosniff
name: mongosniff
title: MongoDB Protocol Introspection Utility
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongotop
name: mongotop
title: MongoDB Activity Monitor
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/program/mongoperf
name: mongoperf
title: MongoDB Performance Utility
authors:
  - MongoDB Documentation Project
section: 1
---
file: reference/parameters
name: mongodb-parameters
title: MongoDB setParameter Options
authors:
  - MongoDB Documentation Project
section: 5
...
