project: 'kubernetes-operator'
master_doc: 'index'
paths:
  static: ['source/.static']
theme:
  name: 'kubernetes-operator'
  sitename: 'MongoDB Enterprise Kubernetes Operator'
  jira: 'DOCSP'
  google_analytics: 'UA-7301842-8'
  nav_excluded:
    - /
sidebars:
  '**':
    - 'pagenav.html'
...
