name = "kotlin"
title = "Kotlin Coroutine"
intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
    "https://www.mongodb.com/docs/objects.inv",
]

toc_landing_pages = [
    "/connect",
    "/crud",
    "/crud/read-operations",
    "/aggregation",
    "/builders",
    "/data-formats",
    "/logging-monitoring",
    "/security",
    "/security/auth",
    "/reference"
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"
eol = true

[constants]
driver = "kotlin"
driver-short = "Kotlin driver"
driver-long = "MongoDB Kotlin Driver"
version = "5.0"
full-version = "{+version+}.0"
language = "Kotlin"
mdb-server = "MongoDB server"
kotlin-docs = "https://kotlinlang.org"

package-name-org = "mongodb-org"
api = "https://mongodb.github.io/mongo-java-driver/{+version+}"
api-root = "https://mongodb.github.io/mongo-java-driver/{+version+}/apidocs"
core-api = "{+api-root+}/mongodb-driver-core/com/mongodb"
driver-api = "{+api-root+}/mongodb-driver-kotlin-coroutine/mongodb-driver-kotlin-coroutine/com.mongodb.kotlin.client.coroutine"
stable-api = "Stable API"
mongocrypt-version = "1.8.0"
nettyVersion = "io.netty:netty-all:4.1.79.Final"
snappyVersion = "org.xerial.snappy:snappy-java:1.1.8.4"
zstdVersion = "com.github.luben:zstd-jni:1.5.5-2"
logbackVersion = "1.2.11"
log4j2Version = "2.17.1"
serializationVersion = "1.6.0"
kotlinx-dt-version = "0.6.1"
netty-version = "io.netty:netty-all:4.1.87.Final"

[[composables]]
id = "connection-mechanism"
title = "Connection Mechanism"
options = [
  {id = "connection-string", title = "Connection String"},
  {id = "mongocred", title = "MongoCredential"},
]

[[composables]]
id = "logger"
title = "Logger"
options = [
  {id = "logback", title = "Logback"},
  {id = "log4j2", title = "Log4j2"},
]

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/>`__ to learn about currently supported versions of the Kotlin driver.\
    """
