ref: default-bind-ip-security-command-line
content: |

   :binary:`~bin.mongod` and :binary:`~bin.mongos`
   bind to localhost by default. If the members of your deployment are
   run on different hosts or if you wish remote clients to connect to
   your instance, you must specify the ``--bind_ip`` option. 

---
ref: default-bind-ip-security-config-file
content: |

   :binary:`~bin.mongod` and :binary:`~bin.mongos`
   bind to localhost by default. If the members of your deployment are
   run on different hosts or if you wish remote clients to connect to
   your deployment, you must specify the :setting:`net.bindIp` setting.
---
ref: default-bind-ip-security
content: |

   :binary:`~bin.mongod` and :binary:`~bin.mongos`
   bind to localhost by default. If the members of your deployment are
   run on different hosts or if you wish remote clients to connect to
   your deployment, you must specify ``--bind_ip`` or
   :setting:`net.bindIp`. 
---
ref: default-bind-ip-security-windows
content: |

   :binary:`mongod.exe` and
   :binary:`mongos.exe` bind to localhost by default. If the members
   of your deployment are run on different hosts or if you wish remote
   clients to connect to your deployment, you must specify
   ``--bind_ip`` or :setting:`net.bindIp`. For more information on the
   configuration file, see :doc:`configuration
   options</reference/configuration-options>`.
       
---
ref: default-bind-ip-security-additional-command-line
content: |

   Include additional options as required for your configuration. For
   instance, if you wish remote clients to connect to your deployment
   or your deployment members are run on different hosts, specify the
   ``--bind_ip``. For more information, see
   :ref:`3.6-bind_ip-compatibility`.

---
ref: default-bind-ip-security-additional-config-file
content: |

   Include additional  options as required
   for your configuration. For instance, if you wish remote clients to
   connect to your deployment or your deployment members are run on
   different hosts, specify the :setting:`net.bindIp` setting. For more
   information, see :ref:`3.6-bind_ip-compatibility`. 


...
