name = "java"
title = "Java Sync Driver"
intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
    "https://www.mongodb.com/docs/objects.inv",
]

toc_landing_pages = [
    "/get-started",
    "/connection",
    "/crud",
    "/aggregation",
    "/builders",
    "/data-formats",
    "/api-documentation",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver = "Java"
driver-long = "MongoDB Java Driver"
driver-short = "Java driver"
version = "5.1"
full-version = "{+version+}.4"
mdb-server = "MongoDB Server"
search = "MongoDB Search"
vector-search = "MongoDB Vector Search"
package-name-org = "mongodb-org"
api = "https://mongodb.github.io/mongo-java-driver/{+version+}"
api-root = "https://mongodb.github.io/mongo-java-driver/{+version+}/apidocs"
driver-api = "{+api-root+}/mongodb-driver-sync/com/mongodb/client"
core-api = "{+api-root+}/mongodb-driver-core/com/mongodb"
stable-api = "Stable API"
mongocrypt-version = "1.8.0"
nettyVersion = "io.netty:netty-all:4.1.87.Final"
snappyVersion = "org.xerial.snappy:snappy-java:1.1.10.3"
zstdVersion = "com.github.luben:zstd-jni:1.5.5-3"
logbackVersion = "1.2.11"
log4j2Version = "2.17.1"

[[composables]]
id = "connection-mechanism"
title = "Connection Mechanism"
options = [
  {id = "connection-string", title = "Connection String"},
  {id = "mongocred", title = "MongoCredential"},
]

[[composables]]
id = "logger"
title = "Logger"
options = [
  {id = "logback", title = "Logback"},
  {id = "log4j2", title = "Log4j2"},
]
