title: Select a data source in |service|.
ref: new-chart-atlas-data-source.
level: 4
content: |
  a. In the left navigation pane in |service|, click :guilabel:`Database`
     to display the :guilabel:`Database Deployments` view.  
  #. Click the :guilabel:`Browse Collections` button for the deployment 
     that contains the data source.
  #. Select the collection that you want to use to build 
     your chart.
---
title: Click the :guilabel:`Visualize Your Data` button.
ref: new-chart-atlas-visualize-data
level: 4
content: |
  |charts-short| automatically loads the data source in the Chart Builder. 
  
  .. note:: 

     If you selected a database as your data source, |charts-short| prompts 
     you to select a specific collection before you can continue building
     your chart.
---
title: Apply a suggested chart.
optional: true
ref: apply-starter-chart-atlas
level: 4
inherit:
  file: steps-build-new-chart.yaml
  ref: apply-starter-chart
---
title: Choose your chart type.
ref: new-chart-type-atlas
level: 4
inherit:
  file: steps-build-new-chart.yaml
  ref: new-chart-type
---
title: Add fields to your chart.
ref: new-chart-fields-atlas
level: 4
inherit:
  file: steps-build-new-chart.yaml
  ref: new-chart-fields

---
title: Title your chart.
ref: new-chart-title-atlas
level: 4
inherit:
  file: steps-build-new-chart.yaml
  ref: new-chart-title
---
title: Save your chart.
ref: new-chart-save-atlas
level: 4
content: |
  Once you're satisfied with your chart: 
  
  a. Click :guilabel:`Save and close` in the top right corner. 
  
  #. Save the chart to a dashboard:

     - To save to a new dashboard, click :guilabel:`New` and 
       specify a :guilabel:`Dashboard title`. 

     - To save to an existing dashboard, click :guilabel:`Existing` 
       and select a dashboard from the drop-down menu.

  #. Click :guilabel:`Save`. This saves your chart to the specified dashboard and 
     redirects you to the dashboard view.
