---
ref: upgrade-oc-edit-yaml
title: Customize the |k8s-op-short| |yaml| before upgrading it.
stepnum: 1
content: |

  To avoid breaking changes, you should ensure that you select the same settings
  as those in your existing deployment. To learn about optional |k8s-op-short| 
  installation settings, see :ref:`Operator Helm Installation Settings <meko-op-install-settings-helm>`.

  You must add your ``<openshift-pull-secret>`` to the 
  ``ServiceAccount`` definitions:

  .. literalinclude:: /includes/openshift-service-accounts.yaml
    :language: yaml
    :emphasize-lines: 9-10, 20-21, 31-32
---
ref: upgrade-oc-upgrade
inherit:
  file: steps-install-master.yaml
  ref: install-master-install
stepnum: 2
replacement:
  method: "Upgrade to the new version of the |k8s-op-short|."

content: |

  Populate the ``<version>`` placeholder and run the following |oc|:

  .. code-block:: sh

     oc apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes/{+dl-version+}/public/mongodb-kubernetes-openshift.yaml
---
ref: update-meko-oc
inherit:
  file: steps-install-master.yaml
  ref: install-master-crds
stepnum: 3
replacement:
  method: "Upgrade the |k8s-crds| for MongoDB deployments."
content: |

  Run the following |oc| command:

  Populate the ``<version>`` placeholder and run the following |oc| 
  command to deploy your chosen version of the CRDs to your |k8s| cluster:

  .. code-block::
     
     oc apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes/{+dl-version+}/public/crds.yaml
