stepnum: 1
level: 4
source:
  file: steps-source-update-automation-configuration.yaml
  ref: check-automation-config
replacement:
  variables: "Variables for Automation Config API Resources"
---
stepnum: 2
level: 4
source:
  file: steps-source-update-automation-configuration.yaml
  ref: open-for-editing
post: |
  If you're updating the {+mdbagent+}, see
  :ref:`update-monitoring-backup-versions` before continuing
  with this procedure.
---
stepnum: 3
level: 4
source:
  file: steps-source-update-automation-configuration.yaml
  ref: send-updated-configuration
replacement:
  variables: "Variables for Automation Config API Resources"
---
stepnum: 4
level: 4
source:
  file: steps-source-update-automation-configuration.yaml
  ref: confirm-update-of-config
replacement:
  variables: "Variables for Automation Config API Resources"
---
stepnum: 5
level: 4
source:
  file: steps-source-update-automation-configuration.yaml
  ref: check-deployment-status
replacement:
  variables: "Variables for Automation Config API Resources"
...
