name = "cpp-driver"
title = "C++ Driver"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
    "https://www.mongodb.com/docs/objects.inv",
]

toc_landing_pages = [
    "/api-abi-versioning",
    "/connect",
    "/read",
    "/write",
    "/indexes",
    "/security",
]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver = "cpp"
driver-long = "MongoDB C++ Driver"
driver-short = "C++ driver"
version = "3.11"
full-version = "{+version+}.1"
api = "https://mongocxx.org/api/current"
string-data-type = "``string``"
int-data-type = "``int``"
stable-api = "Stable API"
mdb-server = "MongoDB Server"
language = "C++"
search = "MongoDB Search"
vector-search = "MongoDB Vector Search"
