---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: standalone
  namespace: <metadata.namespace> # Should match metadata.namespace in
                                  # your configmap file.
spec:
  version: 4.0.6
  project: <myconfigmap> # Should match metadata.name in your
                        # configmap file.
  credentials: <mycredentials>
  type: Standalone
  persistent: true
  exposedExternally: true
...
