---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: <my-standalone>
spec:
  version: 4.2.2-ent
  opsManager:                           # Alias of cloudManager
    configMapRef:
      name: <configMap.metadata.name>   # Should match metadata.name
                                        # in your configmap file.
  credentials: <mycredentials>
  type: Standalone
  persistent: true
  exposedExternally: true
...
