---
apiVersion: v1
kind: ConfigMap
metadata:
  name: <my-configmap>
  namespace: <my-namespace>
data:
  projectName: <my-ops-manager-project-name> # Optional
  orgId: <org-id> # Optional
  baseUrl: https://<my-ops-manager-URL>

...
