---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: <myreplicaset>
  namespace: <metadata.namespace> # Should match metadata.namespace in
                                  # your configmap file.
spec:
  members: 4
  version: 4.0.6
  project: <myconfigmap> # Should match metadata.name in your
                         # configmap file.
  credentials: <mycredentials>
  type: ReplicaSet
  persistent: true
...
