---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: <myopsmanager>
spec:
  replicas: 1
  version: <opsmanagerversion>
  adminCredentials: <adminusercredentials> # Should match metadata.name
                                           # in the Kubernetes secret
                                           # for the admin user
  security:
    tls:
      ca: <om-http-cert-ca>
      secretRef:
        name: <tlscertificate> # Should match metadata.name
                               # in the Kubernetes secret
                               # for the TLS Certificate / Private Key
  externalConnectivity:
    type: LoadBalancer

  applicationDatabase:
    members: 3
    version: <mongodbversion>

...
