---
apiVersion: v1
kind: ConfigMap
metadata:
  name: <my-configmap>
  namespace: <my-namespace>
data:
  projectName: <my-ops-manager-project-name>
  orgId: <org-id> # Optional
  baseUrl: https://<my-ops-manager-URL>

  sslMMSCAConfigMap: <root-ca-configmap-name> # Must match name from step 1
  sslRequireValidMMSServerCertificates: ‘true’
...
