---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
 name: ops-manager-localmode
spec:
 replicas: 1
 version: 4.4.0-rc1
 adminCredentials: ops-manager-admin-secret
 configuration:
   # this enables local mode in Ops Manager
   automation.versions.source: remote
   automation.versions.download.baseUrl: "http://nginx-svc.<namespace>.svc.cluster.local:80"

 backup:
   enabled: false

 applicationDatabase:
   members: 3
   persistent: true
...
