name = "guides"
title = "Guides"

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://pymongo.readthedocs.io/en/stable/objects.inv",
    "https://motor.readthedocs.io/en/stable/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
    "https://www.mongodb.com/docs/php-library/master/objects.inv",
    "https://www.mongodb.com/docs/compass/current/objects.inv",
    "https://www.mongodb.com/docs/database-tools/objects.inv",
    "https://www.mongodb.com/docs/drivers/node/master/objects.inv",
    "https://www.mongodb.com/docs/drivers/go/master/objects.inv",
    "https://www.mongodb.com/docs/drivers/java/sync/master/objects.inv",
    "https://www.mongodb.com/docs/mongodb-shell/objects.inv",
]

[constants]
db-deployments = "`Database Deployments <https://cloud.mongodb.com/v2>`__"
guides-db = "sample_guides"
guides-coll = "planets"
full-java-version = "4.7.0"
full-dotnet-version = "2.17.0"
fts = "Atlas Search"
