# For handling Kanopy routing distinction between mongodb.com and products/updates _next/static request we needed to use 
# assetPrefix to move products/updates _next/static under /docs allowing for request coming from Kanopy to be handled by B2k and NextJs
# This redirect handles NextJs assuming _next/static to be under docs but when deployed in to our CDN the static folder sits at the root
# See EPIC below for more context
# https://jira.mongodb.org/browse/DOP-6064

[[redirects]]
from = "/docs/docs_static_nextjs/_next/*"
to = "/_next/:splat"
status = 200

[dev]
framework = "next"
command = "next dev"
publish = ".next"
