---
ref: update-meko-kubectl
stepnum: 1
title: "Update the MongoDB CRDs."
content: |
  
  Run the following ``kubectl`` command to deploy your chosen version of the 
  CRDs to your |k8s| cluster:

  .. code-block::
     
     kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes/{+dl-version+}/public/crds.yaml

---
ref: upgrade-get-current-deployment-configuration
stepnum: 2
title: "Get your currently deployed |k8s-op-short| configuration details."
content: |
  Run the following command to get the configuration details of your currently deployed |k8s-op-short|:

  .. code-block:: sh

     kubectl get deployment <operator-deployment-name> -n <namespace> -o yaml

---
stepnum: 3
ref: upgrade-customize-chart
title: "Customize your |k8s-op-short| |yaml| before upgrading it."
content: |

  If needed, find the appropriate example deployment |yaml| file for your
  chosen version of the |k8s-op-short| in the `GitHub repository <https://github.com/mongodb/mongodb-kubernetes/blob/1.4.0/public/>`__.
  Then, to avoid breaking changes, customize the example |yaml| file to match the configuration details
  of your currently deployed |k8s-op-short|.

---
ref: upgrade-kubectl-upgrade
inherit:
  file: steps-install-master.yaml
  ref: install-master-install
stepnum: 4
replacement:
  method: "Upgrade to the new version of the |k8s-op-short|."
content: |

  Deploy your customized |k8s-op-short| by running the following:

  .. code-block:: sh

     kubectl apply -f <customized-operator-yaml-file>.yaml
  
  If you do not need to modify the provided deployment |yaml|, you can apply it directly as follows:

  Multi-Cluster
  ~~~~~~~~~~~~~

  .. code-block:: sh

     kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes/{+dl-version+}/mongodb-enterprise-multi-cluster.yaml

  Single-Cluster
  ~~~~~~~~~~~~~~

  .. code-block:: sh

     kubectl apply -f  https://raw.githubusercontent.com/mongodb/mongodb-kubernetes/{+dl-version+}/public/mongodb-kubernetes.yaml
