name: Copy Files to docs-shared

on:
  workflow_dispatch: {} # use to manually trigger workflow
  push:
    branches:
      - "master"
    paths:
      - "source/includes/mongodb-compatibility-table-css.rst"
      - "source/includes/language-compatibility-table-cxx.rst"

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy mongodb-compat table
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "source/includes/mongodb-compatibility-table-cxx.rst"
          destination_repo: "10gen/docs-shared"
          destination_folder: "dbx"
          user_email: "docs-builder-bot@mongodb.com"
          user_name: "docs-builder-bot"
          commit_message: "Auto-import from docs-cpp"

      - name: Copy language-compat table
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "source/includes/language-compatibility-table-cxx.rst"
          destination_repo: "10gen/docs-shared"
          destination_folder: "dbx"
          user_email: "docs-builder-bot@mongodb.com"
          user_name: "docs-builder-bot"
          commit_message: "Auto-import from docs-cpp"
