name: Copy Files to docs-shared

on:
  push:
    branches:
      - 'master'
    paths:
      - 'source/includes/mongodb-compatibility-table-node.rst'
      - 'source/includes/language-compatibility-table-node.rst'
env:
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

jobs:
  copy-mongodb-compat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy mongodb-compat table
      uses: dmnemec/copy_file_to_another_repo_action@main
      with:
        source_file: 'source/includes/mongodb-compatibility-table-node.rst'
        destination_repo: '10gen/docs-shared'
        destination_folder: 'dbx'
        user_email: 'mike.woofter@mongodb.com'
        user_name: 'mongoKart'
        commit_message: 'Auto-import from docs-node'

  copy-language-compat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy language-compat table
      uses: dmnemec/copy_file_to_another_repo_action@main
      with:
        source_file: 'source/includes/language-compatibility-table-node.rst'
        destination_repo: '10gen/docs-shared'
        destination_folder: 'dbx'
        user_email: 'mike.woofter@mongodb.com'
        user_name: 'mongoKart'
        commit_message: 'Auto-import from docs-node'
