name: ToC Formatting and Linting

on:
  push:
    branches:
      - main
    paths:
      - 'content/table-of-contents/**'
      
  pull_request:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'content/table-of-contents/**'


jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
      
    env:
      NPM_BASE_64_AUTH: ${{ secrets.NPM_BASE_64_AUTH }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@d648c2dd069001a242c621c8306af467f150e99d
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: content/table-of-contents/pnpm-lock.yaml

      - name: Install
        run: pnpm install
        working-directory: ./content/table-of-contents

      - name: Lint & Format
        run: pnpm run lint && pnpm run format
        working-directory: ./content/table-of-contents

      - name: Test
        run: pnpm run test
        working-directory: ./content/table-of-contents
