name: Trigger all prod builds on ToC Changes

on:
  push:
    branches:
      - main
    paths:
      - 'content/table-of-contents/**'

env:
  NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}

jobs:
  trigger-prod-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@d648c2dd069001a242c621c8306af467f150e99d
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: content/table-of-contents/pnpm-lock.yaml

      - name: Install dependencies for table-of-contents
        run: pnpm install
        working-directory: ./content/table-of-contents

      - name: Trigger Netlify Prod Build
        run: |
          # Triggering the deploy all flow for prod sites
          pnpm run api:build --branch=prod --ap 
        working-directory: ./content/table-of-contents
