name: vale-checks
on:
  push:
    branches-ignore:
      - master

jobs:
  vale:
    name: TDBX Vale rules
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'csv'

      - name: tdbx-vale
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          files: ${{steps.files.outputs.added_modified}}
          fail_on_error: true
          token: ${{secrets.GITHUB_TOKEN}}
