name: vale-checks
on:
  pull_request:
    paths:
      - "source/**"
    paths-ignored:
      - "**.ast"

jobs:
  vale:
    name: TDBX Vale rules
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Install docutils
        run: sudo apt-get install -y docutils

      - id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: "csv"

      - name: checkout-latest-rules
        uses: actions/checkout@master
        with:
          repository: mongodb/mongodb-vale-action
          path: "./tdbx-vale-rules"
          token: ${{secrets.GITHUB_TOKEN}}

      - name: move-files-for-vale-action
        run: |
          cp tdbx-vale-rules/.vale.ini .vale.ini
          mkdir -p .github/styles/
          cp -rf tdbx-vale-rules/.github/styles/ .github/

      - name: run-vale
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          files: ${{steps.files.outputs.added_modified}}
          fail_on_error: true
          token: ${{secrets.GITHUB_TOKEN}}
